package com.carddemo.model.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Objects;

/**
 * Composite primary key class for CardAccountXref entity.
 * 
 * Required by JPA @IdClass pattern for entities with composite primary keys.
 * 
 * This class represents the combination of xrefCardNum and xrefAcctId that
 * uniquely identifies a card-account cross-reference record. Matches the
 * composite PRIMARY KEY (xref_card_num, xref_acct_id) constraint defined
 * in the database schema (Section 0.3.4).
 * 
 * JPA Requirements:
 * - Must implement Serializable interface
 * - Must have public no-arg constructor (provided by Lombok @NoArgsConstructor)
 * - Must override equals() and hashCode() methods (provided by Lombok @Data)
 * - Field names and types must exactly match the @Id fields in CardAccountXref
 * 
 * Usage:
 * This class is used internally by JPA when:
 * - Performing findById() lookups with composite key: 
 *   repository.findById(new CardAccountXrefId(cardNum, acctId))
 * - Managing entity identity in persistence context
 * - Implementing equals/hashCode for entity comparison
 * 
 * Original COBOL Key Structure:
 * - Primary key in VSAM KSDS: XREF-CARD-NUM (16 bytes) + XREF-ACCT-ID (11 bytes)
 * - Allows direct key access to cross-reference records by card-account combination
 * 
 * @see CardAccountXref
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CardAccountXrefId implements Serializable {
    
    /**
     * Serial version UID for Serializable interface.
     * 
     * Required for consistent serialization across different JVM versions.
     * Change this value if the class structure is modified in a way that
     * makes it incompatible with previously serialized versions.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Card number component of composite primary key.
     * 
     * Converted from: COBOL PIC X(16) XREF-CARD-NUM
     * 
     * Field name and type must exactly match CardAccountXref.xrefCardNum
     * per JPA @IdClass requirements.
     */
    private String xrefCardNum;

    /**
     * Account ID component of composite primary key.
     * 
     * Converted from: COBOL PIC 9(11) XREF-ACCT-ID
     * 
     * Field name and type must exactly match CardAccountXref.xrefAcctId
     * per JPA @IdClass requirements.
     */
    private Long xrefAcctId;

    /**
     * Override equals for composite key comparison.
     * 
     * Required by JPA for entity identity management in persistence context.
     * Two CardAccountXrefId instances are equal if both xrefCardNum and
     * xrefAcctId values match.
     * 
     * Generated by Lombok @Data annotation but documented here for clarity.
     * 
     * @param o Object to compare with
     * @return true if both xrefCardNum and xrefAcctId match, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        CardAccountXrefId that = (CardAccountXrefId) o;
        return Objects.equals(xrefCardNum, that.xrefCardNum) &&
               Objects.equals(xrefAcctId, that.xrefAcctId);
    }

    /**
     * Override hashCode for composite key hashing.
     * 
     * Required by JPA for entity identity management in persistence context.
     * Hash code is computed from both xrefCardNum and xrefAcctId values.
     * 
     * Generated by Lombok @Data annotation but documented here for clarity.
     * 
     * @return Hash code based on both primary key components
     */
    @Override
    public int hashCode() {
        return Objects.hash(xrefCardNum, xrefAcctId);
    }
}
