      *****************************************************************
      * Generated fixture: CARD-FIXTURE-001
      * Source: app/data/ASCII/carddata.txt
      * Records: 1 of 150 bytes each
      * SHA-256(payload, 64-bit prefix): d8dd6879893c006f
      * Generated by tests/fixtures/load_fixture.py; do not hand-edit.
      * Copyright Amazon.com, Inc. or its affiliates.
      * SPDX-License-Identifier: Apache-2.0
      *****************************************************************
      * Record #1 at byte offset 0
           MOVE X'303530303032343435333736353734303030303030303030'
             TO CARD-RECORD(1:24)
           MOVE X'303530373437416E69796120566F6E202020202020202020'
             TO CARD-RECORD(25:24)
           MOVE X'202020202020202020202020202020202020202020202020'
             TO CARD-RECORD(49:24)
           MOVE X'2020202020202020323032332D30332D3039592020202020'
             TO CARD-RECORD(73:24)
           MOVE X'202020202020202020202020202020202020202020202020'
             TO CARD-RECORD(97:24)
           MOVE X'202020202020202020202020202020202020202020202020'
             TO CARD-RECORD(121:24)
           MOVE X'202020202020'
             TO CARD-RECORD(145:6)
