      *****************************************************************
      * Generated fixture: TCATBAL-FIXTURE-001
      * Source: app/data/ASCII/tcatbal.txt
      * Records: 1 of 50 bytes each
      * SHA-256(payload, 64-bit prefix): 004cb115f34fc821
      * Generated by tests/fixtures/load_fixture.py; do not hand-edit.
      * Copyright Amazon.com, Inc. or its affiliates.
      * SPDX-License-Identifier: Apache-2.0
      *****************************************************************
      * Record #1 at byte offset 0
           MOVE X'303030303030303030303130313030303130303030303030'
             TO TRAN-CAT-BAL-RECORD(1:24)
           MOVE X'3030307B3030303030303030303030303030303030303030'
             TO TRAN-CAT-BAL-RECORD(25:24)
           MOVE X'3030'
             TO TRAN-CAT-BAL-RECORD(49:2)
