      *****************************************************************
      * Generated fixture: XREF-FIXTURE-001
      * Source: app/data/ASCII/cardxref.txt
      * Records: 1 of 36 bytes each
      * SHA-256(payload, 64-bit prefix): 2eabe56a75b834b2
      * Generated by tests/fixtures/load_fixture.py; do not hand-edit.
      * Copyright Amazon.com, Inc. or its affiliates.
      * SPDX-License-Identifier: Apache-2.0
      *****************************************************************
      * Record #1 at byte offset 0
           MOVE X'303530303032343435333736353734303030303030303035'
             TO CARD-XREF-RECORD(1:24)
           MOVE X'303030303030303030303530'
             TO CARD-XREF-RECORD(25:12)
