package com.carddemo.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

import com.carddemo.dto.account.AccountDto;
import com.carddemo.entity.Account;
import com.carddemo.entity.CardXref;
import com.carddemo.exception.AccountNotFoundException;
import com.carddemo.mapper.AccountMapper;
import com.carddemo.repository.AccountRepository;
import com.carddemo.repository.CardXrefRepository;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.orm.ObjectOptimisticLockingFailureException;

/**
 * Pure Mockito unit test for {@link AccountService} &mdash; the Spring service that
 * reproduces the two CICS online programs {@code app/cbl/COACTVWC.cbl} (account view,
 * TRANID {@code 'CAVW'}) and {@code app/cbl/COACTUPC.cbl} (account update, TRANID
 * {@code 'CAUP'}).
 *
 * <p>No Spring context and no database are involved: the three {@code final}
 * collaborators of {@link AccountService} &mdash; {@link AccountRepository},
 * {@link CardXrefRepository}, and {@link AccountMapper} &mdash; are mocked and injected
 * through the constructor generated by Lombok {@code @RequiredArgsConstructor}
 * ({@code @InjectMocks} over {@code final} fields, honouring <strong>PR-29</strong>:
 * constructor injection, never field injection). {@link MockitoExtension} runs in its
 * default <em>strict-stubs</em> mode, so each test declares only the stubs it actually
 * exercises.</p>
 *
 * <h2>Class-under-test API (verified against the committed source)</h2>
 * <p>The actual service exposes {@link AccountService#getAccount(Long)} (view) and
 * {@link AccountService#updateAccount(Long, AccountDto)} (update) &mdash; not the
 * {@code findById}/{@code update} names sketched in the original implementation prompt.
 * The view flow performs the COACTVWC two-step lookup (card cross-reference existence
 * via {@link CardXrefRepository#findByAccountId(Long)}, then the keyed master read via
 * {@link AccountRepository#findById(Object)}) before delegating entity&rarr;DTO mapping to
 * {@link AccountMapper#toDto(Account)}. The update flow loads the master record, applies a
 * COACTUPC-style {@code WS-DATACHANGED-FLAG} partial update, then persists via
 * {@link AccountRepository#saveAndFlush(Object)} (so the {@code @Version} check runs
 * synchronously, PR-22).</p>
 *
 * <h2>Preservation rules verified</h2>
 * <ul>
 *   <li><strong>PR-02</strong> &mdash; a missing account raises
 *       {@link AccountNotFoundException}, surfacing the exact COACTVWC literals
 *       {@code "Did not find this account in account card xref file"} (L130) and
 *       {@code "Did not find this account in account master file"} (L132).</li>
 *   <li><strong>PR-16</strong> &mdash; all monetary assertions use AssertJ
 *       {@code isEqualByComparingTo} (scale-insensitive {@code compareTo}), never
 *       {@code equals}; the update path is shown to normalize inbound money to scale 2.</li>
 *   <li><strong>PR-22</strong> &mdash; the service delegates the REWRITE to
 *       {@link AccountRepository#saveAndFlush(Object)} (optimistic-locking enforcement
 *       point), and a simulated {@link ObjectOptimisticLockingFailureException} is shown to
 *       be re-thrown with the exact COACTUPC race-condition message
 *       {@code "Record changed by some one else. Please review"} (L522).</li>
 * </ul>
 *
 * <h2>Test-only collaborators beyond the originally declared dependency set</h2>
 * <p>{@link AccountMapper} is a genuine third constructor dependency of the committed
 * {@link AccountService} (required so {@code @InjectMocks} can build the service), and
 * {@link CardXref} is the element type returned by the mocked
 * {@link CardXrefRepository#findByAccountId(Long)} used to drive the COACTVWC happy path.
 * Both are real, committed types; mocking/instantiating them here is the faithful way to
 * exercise the actual service API.</p>
 *
 * @see AccountService
 * @see com.carddemo.mapper.AccountMapper
 * @see com.carddemo.exception.AccountNotFoundException
 */
@ExtendWith(MockitoExtension.class)
@DisplayName("AccountService - replaces COBOL COACTVWC (view) + COACTUPC (update)")
class AccountServiceTest {

    /** Canonical 11-digit account id ({@code ACCT-ID PIC 9(11)}) used across the happy paths. */
    private static final long ACCT_ID = 11_111_111_111L;

    /** A valid-but-absent account id, exercising the not-found branches. */
    private static final long MISSING_ACCT_ID = 99_999L;

    // ----- Exact COBOL message literals (must match AccountService verbatim) -----

    /** {@code app/cbl/COACTVWC.cbl} L130. */
    private static final String MSG_NOT_IN_XREF = "Did not find this account in account card xref file";

    /** {@code app/cbl/COACTVWC.cbl} L132. */
    private static final String MSG_NOT_IN_MASTER = "Did not find this account in account master file";

    /** {@code app/cbl/COACTVWC.cbl} L122. */
    private static final String MSG_ACCT_NOT_PROVIDED = "Account number not provided";

    /** {@code app/cbl/COACTVWC.cbl} L126/L128. */
    private static final String MSG_ACCT_INVALID = "Account number must be a non zero 11 digit number";

    /** {@code app/cbl/COACTUPC.cbl} L504. */
    private static final String MSG_STATUS_YN = "Account Active Status must be Y or N";

    /** {@code app/cbl/COACTUPC.cbl} L492 (note the trailing period). */
    private static final String MSG_NO_CHANGE = "No change detected with respect to values fetched.";

    /** {@code app/cbl/COACTUPC.cbl} L522. */
    private static final String MSG_OPTIMISTIC_LOCK = "Record changed by some one else. Please review";

    /** Mocked account-master repository (replaces the VSAM {@code ACCTDAT} keyed file). */
    @Mock
    private AccountRepository accountRepository;

    /** Mocked card cross-reference repository (replaces the VSAM {@code CXACAIX} path). */
    @Mock
    private CardXrefRepository cardXrefRepository;

    /** Mocked entity&rarr;DTO mapper (third constructor dependency of {@link AccountService}). */
    @Mock
    private AccountMapper accountMapper;

    /** Class under test, with all three mocks injected via the Lombok-generated constructor (PR-29). */
    @InjectMocks
    private AccountService accountService;

    /** Captures the {@link Account} handed to {@link AccountRepository#saveAndFlush(Object)}. */
    @Captor
    private ArgumentCaptor<Account> accountCaptor;

    /** Baseline managed-entity fixture (rebuilt fresh before each test; safe to mutate). */
    private Account canonicalAccount;

    /**
     * Builds the shared baseline account fixture before each test. Performs no Mockito
     * stubbing so the {@link MockitoExtension} strict-stubs policy is honoured.
     */
    @BeforeEach
    void setUp() {
        canonicalAccount = buildAccount(ACCT_ID, new BigDecimal("1500.00"), new BigDecimal("5000.00"));
    }

    @Nested
    @DisplayName("getAccount (replaces COACTVWC view)")
    class GetAccount {

        @Test
        @DisplayName("Should return AccountDto following the COACTVWC xref->master->map flow")
        void shouldReturnAccountDtoWhenAccountExists() {
            // given: account present in both the xref (CXACAIX) and the master (ACCTDAT)
            when(cardXrefRepository.findByAccountId(ACCT_ID)).thenReturn(xrefList());
            when(accountRepository.findById(ACCT_ID)).thenReturn(Optional.of(canonicalAccount));
            when(accountMapper.toDto(canonicalAccount)).thenReturn(toDto(canonicalAccount));

            // when
            AccountDto result = accountService.getAccount(ACCT_ID);

            // then
            assertThat(result).isNotNull();
            assertThat(result.getAcctId()).isEqualTo(ACCT_ID);
            assertThat(result.getCurrBal()).isEqualByComparingTo(new BigDecimal("1500.00"));
            assertThat(result.getCreditLimit()).isEqualByComparingTo(new BigDecimal("5000.00"));
            // COACTVWC two-step lookup order: xref existence first, then the keyed master read, then map.
            verify(cardXrefRepository).findByAccountId(ACCT_ID);
            verify(accountRepository).findById(ACCT_ID);
            verify(accountMapper).toDto(canonicalAccount);
        }

        @Test
        @DisplayName("Should throw AccountNotFoundException (xref message) when not in card xref (PR-02)")
        void shouldThrowAccountNotFoundWhenAbsentFromXref() {
            // given: COACTVWC 9200-GETCARDXREF-BYACCT finds no cross-reference row
            when(cardXrefRepository.findByAccountId(MISSING_ACCT_ID)).thenReturn(List.of());

            // when / then: unchecked AccountNotFoundException carrying the verbatim COBOL literal (L130)
            assertThatThrownBy(() -> accountService.getAccount(MISSING_ACCT_ID))
                    .isInstanceOf(AccountNotFoundException.class)
                    .isInstanceOf(RuntimeException.class)
                    .hasMessage(MSG_NOT_IN_XREF);

            // the master read and the mapper are never reached on the xref short-circuit
            verifyNoInteractions(accountRepository, accountMapper);
        }

        @Test
        @DisplayName("Should throw AccountNotFoundException (master message) when in xref but not master (PR-02)")
        void shouldThrowAccountNotFoundWhenAbsentFromMaster() {
            // given: the xref links the account, but COACTVWC 9300-GETACCTDATA-BYACCT NOTFND -> code 101
            when(cardXrefRepository.findByAccountId(ACCT_ID)).thenReturn(xrefList());
            when(accountRepository.findById(ACCT_ID)).thenReturn(Optional.empty());

            // when / then: verbatim COBOL literal (L132)
            assertThatThrownBy(() -> accountService.getAccount(ACCT_ID))
                    .isInstanceOf(AccountNotFoundException.class)
                    .hasMessage(MSG_NOT_IN_MASTER);

            // mapping is never attempted when the master record is missing
            verifyNoInteractions(accountMapper);
        }

        @Test
        @DisplayName("Should correctly surface an account with a zero balance")
        void shouldHandleAccountWithZeroBalance() {
            // given
            Account zeroBalance = buildAccount(ACCT_ID, new BigDecimal("0.00"), new BigDecimal("5000.00"));
            when(cardXrefRepository.findByAccountId(ACCT_ID)).thenReturn(xrefList());
            when(accountRepository.findById(ACCT_ID)).thenReturn(Optional.of(zeroBalance));
            when(accountMapper.toDto(zeroBalance)).thenReturn(toDto(zeroBalance));

            // when
            AccountDto result = accountService.getAccount(ACCT_ID);

            // then: compareTo treats 0.00 and ZERO as numerically equal (PR-16)
            assertThat(result.getCurrBal()).isEqualByComparingTo(BigDecimal.ZERO);
            assertThat(result.getCurrBal()).isEqualByComparingTo(new BigDecimal("0.00"));
        }

        @Test
        @DisplayName("Should reject a null account id (COACTVWC 'Account number not provided', L122)")
        void shouldRejectNullAccountId() {
            // when / then: the id edit short-circuits before any repository access
            assertThatThrownBy(() -> accountService.getAccount(null))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessage(MSG_ACCT_NOT_PROVIDED);

            verifyNoInteractions(cardXrefRepository, accountRepository, accountMapper);
        }

        @Test
        @DisplayName("Should reject zero / negative / >11-digit ids (COACTVWC edit message, L126)")
        void shouldRejectOutOfRangeAccountId() {
            // when / then: each invalid id raises the same COACTVWC edit message, before any I/O
            assertThatThrownBy(() -> accountService.getAccount(0L))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessage(MSG_ACCT_INVALID);
            assertThatThrownBy(() -> accountService.getAccount(-1L))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessage(MSG_ACCT_INVALID);
            assertThatThrownBy(() -> accountService.getAccount(100_000_000_000L))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessage(MSG_ACCT_INVALID);

            verifyNoInteractions(cardXrefRepository, accountRepository, accountMapper);
        }
    }

    @Nested
    @DisplayName("updateAccount (replaces COACTUPC update)")
    class UpdateAccount {

        @Test
        @DisplayName("Should apply changed fields and delegate the REWRITE to repository.saveAndFlush (PR-22)")
        void shouldUpdateAccountAndDelegatePersistence() {
            // given
            when(accountRepository.findById(ACCT_ID)).thenReturn(Optional.of(canonicalAccount));
            when(accountRepository.saveAndFlush(any(Account.class))).thenAnswer(inv -> inv.getArgument(0));
            when(accountMapper.toDto(any(Account.class))).thenAnswer(inv -> toDto(inv.getArgument(0)));

            AccountDto update = new AccountDto();
            update.setCreditLimit(new BigDecimal("7500.00"));

            // when
            AccountDto result = accountService.updateAccount(ACCT_ID, update);

            // then: the managed entity is persisted via saveAndFlush (PR-22 optimistic-lock enforcement point)
            verify(accountRepository).saveAndFlush(accountCaptor.capture());
            Account saved = accountCaptor.getValue();
            assertThat(saved.getCreditLimit()).isEqualByComparingTo(new BigDecimal("7500.00"));
            assertThat(result.getCreditLimit()).isEqualByComparingTo(new BigDecimal("7500.00"));
        }

        @Test
        @DisplayName("Should throw AccountNotFoundException and never persist when updating a missing account (PR-02)")
        void shouldThrowAccountNotFoundWhenUpdatingMissingAccount() {
            // given: COACTUPC master read NOTFND
            when(accountRepository.findById(MISSING_ACCT_ID)).thenReturn(Optional.empty());

            AccountDto update = new AccountDto();
            update.setCreditLimit(new BigDecimal("7500.00"));

            // when / then
            assertThatThrownBy(() -> accountService.updateAccount(MISSING_ACCT_ID, update))
                    .isInstanceOf(AccountNotFoundException.class)
                    .hasMessage(MSG_NOT_IN_MASTER);

            // no REWRITE is attempted; the xref and mapper are not involved in the update flow
            verify(accountRepository, never()).saveAndFlush(any(Account.class));
            verifyNoInteractions(cardXrefRepository, accountMapper);
        }

        @Test
        @DisplayName("Should preserve fields absent from the update payload (COACTUPC partial update)")
        void shouldPreserveFieldsNotIncludedInUpdate() {
            // given
            when(accountRepository.findById(ACCT_ID)).thenReturn(Optional.of(canonicalAccount));
            when(accountRepository.saveAndFlush(any(Account.class))).thenAnswer(inv -> inv.getArgument(0));
            when(accountMapper.toDto(any(Account.class))).thenAnswer(inv -> toDto(inv.getArgument(0)));

            AccountDto update = new AccountDto();
            update.setCurrBal(new BigDecimal("999.99")); // only the balance changes

            // when
            accountService.updateAccount(ACCT_ID, update);

            // then: the single supplied field is applied; every other field retains its persisted value
            verify(accountRepository).saveAndFlush(accountCaptor.capture());
            Account saved = accountCaptor.getValue();
            assertThat(saved.getCurrBal()).isEqualByComparingTo(new BigDecimal("999.99"));        // applied
            assertThat(saved.getCreditLimit()).isEqualByComparingTo(new BigDecimal("5000.00"));   // preserved
            assertThat(saved.getCashCreditLimit()).isEqualByComparingTo(new BigDecimal("1000.00")); // preserved
            assertThat(saved.getActiveStatus()).isEqualTo("Y");                                   // preserved
            assertThat(saved.getOpenDate()).isEqualTo(LocalDate.of(2020, 1, 1));                  // preserved
            assertThat(saved.getExpirationDate()).isEqualTo(LocalDate.of(2030, 12, 31));          // preserved
            assertThat(saved.getGroupId()).isEqualTo("GROUP001");                                 // preserved
        }

        @Test
        @DisplayName("Should raise IllegalStateException 'No change detected...' when no field differs (COACTUPC L492)")
        void shouldThrowNoChangeWhenNothingDiffers() {
            // given: the only supplied field equals the persisted value -> WS-DATACHANGED-FLAG stays 0
            when(accountRepository.findById(ACCT_ID)).thenReturn(Optional.of(canonicalAccount));

            AccountDto update = new AccountDto();
            update.setCreditLimit(new BigDecimal("5000.00")); // identical to the persisted credit limit

            // when / then
            assertThatThrownBy(() -> accountService.updateAccount(ACCT_ID, update))
                    .isInstanceOf(IllegalStateException.class)
                    .hasMessage(MSG_NO_CHANGE);

            verify(accountRepository, never()).saveAndFlush(any(Account.class));
            verifyNoInteractions(accountMapper);
        }

        @Test
        @DisplayName("Should reject an active status other than Y or N (COACTUPC L504)")
        void shouldRejectInvalidActiveStatus() {
            // given
            when(accountRepository.findById(ACCT_ID)).thenReturn(Optional.of(canonicalAccount));

            AccountDto update = new AccountDto();
            update.setActiveStatus("X"); // neither Y nor N

            // when / then
            assertThatThrownBy(() -> accountService.updateAccount(ACCT_ID, update))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessage(MSG_STATUS_YN);

            verify(accountRepository, never()).saveAndFlush(any(Account.class));
            verifyNoInteractions(accountMapper);
        }

        @Test
        @DisplayName("Should translate a concurrent-modification conflict to the COACTUPC L522 message (PR-22)")
        void shouldRethrowOptimisticLockConflict() {
            // given: a real change is made, then saveAndFlush detects a @Version conflict
            when(accountRepository.findById(ACCT_ID)).thenReturn(Optional.of(canonicalAccount));
            when(accountRepository.saveAndFlush(any(Account.class)))
                    .thenThrow(new ObjectOptimisticLockingFailureException(Account.class, ACCT_ID));

            AccountDto update = new AccountDto();
            update.setCreditLimit(new BigDecimal("7500.00")); // produce a change so the REWRITE is attempted

            // when / then: rethrown with the COACTUPC race-condition literal preserved (mapped to HTTP 409).
            // hasMessageContaining (not hasMessage) because ObjectOptimisticLockingFailureException extends
            // Spring's NestedRuntimeException, whose getMessage() appends "; nested exception is ..." when a
            // cause is present; the COBOL literal is still asserted to be present verbatim.
            assertThatThrownBy(() -> accountService.updateAccount(ACCT_ID, update))
                    .isInstanceOf(ObjectOptimisticLockingFailureException.class)
                    .hasMessageContaining(MSG_OPTIMISTIC_LOCK);

            // the mapper is never reached because saveAndFlush threw before the toDto call
            verifyNoInteractions(accountMapper);
        }
    }

    @Nested
    @DisplayName("BigDecimal money handling (PR-16)")
    class MoneyHandling {

        @Test
        @DisplayName("Should compare money with isEqualByComparingTo (scale-insensitive, never equals)")
        void shouldUseIsEqualByComparingToForBigDecimal() {
            // given
            Account account = buildAccount(ACCT_ID, new BigDecimal("1234.56"), new BigDecimal("5000.00"));
            when(cardXrefRepository.findByAccountId(ACCT_ID)).thenReturn(xrefList());
            when(accountRepository.findById(ACCT_ID)).thenReturn(Optional.of(account));
            when(accountMapper.toDto(account)).thenReturn(toDto(account));

            // when
            AccountDto result = accountService.getAccount(ACCT_ID);

            // then: compareTo-based equality is scale-insensitive (1234.56 == 1234.560 numerically),
            // which is exactly why PR-16 mandates isEqualByComparingTo over equals for money.
            assertThat(result.getCurrBal()).isEqualByComparingTo(new BigDecimal("1234.56"));
            assertThat(result.getCurrBal()).isEqualByComparingTo(new BigDecimal("1234.560"));
        }

        @Test
        @DisplayName("Should normalize inbound money to scale 2 (HALF_UP) on update (PR-16)")
        void shouldNormalizeScaleToTwoOnUpdate() {
            // given: a scale-1 inbound balance
            when(accountRepository.findById(ACCT_ID)).thenReturn(Optional.of(canonicalAccount));
            when(accountRepository.saveAndFlush(any(Account.class))).thenAnswer(inv -> inv.getArgument(0));
            when(accountMapper.toDto(any(Account.class))).thenAnswer(inv -> toDto(inv.getArgument(0)));

            AccountDto update = new AccountDto();
            update.setCurrBal(new BigDecimal("200.5")); // scale 1 inbound

            // when
            accountService.updateAccount(ACCT_ID, update);

            // then: the service (via BigDecimalUtil.ensureScaleTwo) stores the value normalized to scale 2
            verify(accountRepository).saveAndFlush(accountCaptor.capture());
            Account saved = accountCaptor.getValue();
            assertThat(saved.getCurrBal().scale()).isEqualTo(2);
            assertThat(saved.getCurrBal()).isEqualByComparingTo(new BigDecimal("200.5"));
        }
    }

    // ---------------------------------------------------------------------------------------------
    // Test fixtures
    //
    // Adapted to the ACTUAL entity/DTO/service API discovered during analysis:
    //   * AccountService exposes getAccount(Long)/updateAccount(Long, AccountDto) and persists via
    //     saveAndFlush (not save); it depends on AccountRepository + CardXrefRepository + AccountMapper.
    //   * The Account entity stores the three date fields as java.time.LocalDate (NOT String), so the
    //     fixture sets them with LocalDate.of(...).
    //   * AccountDto stores the three date fields as ISO yyyy-MM-dd Strings.
    // ---------------------------------------------------------------------------------------------

    /**
     * Builds a fully-populated transient {@link Account} entity fixture mirroring the 300-byte
     * {@code ACCOUNT-RECORD} (CVACT01Y). Monetary fields are scale-2 {@link BigDecimal}; the three
     * date fields are {@link LocalDate} (matching the entity, which persists them as SQL {@code DATE}).
     *
     * @param acctId      account primary key ({@code ACCT-ID PIC 9(11)})
     * @param currBal     current balance ({@code ACCT-CURR-BAL PIC S9(10)V99})
     * @param creditLimit credit limit ({@code ACCT-CREDIT-LIMIT PIC S9(10)V99})
     * @return a populated transient {@code Account}
     */
    private Account buildAccount(Long acctId, BigDecimal currBal, BigDecimal creditLimit) {
        Account a = new Account();
        a.setAcctId(acctId);
        a.setActiveStatus("Y");
        a.setCurrBal(currBal);
        a.setCreditLimit(creditLimit);
        a.setCashCreditLimit(new BigDecimal("1000.00"));
        a.setOpenDate(LocalDate.of(2020, 1, 1));
        a.setExpirationDate(LocalDate.of(2030, 12, 31));
        a.setReissueDate(LocalDate.of(2025, 6, 1));
        a.setCurrCycCredit(new BigDecimal("0.00"));
        a.setCurrCycDebit(new BigDecimal("0.00"));
        a.setAddrZip("12345-6789");
        a.setGroupId("GROUP001");
        return a;
    }

    /**
     * Faithfully mirrors {@link AccountMapper#toDto(Account)} for stubbing the mocked mapper: money
     * fields are copied (null becomes {@code 0.00}, matching the mapper's null-safe scale-2 behaviour
     * for the scale-2 fixtures used here) and the {@link LocalDate} dates are rendered to ISO
     * {@code yyyy-MM-dd} strings. This keeps the returned DTO consistent with the {@link Account}
     * actually handed to the mapper, so assertions reflect genuine value flow-through.
     *
     * @param a the source entity (assumed non-null by callers)
     * @return an {@link AccountDto} mirroring {@code a}
     */
    private AccountDto toDto(Account a) {
        return AccountDto.builder()
                .acctId(a.getAcctId())
                .activeStatus(a.getActiveStatus())
                .currBal(moneyOrZero(a.getCurrBal()))
                .creditLimit(moneyOrZero(a.getCreditLimit()))
                .cashCreditLimit(moneyOrZero(a.getCashCreditLimit()))
                .openDate(a.getOpenDate() == null ? null : a.getOpenDate().toString())
                .expirationDate(a.getExpirationDate() == null ? null : a.getExpirationDate().toString())
                .reissueDate(a.getReissueDate() == null ? null : a.getReissueDate().toString())
                .currCycCredit(moneyOrZero(a.getCurrCycCredit()))
                .currCycDebit(moneyOrZero(a.getCurrCycDebit()))
                .addrZip(a.getAddrZip())
                .groupId(a.getGroupId())
                .build();
    }

    /** Null-safe money helper mirroring the mapper's {@code null -> 0.00} normalization. */
    private BigDecimal moneyOrZero(BigDecimal value) {
        return value == null ? new BigDecimal("0.00") : value;
    }

    /**
     * A non-empty {@code List<CardXref>} used to satisfy the COACTVWC card-cross-reference existence
     * check in {@link AccountService#getAccount(Long)} (the contents are irrelevant to the assertions;
     * only non-emptiness drives the flow past the xref step).
     *
     * @return a singleton list containing one cross-reference row
     */
    private List<CardXref> xrefList() {
        return List.of(new CardXref());
    }
}
