package com.carddemo.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

import com.carddemo.dto.customer.CustomerDto;
import com.carddemo.entity.Customer;
import com.carddemo.exception.AccountNotFoundException;
import com.carddemo.mapper.CustomerMapper;
import com.carddemo.repository.CustomerRepository;

import java.util.Optional;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

/**
 * Unit test for {@link CustomerService} &mdash; the Spring service that reproduces the
 * customer-master read of the CICS online account-view program
 * {@code app/cbl/COACTVWC.cbl} (TRANID {@code 'CAVW'}).
 *
 * <p>These are pure Mockito unit tests: no Spring context and no database are involved.
 * The two {@code final} collaborators ({@link CustomerRepository} and
 * {@link CustomerMapper}) are mocked and injected through the constructor generated by
 * Lombok {@code @RequiredArgsConstructor} ({@code @InjectMocks} over {@code final} fields,
 * honouring <strong>PR-29</strong> &mdash; constructor injection, never field injection).
 * The class under test exposes a single read method, the actual signature of which is
 * {@link CustomerService#getCustomer(Long)} &rarr; {@link CustomerDto}.</p>
 *
 * <h2>COBOL parity verified ({@code COACTVWC.cbl})</h2>
 * <ul>
 *   <li><strong>Customer-master keyed read</strong> &mdash; paragraph
 *       {@code 9400-GETCUSTDATA-BYCUST} ({@code app/cbl/COACTVWC.cbl} lines 825-870) issues
 *       {@code EXEC CICS READ DATASET('CUSTDAT') RIDFLD(CUST-ID)}; reproduced here by
 *       {@link CustomerRepository#findById(Object)} returning {@code Optional.of(customer)}.</li>
 *   <li><strong>{@code NOTFND} branch</strong> &mdash; the COBOL {@code DFHRESP(NOTFND)} arm
 *       sets 88-level {@code DID-NOT-FIND-CUST-IN-CUSTDAT} whose value is the literal
 *       {@code "Did not find associated customer in master file"}
 *       ({@code app/cbl/COACTVWC.cbl} line 134). Reproduced here by {@code Optional.empty()}
 *       driving {@link AccountNotFoundException} carrying that exact message verbatim.</li>
 * </ul>
 *
 * <h2>CRITICAL &mdash; PR-20 (SSN masking, security boundary)</h2>
 * <p>The raw 9-digit Social Security Number is PII and must <em>never</em> leave the server
 * in plain form; it is masked to {@code ***-**-####} (only the last four digits visible).
 * This test class proves the service treats {@link CustomerMapper} as the <strong>sole</strong>
 * masking authority:</p>
 * <ul>
 *   <li>The mapper is mocked and stubbed to return a DTO whose SSN is already masked; the
 *       service is asserted to return that masked value unchanged
 *       ({@link SsnMasking#shouldNeverReturnRawSsnInDto()}).</li>
 *   <li>The service is proven never to read {@code customer.getSsn()} itself &mdash; a
 *       {@link org.mockito.Mockito#spy(Object) spy} over the entity verifies
 *       {@code getSsn()} is {@code never()} invoked by the service path
 *       ({@link SsnMasking#shouldUseMapperForSsnMasking()}), so masking cannot be bypassed
 *       or duplicated outside the mapper.</li>
 * </ul>
 *
 * <p>The SSN is modeled as a {@link String} on both the {@link Customer} entity
 * ({@code ssn VARCHAR(9)}, leading zeros preserved per PR-13) and the {@link CustomerDto},
 * so the fixtures below use string SSN values throughout.</p>
 *
 * @see CustomerService
 * @see com.carddemo.mapper.CustomerMapper
 * @see com.carddemo.exception.AccountNotFoundException
 */
@ExtendWith(MockitoExtension.class)
@DisplayName("CustomerService - replaces COBOL COACTVWC customer read (PR-20 SSN masking)")
class CustomerServiceTest {

    /** Canonical customer primary key ({@code CUST-ID PIC 9(09)}); one of the 50 seeded customers. */
    private static final Long CANONICAL_CUST_ID = 100000001L;

    /** A customer id guaranteed absent from the repository, exercising the {@code NOTFND} path. */
    private static final Long MISSING_CUST_ID = 999L;

    /** Raw, unmasked 9-digit SSN as stored on the entity ({@code CUST-SSN PIC 9(09)}). */
    private static final String RAW_SSN = "123456789";

    /** Masked SSN as produced by {@link CustomerMapper} on outbound responses (PR-20). */
    private static final String MASKED_SSN = "***-**-6789";

    /**
     * The exact COBOL {@code NOTFND} message literal from {@code app/cbl/COACTVWC.cbl} line 134
     * (88-level {@code DID-NOT-FIND-CUST-IN-CUSTDAT}), surfaced verbatim by the service.
     */
    private static final String NOT_FOUND_MESSAGE = "Did not find associated customer in master file";

    /** Mocked customer-master repository (replaces the VSAM {@code CUSTDAT} keyed file). */
    @Mock
    private CustomerRepository customerRepository;

    /** Mocked entity&rarr;DTO mapper; the authoritative PR-20 SSN-masking boundary. */
    @Mock
    private CustomerMapper customerMapper;

    /** Class under test, with both mocks injected via the Lombok-generated constructor (PR-29). */
    @InjectMocks
    private CustomerService customerService;

    /** Baseline managed-entity fixture carrying the raw SSN. */
    private Customer customer;

    /** Baseline outbound DTO fixture carrying the masked SSN (as the mapper would produce). */
    private CustomerDto maskedDto;

    /**
     * Builds the shared baseline fixtures before each test. Intentionally performs no Mockito
     * stubbing so that the {@link MockitoExtension} strict-stubs policy is honoured (each test
     * declares only the stubs it actually exercises).
     */
    @BeforeEach
    void setUp() {
        customer = buildCustomer(CANONICAL_CUST_ID, "John", "Doe", RAW_SSN);
        maskedDto = buildDto(CANONICAL_CUST_ID, "John", "Doe", MASKED_SSN);
    }

    @Nested
    @DisplayName("Customer lookup by ID")
    class FindById {

        @Test
        @DisplayName("Should return CustomerDto when customer exists")
        void shouldFindCustomerById() {
            // given: COACTVWC 9400-GETCUSTDATA-BYCUST keyed read succeeds, mapper produces the DTO
            when(customerRepository.findById(CANONICAL_CUST_ID)).thenReturn(Optional.of(customer));
            when(customerMapper.toDto(customer)).thenReturn(maskedDto);

            // when
            CustomerDto result = customerService.getCustomer(CANONICAL_CUST_ID);

            // then
            assertThat(result).isNotNull();
            assertThat(result.getCustId()).isEqualTo(CANONICAL_CUST_ID);
            verify(customerMapper).toDto(customer);
        }

        @Test
        @DisplayName("Should throw AccountNotFoundException with the exact COBOL message when "
                + "customer not found (mirrors COACTVWC 'Did not find associated customer in master file')")
        void shouldThrowExceptionWhenCustomerNotFound() {
            // given: the COBOL DFHRESP(NOTFND) arm — no customer for this id
            when(customerRepository.findById(MISSING_CUST_ID)).thenReturn(Optional.empty());

            // when / then: unchecked AccountNotFoundException carrying the verbatim COBOL literal
            assertThatThrownBy(() -> customerService.getCustomer(MISSING_CUST_ID))
                    .isInstanceOf(AccountNotFoundException.class)
                    .isInstanceOf(RuntimeException.class)
                    .hasMessage(NOT_FOUND_MESSAGE);

            // the not-found path short-circuits before any mapping is attempted
            verifyNoInteractions(customerMapper);
        }

        @Test
        @DisplayName("Should delegate entity->DTO conversion (including SSN masking) to CustomerMapper")
        void shouldDelegateMappingToCustomerMapper() {
            // given: a fully-populated entity is returned by the keyed read
            when(customerRepository.findById(CANONICAL_CUST_ID)).thenReturn(Optional.of(customer));
            when(customerMapper.toDto(customer)).thenReturn(maskedDto);

            // when
            CustomerDto result = customerService.getCustomer(CANONICAL_CUST_ID);

            // then: the conversion (and, per PR-20, the SSN masking within it) is the mapper's job,
            // invoked with the exact managed entity the repository returned — not the service's.
            assertThat(result).isSameAs(maskedDto);
            verify(customerMapper).toDto(customer);
        }
    }

    @Nested
    @DisplayName("SSN Masking (PR-20)")
    class SsnMasking {

        @Test
        @DisplayName("Should never return raw SSN in DTO (PR-20: SSN masked as ***-**-####)")
        void shouldNeverReturnRawSsnInDto() {
            // given: entity holds the raw SSN; mapper yields a DTO with the masked SSN
            when(customerRepository.findById(CANONICAL_CUST_ID)).thenReturn(Optional.of(customer));
            when(customerMapper.toDto(customer)).thenReturn(maskedDto);

            // when
            CustomerDto result = customerService.getCustomer(CANONICAL_CUST_ID);

            // then: only the masked form reaches the caller; raw digits must be absent
            assertThat(result.getSsn()).isEqualTo(MASKED_SSN);
            assertThat(result.getSsn()).doesNotContain("12345");
            assertThat(result.getSsn()).isNotEqualTo(RAW_SSN);
        }

        @Test
        @DisplayName("Should use the mapper as the SOLE masking point; service never reads the raw SSN")
        void shouldUseMapperForSsnMasking() {
            // given: a spy over the entity lets us prove the service never touches the raw SSN
            Customer spied = spy(buildCustomer(CANONICAL_CUST_ID, "John", "Doe", RAW_SSN));
            when(customerRepository.findById(CANONICAL_CUST_ID)).thenReturn(Optional.of(spied));
            when(customerMapper.toDto(spied)).thenReturn(maskedDto);

            // when
            CustomerDto result = customerService.getCustomer(CANONICAL_CUST_ID);

            // then: masking is delegated to the mapper...
            assertThat(result.getSsn()).isEqualTo(MASKED_SSN);
            verify(customerMapper).toDto(spied);
            // ...and the service NEVER reads customer.getSsn() directly — the mapper is the single
            // authoritative masking boundary (PR-20), so masking can be neither bypassed nor duplicated.
            verify(spied, never()).getSsn();
        }
    }

    // ---------------------------------------------------------------------------------------------
    // Test fixtures
    //
    // Adapted to the ACTUAL entity/DTO accessors discovered during analysis: the SSN is a String on
    // both Customer and CustomerDto (CUST-SSN PIC 9(09) -> VARCHAR(9), leading zeros preserved per
    // PR-13), and the entity exposes getFirstName/getLastName/getSsn (not COBOL-prefixed names).
    // ---------------------------------------------------------------------------------------------

    /**
     * Builds a transient {@link Customer} entity fixture with only the fields exercised by these
     * tests populated. The remaining 500-byte {@code CUSTOMER-RECORD} fields are irrelevant here
     * because the {@link CustomerMapper} is mocked.
     *
     * @param custId    customer primary key ({@code CUST-ID PIC 9(09)})
     * @param firstName first name ({@code CUST-FIRST-NAME PIC X(25)})
     * @param lastName  last name ({@code CUST-LAST-NAME PIC X(25)})
     * @param ssn       raw 9-digit SSN ({@code CUST-SSN PIC 9(09)}), stored as a {@link String}
     * @return a populated transient {@code Customer} entity
     */
    private Customer buildCustomer(Long custId, String firstName, String lastName, String ssn) {
        Customer c = new Customer();
        c.setCustId(custId);
        c.setFirstName(firstName);
        c.setLastName(lastName);
        c.setSsn(ssn);
        return c;
    }

    /**
     * Builds a {@link CustomerDto} fixture representing the mapper's masked output for the matching
     * entity. The {@code maskedSsn} argument is expected to be in PR-20 {@code ***-**-####} form.
     *
     * @param custId    customer primary key
     * @param firstName first name
     * @param lastName  last name
     * @param maskedSsn the masked SSN ({@code ***-**-####}) as produced by {@link CustomerMapper}
     * @return a populated {@code CustomerDto}
     */
    private CustomerDto buildDto(Long custId, String firstName, String lastName, String maskedSsn) {
        CustomerDto dto = new CustomerDto();
        dto.setCustId(custId);
        dto.setFirstName(firstName);
        dto.setLastName(lastName);
        dto.setSsn(maskedSsn);
        return dto;
    }
}
