package com.carddemo.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.carddemo.dto.user.UserCreateRequest;
import com.carddemo.dto.user.UserDto;
import com.carddemo.entity.User;
import com.carddemo.exception.AccountNotFoundException;
import com.carddemo.mapper.UserMapper;
import com.carddemo.repository.UserRepository;

import java.util.List;
import java.util.Optional;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.security.crypto.password.PasswordEncoder;

/**
 * Unit test for {@link UserService} &mdash; the Spring service that replaces the four CICS
 * online user-administration programs
 * ({@code app/cbl/COUSR00C.cbl} list, {@code COUSR01C.cbl} add, {@code COUSR02C.cbl} update,
 * {@code COUSR03C.cbl} delete).
 *
 * <p>These are pure Mockito unit tests: no Spring context and no database are involved. The
 * three {@code final} collaborators ({@link UserRepository}, {@link PasswordEncoder} and
 * {@link UserMapper}) are mocked and injected through the constructor generated by Lombok
 * {@code @RequiredArgsConstructor} ({@code @InjectMocks} over {@code final} fields, honouring
 * <strong>PR-29</strong> &mdash; constructor injection, never field injection).</p>
 *
 * <h2>CRITICAL &mdash; PR-17 (BCrypt password storage)</h2>
 * <p>This is one of the most security-sensitive test classes in the codebase. It proves the
 * service NEVER stores, returns, or compares a plaintext password:</p>
 * <ul>
 *   <li>On create the raw password is passed to {@link PasswordEncoder#encode(CharSequence)}
 *       <em>before</em> the entity is persisted; the value written to
 *       {@link User#getSecUsrPwd()} is the BCrypt hash (verified with
 *       {@code startsWith("$2")} and {@code isNotEqualTo(rawPassword)}), never the clear-text
 *       input.</li>
 *   <li>On update a supplied (non-blank) password is always re-encoded (a raw value can never
 *       be diffed against a stored BCrypt hash), while a {@code null}/blank password leaves the
 *       existing hash untouched &mdash; {@code passwordEncoder.encode(...)} is verified to be
 *       called or {@code never()} called accordingly.</li>
 *   <li>Because the encoder is mocked, salt randomisation is simulated by returning two distinct
 *       hashes for the same raw input, proving the service relies on the encoder rather than a
 *       hard-coded hash.</li>
 * </ul>
 *
 * <h2>COBOL parity verified</h2>
 * <ul>
 *   <li><strong>COUSR01C</strong> (add) &mdash; required-field validation order
 *       (First Name &rarr; Last Name &rarr; User ID &rarr; Password &rarr; User Type) with the
 *       exact legacy messages, plus the {@code DUPKEY}/{@code DUPREC} "User ID already exist..."
 *       branch (here {@link DataIntegrityViolationException}).</li>
 *   <li><strong>COUSR02C</strong> (update) &mdash; compare-and-update with the
 *       "Please modify to update ..." no-change branch (here {@link IllegalStateException}) and
 *       PR-17 password re-encoding.</li>
 *   <li><strong>COUSR03C</strong> (delete) &mdash; read-to-confirm-then-delete, with the
 *       {@code NOTFND} branch raising {@link AccountNotFoundException}.</li>
 *   <li><strong>COUSR00C</strong> (list) &mdash; the COBOL {@code STARTBR}/{@code READNEXT}
 *       browse cursor replaced by a stateless Spring Data {@link Pageable}; PR-19 role flag
 *       ({@code 'A'}/{@code 'U'}) stored verbatim.</li>
 * </ul>
 *
 * @see UserService
 * @see com.carddemo.entity.User
 * @see com.carddemo.mapper.UserMapper
 */
@ExtendWith(MockitoExtension.class)
@DisplayName("UserService - CRITICAL PR-17 BCrypt verification + COUSR00/01/02/03 logic")
class UserServiceTest {

    @Mock
    private UserRepository userRepository;

    @Mock
    private PasswordEncoder passwordEncoder;

    @Mock
    private UserMapper userMapper;

    @InjectMocks
    private UserService userService;

    @Captor
    private ArgumentCaptor<User> userCaptor;

    /** Canonical raw (plaintext) password used across the create/compliance scenarios. */
    private static final String RAW_PASSWORD = "PASSWORD";

    /**
     * A realistic 60-character BCrypt hash (prefix {@code $2a$}) standing in for the value the
     * mocked {@link PasswordEncoder} returns. The tests only rely on the {@code "$2"} prefix and
     * on it differing from the raw input, never on a real BCrypt computation.
     */
    private static final String BCRYPT_HASH =
            "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy";

    /** Raw password used for the update re-encoding scenario. */
    private static final String NEW_RAW_PASSWORD = "NEWPASS";

    /** A second, distinct BCrypt-shaped hash returned when the update re-encodes a new password. */
    private static final String NEW_BCRYPT_HASH =
            "$2a$10$E9PqL3hZ8nF1cR2kuJ7mNuWl5qErsymXJ9zJZ0xR8s9k8m3pZ8nC";

    @BeforeEach
    void setUp() {
        // MockitoExtension constructs the system-under-test via @InjectMocks over the Lombok
        // @RequiredArgsConstructor (PR-29: constructor injection over final fields). Confirm the
        // wiring succeeded so every test starts from a known-good, fully-injected state.
        assertThat(userService).isNotNull();
    }

    // ------------------------------------------------------------------------------------------
    // Test helpers
    // ------------------------------------------------------------------------------------------

    /**
     * Builds a {@link User} entity using the REAL entity setters
     * ({@code setUserId}/{@code setFirstName}/{@code setLastName}/{@code setSecUsrPwd}/{@code setUserType}).
     *
     * @param userId       the primary-key user id (uppercase by convention)
     * @param passwordHash the stored password hash (a BCrypt hash, never plaintext)
     * @param userType     the role discriminator ({@code 'A'} or {@code 'U'}, PR-19)
     * @return a fully populated transient {@link User}
     */
    private User buildUser(String userId, String passwordHash, String userType) {
        User u = new User();
        u.setUserId(userId);
        u.setFirstName("First");
        u.setLastName("Last");
        u.setSecUsrPwd(passwordHash);
        u.setUserType(userType);
        return u;
    }

    /**
     * Builds a {@link UserCreateRequest} test input with a default first/last name and
     * {@code userType = 'U'}; only the id and the raw password vary per scenario.
     *
     * @param userId      the requested user id
     * @param rawPassword the raw (plaintext) password the service must BCrypt-encode (PR-17)
     * @return a populated {@link UserCreateRequest}
     */
    private UserCreateRequest createRequest(String userId, String rawPassword) {
        UserCreateRequest r = new UserCreateRequest();
        r.setUserId(userId);
        r.setFirstName("First");
        r.setLastName("Last");
        r.setPassword(rawPassword);
        r.setUserType("U");
        return r;
    }

    // ==========================================================================================
    // Group 1 - Create user (replaces COUSR01C) - CRITICAL BCrypt verification (PR-17)
    // ==========================================================================================
    @Nested
    @DisplayName("Create user (CRITICAL BCrypt verification)")
    class CreateUser {

        @Test
        @DisplayName("Should BCrypt-encode password before saving (PR-17 mandatory)")
        void shouldCreateUserWithBcryptHashedPassword() {
            // given
            UserCreateRequest request = new UserCreateRequest();
            request.setUserId("NEWUSER1");
            request.setFirstName("Jane");
            request.setLastName("Doe");
            request.setPassword(RAW_PASSWORD);
            request.setUserType("U");

            when(userRepository.existsById("NEWUSER1")).thenReturn(false);
            when(passwordEncoder.encode(RAW_PASSWORD)).thenReturn(BCRYPT_HASH);
            when(userRepository.save(any(User.class))).thenAnswer(invocation -> invocation.getArgument(0));
            when(userMapper.toDto(any(User.class))).thenReturn(new UserDto());

            // when
            userService.createUser(request);

            // then - the encoder was invoked exactly once with the RAW password (never a pre-hash)
            verify(passwordEncoder, times(1)).encode(eq(RAW_PASSWORD));
            verify(userRepository).save(userCaptor.capture());
            User saved = userCaptor.getValue();

            // CRITICAL (PR-17): the persisted password must be the BCrypt hash, never plaintext
            assertThat(saved.getSecUsrPwd())
                    .as("PR-17: password must be a BCrypt hash, NOT plaintext")
                    .isNotEqualTo(RAW_PASSWORD)
                    .isEqualTo(BCRYPT_HASH)
                    .startsWith("$2");
        }

        @Test
        @DisplayName("Should reject a duplicate user id (COUSR01C DUPKEY/DUPREC -> 'User ID already exist...')")
        void shouldRejectDuplicateUserId() {
            // given - all fields valid so processing reaches the existsById duplicate check
            UserCreateRequest request = createRequest("ADMIN001", RAW_PASSWORD);
            when(userRepository.existsById("ADMIN001")).thenReturn(true);

            // when / then
            assertThatThrownBy(() -> userService.createUser(request))
                    .isInstanceOf(DataIntegrityViolationException.class)
                    .hasMessageContaining("already exist");

            // a rejected duplicate must never encode a password or persist anything
            verify(passwordEncoder, never()).encode(anyString());
            verify(userRepository, never()).save(any(User.class));
        }

        @Test
        @DisplayName("Should store userType 'A' for an ADMIN user (PR-19)")
        void shouldCreateAdminUserWithTypeA() {
            // given
            UserCreateRequest request = new UserCreateRequest();
            request.setUserId("ADMIN009");
            request.setFirstName("Ada");
            request.setLastName("Admin");
            request.setPassword(RAW_PASSWORD);
            request.setUserType("A");

            when(userRepository.existsById("ADMIN009")).thenReturn(false);
            when(passwordEncoder.encode(RAW_PASSWORD)).thenReturn(BCRYPT_HASH);
            when(userRepository.save(any(User.class))).thenAnswer(invocation -> invocation.getArgument(0));
            when(userMapper.toDto(any(User.class))).thenReturn(new UserDto());

            // when
            userService.createUser(request);

            // then
            verify(userRepository).save(userCaptor.capture());
            assertThat(userCaptor.getValue().getUserType())
                    .as("PR-19: 'A' must be stored verbatim as the ADMIN role flag")
                    .isEqualTo("A");
        }

        @Test
        @DisplayName("Should store userType 'U' for a regular user (PR-19)")
        void shouldCreateRegularUserWithTypeU() {
            // given
            UserCreateRequest request = createRequest("USER0009", RAW_PASSWORD);

            when(userRepository.existsById("USER0009")).thenReturn(false);
            when(passwordEncoder.encode(RAW_PASSWORD)).thenReturn(BCRYPT_HASH);
            when(userRepository.save(any(User.class))).thenAnswer(invocation -> invocation.getArgument(0));
            when(userMapper.toDto(any(User.class))).thenReturn(new UserDto());

            // when
            userService.createUser(request);

            // then
            verify(userRepository).save(userCaptor.capture());
            assertThat(userCaptor.getValue().getUserType())
                    .as("PR-19: 'U' must be stored verbatim as the USER role flag")
                    .isEqualTo("U");
        }

        @Test
        @DisplayName("Should reject a blank first name with the exact COUSR01C message")
        void shouldRejectBlankFirstName() {
            // given - first blank field stops processing (COUSR01C validation order)
            UserCreateRequest request = createRequest("USER0010", RAW_PASSWORD);
            request.setFirstName("   ");

            // when / then
            assertThatThrownBy(() -> userService.createUser(request))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessageContaining("First Name");

            // validation must short-circuit before any encoding or persistence
            verify(passwordEncoder, never()).encode(anyString());
            verify(userRepository, never()).save(any(User.class));
        }
    }

    // ==========================================================================================
    // Group 2 - Update user (replaces COUSR02C) - CRITICAL BCrypt re-encoding (PR-17)
    // ==========================================================================================
    @Nested
    @DisplayName("Update user (CRITICAL BCrypt re-encoding)")
    class UpdateUser {

        @Test
        @DisplayName("Should re-encode the password when a new one is supplied (PR-17)")
        void shouldUpdateUserAndReencodePasswordIfChanged() {
            // given - existing user holds a current BCrypt hash; request supplies a NEW password
            String userId = "USER0001";
            User existing = buildUser(userId, BCRYPT_HASH, "U");
            // names/userType match the existing record so the PASSWORD change alone drives the update
            UserCreateRequest request = createRequest(userId, NEW_RAW_PASSWORD);

            when(userRepository.findById(userId)).thenReturn(Optional.of(existing));
            when(passwordEncoder.encode(NEW_RAW_PASSWORD)).thenReturn(NEW_BCRYPT_HASH);
            when(userRepository.save(any(User.class))).thenAnswer(invocation -> invocation.getArgument(0));
            when(userMapper.toDto(any(User.class))).thenReturn(new UserDto());

            // when
            userService.updateUser(userId, request);

            // then - the NEW raw password was re-encoded and the NEW hash persisted (never the raw)
            verify(passwordEncoder, times(1)).encode(NEW_RAW_PASSWORD);
            verify(userRepository).save(userCaptor.capture());
            assertThat(userCaptor.getValue().getSecUsrPwd())
                    .as("PR-17: a changed password must be re-encoded to a BCrypt hash")
                    .isNotEqualTo(NEW_RAW_PASSWORD)
                    .isEqualTo(NEW_BCRYPT_HASH)
                    .startsWith("$2");
        }

        @Test
        @DisplayName("Should NOT re-encode password if empty in update request (preserve existing hash)")
        void shouldNotReencodePasswordIfEmptyInUpdate() {
            // given - existing user; request changes the names but supplies a null password
            String userId = "USER0001";
            User existing = buildUser(userId, BCRYPT_HASH, "U");

            UserCreateRequest updateReq = new UserCreateRequest();
            updateReq.setUserId(userId);
            updateReq.setFirstName("UpdatedFirst");
            updateReq.setLastName("UpdatedLast");
            updateReq.setPassword(null); // no password change
            updateReq.setUserType("U");

            when(userRepository.findById(userId)).thenReturn(Optional.of(existing));
            when(userRepository.save(any(User.class))).thenAnswer(invocation -> invocation.getArgument(0));
            when(userMapper.toDto(any(User.class))).thenReturn(new UserDto());

            // when
            userService.updateUser(userId, updateReq);

            // then - the encoder is never invoked and the original hash is preserved (PR-17)
            verify(passwordEncoder, never()).encode(anyString());
            verify(userRepository).save(userCaptor.capture());
            assertThat(userCaptor.getValue().getSecUsrPwd())
                    .as("PR-17: a null/blank password must leave the existing BCrypt hash untouched")
                    .isEqualTo(BCRYPT_HASH)
                    .startsWith("$2");
        }

        @Test
        @DisplayName("Should throw when updating a non-existent user (COUSR02C NOTFND)")
        void shouldThrowExceptionWhenUpdatingNonExistentUser() {
            // given
            String userId = "MISSING1";
            UserCreateRequest request = createRequest(userId, RAW_PASSWORD);
            when(userRepository.findById(userId)).thenReturn(Optional.empty());

            // when / then
            assertThatThrownBy(() -> userService.updateUser(userId, request))
                    .isInstanceOf(AccountNotFoundException.class);

            verify(userRepository, never()).save(any(User.class));
            verify(passwordEncoder, never()).encode(anyString());
        }

        @Test
        @DisplayName("Should throw 'Please modify to update ...' when nothing changed (COUSR02C)")
        void shouldThrowWhenNoFieldsChangedOnUpdate() {
            // given - request matches the stored record exactly and supplies no password
            String userId = "USER0001";
            User existing = buildUser(userId, BCRYPT_HASH, "U"); // firstName "First", lastName "Last"

            UserCreateRequest unchanged = new UserCreateRequest();
            unchanged.setUserId(userId);
            unchanged.setFirstName("First");
            unchanged.setLastName("Last");
            unchanged.setPassword(null);
            unchanged.setUserType("U");

            when(userRepository.findById(userId)).thenReturn(Optional.of(existing));

            // when / then
            assertThatThrownBy(() -> userService.updateUser(userId, unchanged))
                    .isInstanceOf(IllegalStateException.class)
                    .hasMessageContaining("modify");

            // nothing changed -> no save, no encode
            verify(userRepository, never()).save(any(User.class));
            verify(passwordEncoder, never()).encode(anyString());
        }
    }

    // ==========================================================================================
    // Group 3 - Delete user (replaces COUSR03C)
    // ==========================================================================================
    @Nested
    @DisplayName("Delete user (replaces COUSR03C)")
    class DeleteUser {

        @Test
        @DisplayName("Should delete an existing user (read-to-confirm then delete)")
        void shouldDeleteUserById() {
            // given
            String userId = "USER0001";
            User existing = buildUser(userId, BCRYPT_HASH, "U");
            when(userRepository.findById(userId)).thenReturn(Optional.of(existing));

            // when
            userService.deleteUser(userId);

            // then - the previously-loaded entity is deleted
            verify(userRepository).delete(existing);
        }

        @Test
        @DisplayName("Should throw when deleting a non-existent user (COUSR03C NOTFND)")
        void shouldThrowExceptionWhenDeletingNonExistentUser() {
            // given
            String userId = "MISSING1";
            when(userRepository.findById(userId)).thenReturn(Optional.empty());

            // when / then
            assertThatThrownBy(() -> userService.deleteUser(userId))
                    .isInstanceOf(AccountNotFoundException.class);

            verify(userRepository, never()).delete(any(User.class));
        }
    }

    // ==========================================================================================
    // Group 4 - Find users (replaces COUSR00C list + keyed read)
    // ==========================================================================================
    @Nested
    @DisplayName("Find users (replaces COUSR00C)")
    class FindUsers {

        @Test
        @DisplayName("Should return a page of users (Pageable replaces the COUSR00C browse cursor)")
        void shouldReturnAllUsers() {
            // given - three users on the requested page
            Pageable pageable = PageRequest.of(0, 10);
            List<User> users = List.of(
                    buildUser("USER0001", BCRYPT_HASH, "U"),
                    buildUser("USER0002", BCRYPT_HASH, "U"),
                    buildUser("ADMIN001", BCRYPT_HASH, "A"));
            Page<User> page = new PageImpl<>(users, pageable, users.size());

            when(userRepository.findAll(pageable)).thenReturn(page);
            when(userMapper.toDto(any(User.class))).thenReturn(new UserDto());

            // when
            Page<UserDto> result = userService.listUsers(pageable);

            // then
            assertThat(result.getTotalElements()).isEqualTo(3);
            assertThat(result.getContent()).hasSize(3);
            verify(userMapper, times(3)).toDto(any(User.class));
        }

        @Test
        @DisplayName("Should find a single user by id")
        void shouldFindUserById() {
            // given
            String userId = "USER0001";
            User user = buildUser(userId, BCRYPT_HASH, "U");
            UserDto dto = new UserDto();
            dto.setUserId(userId);

            when(userRepository.findById(userId)).thenReturn(Optional.of(user));
            when(userMapper.toDto(user)).thenReturn(dto);

            // when
            UserDto result = userService.getUser(userId);

            // then - the mapped DTO is returned (and the password hash is never exposed by the mapper)
            assertThat(result).isSameAs(dto);
            assertThat(result.getUserId()).isEqualTo(userId);
        }

        @Test
        @DisplayName("Should throw when getting a non-existent user")
        void shouldThrowExceptionWhenGettingNonExistentUser() {
            // given
            String userId = "MISSING1";
            when(userRepository.findById(userId)).thenReturn(Optional.empty());

            // when / then
            assertThatThrownBy(() -> userService.getUser(userId))
                    .isInstanceOf(AccountNotFoundException.class);
        }

        @Test
        @DisplayName("Should normalize the user id to uppercase before lookup (COSGN00C UPPER-CASE convention)")
        void shouldNormalizeUserIdToUpperCaseOnGet() {
            // given - the stored key is uppercase; the request uses lowercase
            User user = buildUser("USER0001", BCRYPT_HASH, "U");
            when(userRepository.findById("USER0001")).thenReturn(Optional.of(user));
            when(userMapper.toDto(user)).thenReturn(new UserDto());

            // when
            userService.getUser("user0001");

            // then - the repository was queried with the uppercased id
            verify(userRepository).findById("USER0001");
        }
    }

    // ==========================================================================================
    // Group 5 - PR-17 Compliance - NEVER store plaintext (the most security-critical scenarios)
    // ==========================================================================================
    @Nested
    @DisplayName("PR-17 Compliance - Never store plaintext")
    class BCryptCompliance {

        @Test
        @DisplayName("Should never store a plaintext password on create")
        void shouldNeverStorePlaintextPasswordOnCreate() {
            // given
            UserCreateRequest request = createRequest("USER0009", RAW_PASSWORD);

            when(userRepository.existsById("USER0009")).thenReturn(false);
            when(passwordEncoder.encode(RAW_PASSWORD)).thenReturn(BCRYPT_HASH);
            when(userRepository.save(any(User.class))).thenAnswer(invocation -> invocation.getArgument(0));
            when(userMapper.toDto(any(User.class))).thenReturn(new UserDto());

            // when
            userService.createUser(request);

            // then - the persisted credential is the BCrypt hash, never the literal "PASSWORD"
            verify(userRepository).save(userCaptor.capture());
            assertThat(userCaptor.getValue().getSecUsrPwd())
                    .as("PR-17: the stored password must never equal the raw input")
                    .isNotEqualTo(RAW_PASSWORD)
                    .startsWith("$2");
        }

        @Test
        @DisplayName("Two users with same password should get different hashes (BCrypt salt behavior)")
        void twoUsersWithSamePasswordShouldHaveDifferentHashes() {
            // given - the (mocked) encoder returns a distinct hash on each call, modelling BCrypt's
            // per-call random salt; this proves the service relies on the encoder, not a fixed hash
            when(userRepository.existsById(anyString())).thenReturn(false);
            when(passwordEncoder.encode(RAW_PASSWORD))
                    .thenReturn("$2a$10$firstUserDistinctSaltHashAAAAAAAAAAAAAAAAAAAAAAAAAA")
                    .thenReturn("$2a$10$secondUserDistinctSaltHashBBBBBBBBBBBBBBBBBBBBBBBBB");
            when(userRepository.save(any(User.class))).thenAnswer(invocation -> invocation.getArgument(0));
            when(userMapper.toDto(any(User.class))).thenReturn(new UserDto());

            UserCreateRequest req1 = createRequest("USER0001", RAW_PASSWORD);
            UserCreateRequest req2 = createRequest("USER0002", RAW_PASSWORD);

            // when
            userService.createUser(req1);
            userService.createUser(req2);

            // then
            verify(passwordEncoder, times(2)).encode(RAW_PASSWORD);
            verify(userRepository, times(2)).save(userCaptor.capture());
            List<User> savedUsers = userCaptor.getAllValues();
            assertThat(savedUsers.get(0).getSecUsrPwd())
                    .as("each user must receive a distinct BCrypt hash (salt randomization)")
                    .isNotEqualTo(savedUsers.get(1).getSecUsrPwd());
            assertThat(savedUsers.get(0).getSecUsrPwd()).startsWith("$2");
            assertThat(savedUsers.get(1).getSecUsrPwd()).startsWith("$2");
        }
    }
}
