#!/bin/sh
# =============================================================================
# frontend/docker-entrypoint.d/15-carddemo-resolver.sh
#
# Generates the nginx `resolver` directive that frontend/nginx.conf includes, so
# the same image re-resolves the `api-gateway` upstream on every request under
# Docker Compose (embedded DNS on 127.0.0.11) and under Kubernetes (the cluster
# DNS service address), without either address being hard-coded in the committed
# configuration.
#
# Placement contract (frontend/Dockerfile):
#   Copied executable to /docker-entrypoint.d/. The nginx image's own
#   /docker-entrypoint.sh runs every executable /docker-entrypoint.d/*.sh in
#   name order before it execs nginx, so this file runs on EVERY container start
#   (including a restart) and always precedes the configuration load.
#
# Output contract (frontend/nginx.conf):
#   Writes /tmp/carddemo-nginx/resolver.conf, which nginx.conf pulls in with the
#   wildcard `include /tmp/carddemo-nginx/*.conf;` inside its http{} context.
#   /tmp is a writable tmpfs in both topologies (Compose `tmpfs:`, Kubernetes
#   `emptyDir`), which the read-only root filesystem otherwise forbids.
# =============================================================================
set -eu

resolver_dir=/tmp/carddemo-nginx
resolver_file="${resolver_dir}/resolver.conf"
resolv_conf=/etc/resolv.conf

# Docker's embedded DNS server. Used only if /etc/resolv.conf names no
# nameserver at all, which neither Docker nor Kubernetes normally produces.
fallback_nameserver=127.0.0.11

mkdir -p "${resolver_dir}"
chmod 755 "${resolver_dir}"

# Collect the IPv4 nameservers of this container. IPv6 addresses are skipped
# because they must be bracketed in the resolver directive and the upstream is
# reached over IPv4 on both container networks.
# The base image's 15-local-resolvers.envsh exports NGINX_LOCAL_RESOLVERS from this
# container's /etc/resolv.conf when NGINX_ENTRYPOINT_LOCAL_RESOLVERS is set (it is, in
# frontend/Dockerfile). It is preferred when present; the /etc/resolv.conf scan below is
# the fallback, so the resolver is still materialized if the base image drops the helper.
nameservers="${NGINX_LOCAL_RESOLVERS:-}"
if [ -z "${nameservers}" ] && [ -r "${resolv_conf}" ]; then
    nameservers=$(awk '$1 == "nameserver" && $2 ~ /^[0-9]+(\.[0-9]+){3}$/ { printf "%s ", $2 }' "${resolv_conf}" \
        | tr -s ' ' | sed 's/[[:space:]]*$//')
fi

if [ -z "${nameservers}" ]; then
    echo "$0: no IPv4 nameserver in ${resolv_conf}; falling back to ${fallback_nameserver}"
    nameservers="${fallback_nameserver}"
fi

# valid=10s bounds how long a resolved address is reused, so a recreated
# upstream container is picked up within one interval. ipv6=off suppresses the
# AAAA lookup that would otherwise be attempted for every request.
{
    echo "# Generated by $0 on container start - do not edit."
    echo "resolver ${nameservers} valid=10s ipv6=off;"
    echo "resolver_timeout 5s;"
} > "${resolver_file}"
chmod 644 "${resolver_file}"

echo "$0: nginx resolver set to: ${nameservers}"
