package com.carddemo.service;

import com.carddemo.dto.user.UserCreateRequest;
import com.carddemo.dto.user.UserDto;
import com.carddemo.entity.User;
import com.carddemo.exception.AccountNotFoundException;
import com.carddemo.mapper.UserMapper;
import com.carddemo.repository.UserRepository;
import java.util.List;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * User administration service replacing four CICS online programs:
 * <ul>
 *   <li>{@code app/cbl/COUSR00C.cbl} (TRANID {@code 'CU00'}) &mdash; List users (10 per page;
 *       PF7=prev / PF8=next), ported to {@link #listUsers(Pageable)}.</li>
 *   <li>{@code app/cbl/COUSR01C.cbl} (TRANID {@code 'CU01'}) &mdash; Add user, ported to
 *       {@link #createUser(UserCreateRequest)}.</li>
 *   <li>{@code app/cbl/COUSR02C.cbl} (TRANID {@code 'CU02'}) &mdash; Update user (load existing,
 *       compare each field, save only when something changed), ported to
 *       {@link #updateUser(String, UserCreateRequest)}.</li>
 *   <li>{@code app/cbl/COUSR03C.cbl} (TRANID {@code 'CU03'}) &mdash; Delete user (read to confirm
 *       it exists, then delete), ported to {@link #deleteUser(String)}.</li>
 * </ul>
 *
 * <p>The persisted shape is the 80-byte {@code SEC-USER-DATA} record from
 * {@code app/cpy/CSUSR01Y.cpy} ({@code SEC-USR-ID X(08)}, {@code SEC-USR-FNAME X(20)},
 * {@code SEC-USR-LNAME X(20)}, {@code SEC-USR-PWD X(08)} &mdash; widened to a 60-character
 * BCrypt hash in Java, {@code SEC-USR-TYPE X(01)}, {@code SEC-USR-FILLER X(23)}), modeled by
 * the {@link User} JPA entity.</p>
 *
 * <p><strong>PR-17 &mdash; BCrypt password storage.</strong> Every password is BCrypt-encoded
 * via {@link PasswordEncoder#encode(CharSequence)} <em>before</em> the entity is persisted, on
 * both create and (when a new password is supplied) update. Plaintext passwords are never
 * stored, transmitted, or compared. This modernizes the original COBOL plaintext handling
 * ({@code COUSR01C} stored {@code PASSWDI} directly into {@code SEC-USR-PWD}; {@code COUSR02C}
 * compared {@code PASSWDI = SEC-USR-PWD} in clear text). Because a raw password can never be
 * compared against a stored BCrypt hash, the update flow always re-encodes when a password is
 * supplied (see {@link #updateUser(String, UserCreateRequest)}).</p>
 *
 * <p><strong>PR-18 &mdash; programmatic authorization.</strong> The class-level
 * {@code @PreAuthorize("hasRole('ADMIN')")} requires {@code ROLE_ADMIN} for every method. This
 * is defense-in-depth: {@code UserController} carries the same annotation at the REST boundary,
 * but enforcing it here too closes the documented gap from Tech Spec &sect;6.4 &mdash; the
 * original {@code COUSR00C}-{@code COUSR03C} programs had <em>no</em> programmatic authorization
 * check and relied solely on admin-menu routing in {@code COADM01C}, so a client invoking the
 * {@code CU0x} transactions directly bypassed the only safeguard.</p>
 *
 * <p><strong>PR-19 &mdash; role discriminator.</strong> {@code userType} is stored verbatim as
 * {@code 'A'} (ADMIN) or {@code 'U'} (USER). The mapping of that flag to a Spring Security
 * {@code GrantedAuthority} ({@code ROLE_ADMIN} / {@code ROLE_USER}) is performed downstream by
 * {@code CustomAuthorityMapper} / {@code UserDetailsServiceImpl} and by {@link User#getAuthorities()};
 * this service only persists the flag.</p>
 *
 * <p><strong>PR-24 &mdash; transaction boundaries.</strong> Read methods are
 * {@code @Transactional(readOnly = true)}; every write method is {@code @Transactional}, matching
 * the implicit CICS {@code SYNCPOINT} unit-of-work that bracketed each pseudo-conversational
 * interaction. <strong>PR-29</strong> &mdash; all collaborators are injected through the
 * constructor generated by Lombok {@code @RequiredArgsConstructor} over {@code final} fields
 * (no field injection).</p>
 *
 * <p>The exact COBOL operator-facing message strings are preserved character-for-character
 * (for example {@code "First Name can NOT be empty..."}, {@code "User ID already exist..."},
 * {@code "Please modify to update ..."}) so that downstream behavior and the parity tests match
 * the legacy system.</p>
 *
 * @see com.carddemo.controller.UserController
 * @see com.carddemo.entity.User
 * @see com.carddemo.mapper.UserMapper
 * @since 1.0
 */
@Service
@RequiredArgsConstructor
@Slf4j
@PreAuthorize("hasRole('ADMIN')")
public class UserService {

    /**
     * Valid {@code SEC-USR-TYPE} values per PR-19 &mdash; {@code 'A'} (ADMIN) and {@code 'U'}
     * (USER). Used by {@link #createUser(UserCreateRequest)} as a defense-in-depth membership
     * check (the primary guard is the {@code @Pattern("[AU]")} constraint on
     * {@link UserCreateRequest#getUserType()} at the REST boundary). Mirrors the COBOL
     * {@code 88-level} role flags from {@code app/cpy/CSUSR01Y.cpy}.
     */
    private static final List<String> VALID_USER_TYPES = List.of("A", "U");

    /** Spring Data JPA repository for {@link User} persistence (replaces the VSAM {@code USRSEC} file). */
    private final UserRepository userRepository;

    /**
     * BCrypt {@link PasswordEncoder} (PR-17). Concrete implementation
     * ({@code BCryptPasswordEncoder}) is supplied by the security configuration; this service
     * depends only on the abstraction.
     */
    private final PasswordEncoder passwordEncoder;

    /** Maps {@link User} entities to {@link UserDto}, deliberately excluding the password hash (PR-17/PR-20). */
    private final UserMapper userMapper;

    /**
     * Lists users one page at a time, replacing the {@code COUSR00C} (TRANID {@code 'CU00'})
     * browse cursor &mdash; the COBOL {@code STARTBR} / {@code READNEXT} / {@code READPREV}
     * sequence driven by PF7 (previous) and PF8 (next) over the {@code USRSEC} file is replaced
     * by a stateless Spring Data {@link Pageable}, recomputed from the request on every call.
     *
     * <p>Each entity is converted with {@link UserMapper#toDto(User)}, which omits the BCrypt
     * password hash (PR-17/PR-20), so the hash never crosses the REST boundary.</p>
     *
     * @param pageable the page request (page number, page size, and optional sort)
     * @return a page of {@link UserDto} (never {@code null}; empty when no users match the page)
     */
    @Transactional(readOnly = true)
    public Page<UserDto> listUsers(Pageable pageable) {
        log.debug("Listing users - page {} size {}", pageable.getPageNumber(), pageable.getPageSize());
        return userRepository.findAll(pageable).map(userMapper::toDto);
    }

    /**
     * Retrieves a single user by id, replacing the keyed {@code USRSEC} read performed by the
     * {@code COUSR02C}/{@code COUSR03C} lookup paragraphs.
     *
     * <p>The id is uppercased before lookup to honor the COBOL uppercase-id convention (e.g.,
     * {@code "ADMIN001"}, {@code "USER0001"}; see {@code COSGN00C} {@code FUNCTION UPPER-CASE}).
     * A missing record &mdash; the COBOL {@code DFHRESP(NOTFND)} branch &mdash; raises
     * {@link AccountNotFoundException}, mapped to HTTP 404 by {@code GlobalExceptionHandler}.</p>
     *
     * @param userId the user id (case-insensitive; normalized to uppercase)
     * @return the matching {@link UserDto} (without the password hash, per PR-17)
     * @throws AccountNotFoundException if no user exists with the given id
     */
    @Transactional(readOnly = true)
    public UserDto getUser(String userId) {
        log.debug("Retrieving user {}", userId);
        // AccountNotFoundException is reused as the generic "not found" (-> HTTP 404). Its
        // (String) constructor prepends "Account not found: ", so the bare id is passed to
        // produce a clean "Account not found: <id>" message (avoids a doubled prefix). The
        // GlobalExceptionHandler surfaces ex.getMessage() to the client.
        User user = userRepository.findById(userId.toUpperCase())
                .orElseThrow(() -> new AccountNotFoundException(userId));
        return userMapper.toDto(user);
    }

    /**
     * Creates a new user, porting {@code COUSR01C} (TRANID {@code 'CU01'}).
     *
     * <p>Validation order is preserved exactly from {@code COUSR01C} paragraph
     * {@code PROCESS-ENTER-KEY} ({@code EVALUATE TRUE}, lines 117-151): First Name &rarr; Last
     * Name &rarr; User ID &rarr; Password &rarr; User Type. The first blank field stops
     * processing and yields the original COBOL message. These checks are defense-in-depth &mdash;
     * the {@code @NotBlank} constraints on {@link UserCreateRequest} reject the same conditions at
     * the REST boundary first &mdash; but they are reproduced here so the service is correct when
     * invoked directly and so the exact legacy strings are guaranteed.</p>
     *
     * <p>After validation the id is uppercased and a duplicate check ({@code existsById}) mirrors
     * the COBOL {@code DFHRESP(DUPKEY)} / {@code DFHRESP(DUPREC)} handling, raising
     * {@link DataIntegrityViolationException} ({@code "User ID already exist..."}, HTTP 409). The
     * raw password is BCrypt-encoded (PR-17) before the entity is saved, and {@code userType} is
     * stored uppercased ({@code 'A'} / {@code 'U'}, PR-19).</p>
     *
     * @param req the create request (raw password; never persisted in clear text)
     * @return the created user as a {@link UserDto} (without the password hash)
     * @throws IllegalArgumentException        if any required field is blank (exact COBOL message)
     * @throws DataIntegrityViolationException  if the user id already exists
     */
    @Transactional
    public UserDto createUser(UserCreateRequest req) {
        log.info("Creating user {}", req.getUserId());

        // Defense-in-depth validation, preserving the COUSR01C order and exact messages.
        if (req.getFirstName() == null || req.getFirstName().isBlank()) {
            throw new IllegalArgumentException("First Name can NOT be empty...");
        }
        if (req.getLastName() == null || req.getLastName().isBlank()) {
            throw new IllegalArgumentException("Last Name can NOT be empty...");
        }
        if (req.getUserId() == null || req.getUserId().isBlank()) {
            throw new IllegalArgumentException("User ID can NOT be empty...");
        }
        if (req.getPassword() == null || req.getPassword().isBlank()) {
            throw new IllegalArgumentException("Password can NOT be empty...");
        }
        // COUSR01C only checks for blank; the agent specification tightens this to
        // "not empty AND in {'A','U'}" (PR-19). Both failure modes reuse the COBOL message.
        String userType = req.getUserType() == null ? null : req.getUserType().toUpperCase();
        if (userType == null || userType.isBlank() || !VALID_USER_TYPES.contains(userType)) {
            throw new IllegalArgumentException("User Type can NOT be empty...");
        }

        String upperId = req.getUserId().toUpperCase();

        // Mirrors the COUSR01C DUPKEY/DUPREC branch: reject a pre-existing id up front.
        if (userRepository.existsById(upperId)) {
            throw new DataIntegrityViolationException("User ID already exist...");
        }

        User user = new User();
        user.setUserId(upperId);
        user.setFirstName(req.getFirstName());
        user.setLastName(req.getLastName());
        user.setSecUsrPwd(passwordEncoder.encode(req.getPassword())); // PR-17: BCrypt encode before persist
        user.setUserType(userType);                                   // PR-19: 'A' or 'U'

        try {
            User saved = userRepository.save(user);
            log.info("User {} has been added ...", saved.getUserId());
            return userMapper.toDto(saved);
        } catch (DataIntegrityViolationException e) {
            // Race condition: another transaction inserted the same id between the
            // existsById check and the flush. Preserve the original COBOL message.
            throw new DataIntegrityViolationException("User ID already exist...", e);
        }
    }

    /**
     * Updates an existing user, porting {@code COUSR02C} (TRANID {@code 'CU02'}).
     *
     * <p>Reproduces the COBOL compare-and-update logic (paragraph block lines 218-243): the
     * existing record is loaded, each supplied field is compared to the stored value, and a save
     * is performed only when at least one field actually changed. When nothing changed the COBOL
     * emits {@code "Please modify to update ..."}; here that becomes {@link IllegalStateException}
     * with the identical message (mapped to HTTP 422 by {@code GlobalExceptionHandler}).</p>
     *
     * <p><strong>Password (PR-17).</strong> COBOL compared {@code PASSWDI = SEC-USR-PWD} in clear
     * text; in Java a raw password cannot be compared against a stored BCrypt hash, so whenever a
     * non-blank password is supplied it is re-encoded and the record is treated as modified. A
     * {@code null}/blank password leaves the existing hash untouched (administrators may edit
     * other fields without forcing a password rotation). {@code userType} is compared and stored
     * uppercased (PR-19); {@code userId} is the immutable primary key and is never changed.</p>
     *
     * @param userId the id of the user to update (case-insensitive; normalized to uppercase)
     * @param req    the update request (any non-null/changed field is applied)
     * @return the updated user as a {@link UserDto} (without the password hash)
     * @throws AccountNotFoundException if no user exists with the given id
     * @throws IllegalStateException    if no field changed ({@code "Please modify to update ..."})
     */
    @Transactional
    public UserDto updateUser(String userId, UserCreateRequest req) {
        log.info("Updating user {}", userId);

        String upperId = userId.toUpperCase();
        User user = userRepository.findById(upperId)
                .orElseThrow(() -> new AccountNotFoundException(userId)); // -> 404 (see getUser note)

        boolean modified = false;

        if (req.getFirstName() != null && !req.getFirstName().equals(user.getFirstName())) {
            user.setFirstName(req.getFirstName());
            modified = true;
        }
        if (req.getLastName() != null && !req.getLastName().equals(user.getLastName())) {
            user.setLastName(req.getLastName());
            modified = true;
        }
        if (req.getPassword() != null && !req.getPassword().isBlank()) {
            // A raw password cannot be diffed against a BCrypt hash, so a supplied password
            // is always re-encoded and counts as a modification (PR-17).
            user.setSecUsrPwd(passwordEncoder.encode(req.getPassword()));
            modified = true;
        }
        if (req.getUserType() != null) {
            String normalizedType = req.getUserType().toUpperCase();
            if (!normalizedType.equals(user.getUserType())) {
                user.setUserType(normalizedType);
                modified = true;
            }
        }

        if (!modified) {
            // COUSR02C "Please modify to update ..." (no USR-MODIFIED-YES set).
            throw new IllegalStateException("Please modify to update ...");
        }

        User saved = userRepository.save(user);
        log.info("User {} has been updated ...", saved.getUserId());
        return userMapper.toDto(saved);
    }

    /**
     * Deletes a user, porting {@code COUSR03C} (TRANID {@code 'CU03'}).
     *
     * <p>Mirrors the COBOL read-then-delete flow: the record is first loaded to confirm it exists
     * (the COBOL {@code DFHRESP(NOTFND)} branch becomes {@link AccountNotFoundException}, HTTP
     * 404) and then deleted. The original program required a PF5 confirmation keystroke; in REST
     * the {@code DELETE} request itself is the confirmation, so no extra confirmation step is
     * modeled here.</p>
     *
     * @param userId the id of the user to delete (case-insensitive; normalized to uppercase)
     * @throws AccountNotFoundException if no user exists with the given id
     */
    @Transactional
    public void deleteUser(String userId) {
        log.info("Deleting user {}", userId);

        String upperId = userId.toUpperCase();
        User user = userRepository.findById(upperId)
                .orElseThrow(() -> new AccountNotFoundException(userId)); // -> 404 (see getUser note)

        userRepository.delete(user);
        log.info("User {} has been deleted ...", upperId);
    }
}
