package com.carddemo.mapper;

import java.time.LocalDate;

import org.springframework.data.domain.Page;
import org.springframework.stereotype.Component;

import com.carddemo.dto.PageResponse;
import com.carddemo.dto.TransactionAddRequest;
import com.carddemo.dto.TransactionListItem;
import com.carddemo.dto.TransactionResponse;
import com.carddemo.entity.Transaction;

/**
 * Stateless, hand-written boundary mapper that converts between the
 * {@link Transaction} JPA entity and the transaction REST DTOs.
 *
 * <h2>Role in the layered architecture</h2>
 * <p>This {@code @Component} sits on the DTO/mapper boundary of the CardDemo
 * monolith (Controller &rarr; Service &rarr; Repository &rarr; Entity). It decouples the
 * persisted {@link Transaction} entity from the API contracts so that controllers
 * and services never serialize entities directly. It is the Spring/REST
 * re-expression of the mapping logic that the legacy CICS online programs
 * {@code COTRN00C} (list), {@code COTRN01C} (view), and {@code COTRN02C} (add)
 * performed implicitly when moving fields between the VSAM {@code TRAN-RECORD}
 * ({@code CVTRA05Y}, RECLN&nbsp;350) and their BMS 3270 maps.</p>
 *
 * <h2>Statelessness and thread safety</h2>
 * <p>The mapper holds <strong>no fields and no constructor dependencies</strong>;
 * every method is a pure function of its arguments. It is therefore inherently
 * thread-safe and may be injected as a singleton wherever an entity&harr;DTO
 * translation is required. Mapping is intentionally plain, hand-written Java &mdash;
 * <em>no</em> MapStruct, ModelMapper, or Lombok is used &mdash; so the field-by-field
 * correspondence to the COBOL record stays explicit and auditable.</p>
 *
 * <h2>Both timestamps are preserved (parity-critical)</h2>
 * <p>The legacy {@code TRAN-RECORD} carries two distinct 26-character timestamps:
 * {@code TRAN-ORIG-TS} (origination) and {@code TRAN-PROC-TS} (processing)
 * &mdash; see {@code app/cpy/CVTRA05Y.cpy} lines&nbsp;16-17. Per the migration's
 * discrepancy resolution (AAP &sect;0.7.3 row&nbsp;10, which governs over the
 * prompt's single-timestamp simplification), {@link #toResponse(Transaction)}
 * surfaces <strong>both</strong> as {@code origTs} and {@code procTs}.</p>
 *
 * <h2>Server-owned fields are NOT populated by this mapper</h2>
 * <p>{@link #toEntity(TransactionAddRequest)} is deliberately a <em>partial</em>
 * builder. It copies only the client-supplied business attributes and leaves the
 * following to {@code TransactionService}, which is authoritative for them:</p>
 * <ul>
 *   <li>{@code tranId} &mdash; generated by {@code util.TranIdGenerator} (PostgreSQL
 *       sequence value left-padded to 16 characters), replacing the
 *       {@code STARTBR}/{@code READPREV} scheme of {@code COTRN02C} (AAP &sect;0.6.5).</li>
 *   <li>{@code origTs} / {@code procTs} &mdash; the origination and processing
 *       timestamps are stamped by the service at add/post time.</li>
 *   <li>{@code acctId} / {@code cardNum} &mdash; the account/card linkage is resolved
 *       by the service via the card&rarr;xref&rarr;account cross-reference (the request
 *       supplies exactly one of {@code accountId} / {@code cardNum}, reconciled in
 *       the service's {@code VALIDATE-INPUT-KEY-FIELDS} parity logic).</li>
 * </ul>
 *
 * @see Transaction
 * @see TransactionResponse
 * @see TransactionListItem
 * @see TransactionAddRequest
 * @see PageResponse
 */
@Component
public class TransactionMapper {

    /**
     * Maps a {@link Transaction} entity onto the full {@link TransactionResponse}
     * detail DTO returned by {@code GET /transactions/{tranId}} ({@code COTRN01C}
     * parity).
     *
     * <p>All thirteen record components are populated positionally in the DTO's
     * canonical-constructor order. Crucially, <strong>both</strong> the origination
     * ({@code origTs}) and processing ({@code procTs}) timestamps are mapped; the
     * latter may legitimately be {@code null} for a transaction that has been
     * originated online but not yet posted by the daily transaction-posting batch.</p>
     *
     * <p><strong>Null policy.</strong> Returns {@code null} when {@code t} is
     * {@code null}, so callers can chain {@code mapper.toResponse(repo.findById(...))}
     * without a separate presence check.</p>
     *
     * @param t the source transaction entity; may be {@code null}
     * @return an immutable {@link TransactionResponse}, or {@code null} if {@code t} is {@code null}
     */
    public TransactionResponse toResponse(Transaction t) {
        if (t == null) {
            return null;
        }
        return new TransactionResponse(
                t.getTranId(),        // tranId       <- TRAN-ID            PIC X(16)
                t.getTypeCd(),        // typeCd       <- TRAN-TYPE-CD       PIC X(02)
                t.getCatCd(),         // categoryCd   <- TRAN-CAT-CD        PIC 9(04)
                t.getSource(),        // source       <- TRAN-SOURCE        PIC X(10)
                t.getDescription(),   // description  <- TRAN-DESC          PIC X(100)
                t.getAmt(),           // amount       <- TRAN-AMT           PIC S9(09)V99
                t.getMerchantId(),    // merchantId   <- TRAN-MERCHANT-ID   PIC 9(09)
                t.getMerchantName(),  // merchantName <- TRAN-MERCHANT-NAME PIC X(50)
                t.getMerchantCity(),  // merchantCity <- TRAN-MERCHANT-CITY PIC X(50)
                t.getMerchantZip(),   // merchantZip  <- TRAN-MERCHANT-ZIP  PIC X(10)
                t.getCardNum(),       // cardNum      <- TRAN-CARD-NUM      PIC X(16)
                t.getOrigTs(),        // origTs       <- TRAN-ORIG-TS       PIC X(26)
                t.getProcTs());       // procTs       <- TRAN-PROC-TS       PIC X(26) (both timestamps)
    }

    /**
     * Maps a {@link Transaction} entity onto the compact {@link TransactionListItem}
     * row projection used by the paginated browse {@code GET /transactions}
     * ({@code COTRN00C} parity).
     *
     * <p>Only the four columns the legacy 3270 list screen rendered are exposed:
     * the transaction id, the date portion of the origination timestamp, the
     * description, and the amount.</p>
     *
     * <p><strong>Null-safe date derivation.</strong> The {@code origDate} column is
     * the date portion of {@code TRAN-ORIG-TS}. {@code toLocalDate()} is invoked only
     * after an explicit null check on {@code origTs}, so a transaction whose
     * origination timestamp is absent yields a {@code null} {@code origDate} rather
     * than a {@link NullPointerException}.</p>
     *
     * <p><strong>Null policy.</strong> Returns {@code null} when {@code t} is
     * {@code null}.</p>
     *
     * @param t the source transaction entity; may be {@code null}
     * @return an immutable {@link TransactionListItem}, or {@code null} if {@code t} is {@code null}
     */
    public TransactionListItem toListItem(Transaction t) {
        if (t == null) {
            return null;
        }
        // Guard against a null origination timestamp before calling toLocalDate().
        LocalDate origDate = (t.getOrigTs() != null) ? t.getOrigTs().toLocalDate() : null;
        return new TransactionListItem(
                t.getTranId(),        // tranId      <- TRAN-ID      PIC X(16)
                origDate,             // origDate    <- date part of TRAN-ORIG-TS
                t.getDescription(),   // description <- TRAN-DESC     PIC X(100)
                t.getAmt());          // amount      <- TRAN-AMT      PIC S9(09)V99
    }

    /**
     * Converts a Spring Data {@link Page} of {@link Transaction} entities into a
     * {@link PageResponse} of {@link TransactionListItem} rows, preserving every
     * pagination attribute (page index, size, totals, first/last flags).
     *
     * <p>The element conversion is delegated to {@link #toListItem(Transaction)} via
     * the {@link PageResponse#from(Page, java.util.function.Function)} mapping
     * factory, which routes both single-type and mapping conversions through one
     * code path. The page <em>size</em> is whatever the source {@link Page} reports
     * (the legacy fixed browse size of {@code 7} is supplied by the repository
     * {@code Pageable} at the call site &mdash; it is never hard-coded here), keeping
     * this mapper a fully general-purpose pagination translator.</p>
     *
     * @param page the source page of transaction entities; must not be {@code null}
     * @return an immutable {@link PageResponse} whose content is the mapped list rows
     *         and whose metadata mirrors the source page
     * @throws NullPointerException if {@code page} is {@code null} (per the
     *         {@link PageResponse#from(Page, java.util.function.Function)} contract)
     */
    public PageResponse<TransactionListItem> toPageResponse(Page<Transaction> page) {
        return PageResponse.from(page, this::toListItem);
    }

    /**
     * Builds a <strong>partial</strong> {@link Transaction} entity from a
     * {@link TransactionAddRequest} for the online add path ({@code COTRN02C}
     * parity), copying only the client-supplied business attributes.
     *
     * <p>By design this method does <strong>not</strong> populate any
     * server-owned or linkage field; those remain the responsibility of
     * {@code TransactionService}:</p>
     * <ul>
     *   <li><b>{@code tranId}</b> &mdash; generated by {@code TranIdGenerator}
     *       (sequence + LPAD-16), AAP &sect;0.6.5.</li>
     *   <li><b>{@code origTs} / {@code procTs}</b> &mdash; stamped by the service;
     *       the request carries {@code origDate}/{@code procDate} which the service
     *       validates ({@code DateValidationService}) and combines into timestamps.</li>
     *   <li><b>{@code acctId} / {@code cardNum}</b> &mdash; resolved by the service
     *       through the card cross-reference (the request supplies exactly one of
     *       {@code accountId} / {@code cardNum}).</li>
     * </ul>
     *
     * <p><strong>Null policy.</strong> Returns {@code null} when {@code req} is
     * {@code null}.</p>
     *
     * @param req the client add request; may be {@code null}
     * @return a new, partially-populated {@link Transaction} carrying only client
     *         business attributes, or {@code null} if {@code req} is {@code null}
     */
    public Transaction toEntity(TransactionAddRequest req) {
        if (req == null) {
            return null;
        }
        Transaction t = new Transaction();
        // --- Client-supplied business attributes (safe to map here) ---
        t.setTypeCd(req.typeCd());            // TRAN-TYPE-CD       PIC X(02)
        t.setCatCd(req.categoryCd());         // TRAN-CAT-CD        PIC 9(04)
        t.setSource(req.source());            // TRAN-SOURCE        PIC X(10)
        t.setDescription(req.description());  // TRAN-DESC          PIC X(100)
        t.setAmt(req.amount());               // TRAN-AMT           PIC S9(09)V99
        t.setMerchantId(req.merchantId());    // TRAN-MERCHANT-ID   PIC 9(09)
        t.setMerchantName(req.merchantName());// TRAN-MERCHANT-NAME PIC X(50)
        t.setMerchantCity(req.merchantCity());// TRAN-MERCHANT-CITY PIC X(50)
        t.setMerchantZip(req.merchantZip());  // TRAN-MERCHANT-ZIP  PIC X(10)

        // --- Intentionally NOT set here (owned by TransactionService) ---
        // tranId  : generated by TranIdGenerator (sequence + LPAD-16) -- AAP §0.6.5
        // origTs  : stamped by the service from validated req.origDate()
        // procTs  : stamped by the service at post time
        // acctId  : resolved by the service via card->xref->account lookup
        // cardNum : resolved/normalized by the service (request supplies acctId XOR cardNum)
        return t;
    }
}
