package com.carddemo.mapper;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

import com.carddemo.dto.transaction.TransactionDto;
import com.carddemo.dto.transaction.TransactionListResponse;
import com.carddemo.dto.transaction.TransactionRequest;
import com.carddemo.entity.Transaction;
import com.carddemo.util.BigDecimalUtil;

import org.springframework.data.domain.Page;
import org.springframework.stereotype.Component;

/**
 * Hand-coded mapper between the {@link Transaction} JPA entity and the transaction
 * REST DTOs ({@link TransactionDto}, {@link TransactionRequest}, and the paginated
 * {@link TransactionListResponse}). Consumed by {@code TransactionController}
 * (the {@code GET /api/transactions}, {@code GET /api/transactions/{tranId}}, and
 * {@code POST /api/transactions} endpoints), by {@code TransactionService}, and by
 * the batch jobs that emit interest transactions ({@code CBACT04C}) or list/report
 * transactions ({@code COTRN00C}).
 *
 * <p>This class is a Spring {@code @Component} so it can be constructor-injected
 * into its consumers (PR-29: constructor injection only, no field injection). It
 * carries no injectable dependencies — the default constructor is sufficient — and
 * therefore needs no Lombok {@code @RequiredArgsConstructor}. The class is
 * intentionally NOT {@code final} so Spring may create a CGLIB proxy if required.</p>
 *
 * <p><strong>Field-name translation (CRITICAL).</strong> The entity field
 * {@code cardNum} (closer to the COBOL {@code TRAN-CARD-NUM}) is exposed to clients
 * as the idiomatic English {@code cardNumber} on both {@link TransactionDto} and
 * {@link TransactionRequest}. This mapper performs that rename in both directions:
 * {@code transaction.getCardNum()} &rarr; {@code dto.cardNumber} (outbound) and
 * {@code request.getCardNumber()} &rarr; {@code transaction.setCardNum(...)}
 * (inbound).</p>
 *
 * <p><strong>Money normalization (PR-16 — CRITICAL).</strong> The monetary
 * {@link java.math.BigDecimal} {@code amount} is normalized to scale 2 with
 * {@link java.math.RoundingMode#HALF_UP} via
 * {@link BigDecimalUtil#ensureScaleTwo(java.math.BigDecimal)} on EVERY mapping
 * direction. {@code ensureScaleTwo} is null-safe: a {@code null} amount becomes
 * {@code 0.00} (scale 2). This guards against scale drift introduced by JSON
 * deserialization of inbound REST payloads (which may produce scale 0 or scale
 * &gt; 2), independent of the entity's {@code @Column(precision = 15, scale = 2)}
 * guarantee. {@code float}/{@code double} are forbidden for any monetary value.</p>
 *
 * <p><strong>DB2 timestamp conversion (PR-11 — CRITICAL).</strong> The two
 * timestamp fields differ in type across the boundary: the {@link Transaction}
 * entity persists {@code origTimestamp} and {@code procTimestamp} as
 * {@link LocalDateTime} (SQL {@code TIMESTAMP} columns, AAP &sect;0.6.5), whereas the
 * DTOs carry them as {@link String} in the 26-character DB2 external form
 * {@code yyyy-MM-dd-HH.mm.ss.SS'0000'}. This mapper therefore <em>converts</em>
 * between the two representations (it does NOT pass the value through): outbound,
 * each {@link LocalDateTime} is rendered with {@link #DB2_TS_FORMATTER} via
 * {@link #formatDb2(LocalDateTime)}; inbound, the DTO string is parsed with that
 * same formatter via {@link #parseDb2(String)}. Both helpers are {@code null}-safe.
 * The {@link #DB2_TS_FORMATTER} pattern is identical to the canonical
 * {@code com.carddemo.util.DateConversionUtil.DB2_TIMESTAMP_FORMATTER}, so the
 * produced and consumed strings are byte-for-byte consistent with the rest of the
 * application and with the parity tests, and they match the 26-character
 * {@code @Size}/{@code @Pattern} contract declared on the DTO fields.</p>
 *
 * <p><strong>Server-controlled fields.</strong> {@link #toEntity(TransactionRequest)}
 * deliberately does NOT set the 16-character {@code tranId} (server-generated by
 * {@code TransactionIdGenerator} per PR-10), the {@code procTimestamp}
 * (server-stamped at persistence time), the {@code @Version} field (PR-22, managed
 * by JPA optimistic locking), or the Spring Data audit fields (populated by the
 * {@code AuditingEntityListener}). The {@code accountId} field present on
 * {@link TransactionRequest} is NOT a {@link Transaction} field — the service uses
 * it to resolve the card number via the cross-reference — and is intentionally
 * ignored here.</p>
 *
 * <p><strong>Exposed surface (PR-13, PR-22).</strong> Exactly the 13 user fields of
 * the 350-byte {@code TRAN-RECORD} are mapped; the trailing COBOL
 * {@code FILLER PIC X(20)} carries no business meaning and is NOT exposed, and the
 * entity {@code @Version} field is NOT exposed in the DTO (PR-22).</p>
 *
 * <p><strong>Pagination.</strong> {@link #toListResponse(Page)} builds the immutable
 * Java 17 {@code record} {@link TransactionListResponse} from a Spring Data
 * {@link Page}, replacing the original VSAM browse cursor
 * ({@code STARTBR}/{@code READNEXT}/{@code READPREV}/{@code ENDBR}) with stateless
 * pagination metadata (AAP &sect;0.6.1).</p>
 *
 * <p>Reference COBOL source: {@code app/cpy/CVTRA05Y.cpy} (350-byte
 * {@code TRAN-RECORD}).</p>
 *
 * @see com.carddemo.entity.Transaction
 * @see com.carddemo.dto.transaction.TransactionDto
 * @see com.carddemo.dto.transaction.TransactionRequest
 * @see com.carddemo.dto.transaction.TransactionListResponse
 */
@Component
public class TransactionMapper {

    /**
     * DB2 external timestamp format: {@code yyyy-MM-dd-HH.mm.ss.SS'0000'} (PR-11).
     *
     * <p>Preserves the COBOL {@code CBACT04C} {@code DB2-FORMAT-TS} layout
     * [app/cbl/CBACT04C.cbl], whose sub-second component is the 2-digit centisecond
     * field {@code DB2-MIL PIC 9(02)} followed by the literal {@code 0000}. The
     * pattern therefore uses {@code SS} (two fractional digits), producing a total
     * of exactly 26 characters (e.g. {@code 2022-07-18-19.27.53.120000}) — matching
     * the {@code @Size(min = 26, max = 26)} and {@code @Pattern} constraints on the
     * DTO timestamp fields and the parity-test expectations.</p>
     *
     * <p>The trailing {@code '0000'} is a quoted literal (four literal {@code '0'}
     * characters mirroring the COBOL {@code DB2-REST} field). This formatter is the
     * exact equivalent of {@code com.carddemo.util.DateConversionUtil.DB2_TIMESTAMP_FORMATTER};
     * it is declared locally so this mapper depends only on its declared inputs while
     * remaining byte-for-byte consistent with the application-wide formatter.</p>
     *
     * <p>{@link DateTimeFormatter} is immutable and thread-safe per the JSR-310
     * contract, so this static constant is safely shared across all threads.</p>
     */
    private static final DateTimeFormatter DB2_TS_FORMATTER =
        DateTimeFormatter.ofPattern("yyyy-MM-dd-HH.mm.ss.SS'0000'");

    /**
     * Renders an internal {@link LocalDateTime} as the 26-character DB2 external
     * timestamp string ({@code yyyy-MM-dd-HH.mm.ss.SS'0000'}) carried by the DTOs
     * (PR-11).
     *
     * <p>Returns {@code null} for {@code null} input so that an unstamped timestamp
     * (for example a {@code procTimestamp} that has not yet been assigned) maps to a
     * {@code null} DTO field rather than throwing.</p>
     *
     * @param value the internal timestamp (may be {@code null})
     * @return the 26-character DB2-format string, or {@code null} if {@code value} is null
     */
    private static String formatDb2(LocalDateTime value) {
        return value == null ? null : value.format(DB2_TS_FORMATTER);
    }

    /**
     * Parses a 26-character DB2 external timestamp string
     * ({@code yyyy-MM-dd-HH.mm.ss.SS'0000'}) into the internal {@link LocalDateTime}
     * persisted by the entity (PR-11).
     *
     * <p>Returns {@code null} for {@code null} or blank input: the request
     * {@code origTimestamp} field is optional, and the service defaults it when
     * absent. A non-null, non-blank value that does not match the DB2 pattern raises
     * {@link java.time.format.DateTimeParseException}; such malformed input is
     * normally rejected upstream by the DTO {@code @Pattern} validation before this
     * mapper is invoked.</p>
     *
     * @param value the DB2-format string (may be {@code null} or blank)
     * @return the parsed {@link LocalDateTime}, or {@code null} if {@code value} is null/blank
     * @throws java.time.format.DateTimeParseException if a non-null, non-blank
     *         {@code value} does not match the DB2 timestamp pattern
     */
    private static LocalDateTime parseDb2(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }
        return LocalDateTime.parse(value, DB2_TS_FORMATTER);
    }

    /**
     * Converts a {@link Transaction} entity to a {@link TransactionDto} for outbound
     * REST responses (the single-transaction view and the elements of the paginated
     * list).
     *
     * <p>Performs the field-name translation {@code Transaction.cardNum} (entity)
     * &rarr; {@code TransactionDto.cardNumber} (DTO). The {@code amount} is normalized
     * to scale 2 with {@link java.math.RoundingMode#HALF_UP} via
     * {@link BigDecimalUtil#ensureScaleTwo(java.math.BigDecimal)} (PR-16). The
     * {@code origTimestamp} and {@code procTimestamp} {@link LocalDateTime} values are
     * rendered to the 26-character DB2 string form via {@link #formatDb2(LocalDateTime)}
     * (PR-11). The {@code tranId} (16 chars, PR-10) is preserved verbatim.</p>
     *
     * <p>Exactly the 13 user fields of {@code TRAN-RECORD} are mapped; the entity
     * {@code @Version} field, the audit fields, and the 20-byte COBOL {@code FILLER}
     * are intentionally NOT exposed (PR-13, PR-22).</p>
     *
     * <p>Returns {@code null} if {@code transaction} is {@code null}.</p>
     *
     * @param transaction the {@link Transaction} entity (may be {@code null})
     * @return the corresponding {@link TransactionDto}, or {@code null} if input is null
     */
    public TransactionDto toDto(Transaction transaction) {
        if (transaction == null) {
            return null;
        }
        return TransactionDto.builder()
            .tranId(transaction.getTranId())
            .cardNumber(transaction.getCardNum())                              // cardNum -> cardNumber
            .typeCd(transaction.getTypeCd())
            .categoryCd(transaction.getCategoryCd())
            .source(transaction.getSource())
            .description(transaction.getDescription())
            .amount(BigDecimalUtil.ensureScaleTwo(transaction.getAmount()))    // PR-16: scale 2, HALF_UP
            .merchantId(transaction.getMerchantId())
            .merchantName(transaction.getMerchantName())
            .merchantCity(transaction.getMerchantCity())
            .merchantZip(transaction.getMerchantZip())
            .origTimestamp(formatDb2(transaction.getOrigTimestamp()))          // PR-11: LocalDateTime -> DB2 String
            .procTimestamp(formatDb2(transaction.getProcTimestamp()))          // PR-11: LocalDateTime -> DB2 String
            .build();
    }

    /**
     * Builds a transient {@link Transaction} entity from a {@link TransactionRequest}
     * for the {@code POST /api/transactions} create flow.
     *
     * <p>Performs the field-name translation {@code TransactionRequest.cardNumber}
     * (DTO) &rarr; {@code Transaction.cardNum} (entity). The {@code amount} is
     * normalized to scale 2 with {@link java.math.RoundingMode#HALF_UP} via
     * {@link BigDecimalUtil#ensureScaleTwo(java.math.BigDecimal)} (PR-16). The
     * optional {@code origTimestamp} request string is parsed to a
     * {@link LocalDateTime} via {@link #parseDb2(String)} when supplied (otherwise the
     * service defaults it).</p>
     *
     * <p><strong>Server-controlled fields are deliberately NOT set:</strong></p>
     * <ul>
     *   <li>{@code tranId} — generated by {@code TransactionIdGenerator} (PR-10);</li>
     *   <li>{@code procTimestamp} — stamped by the service at persistence time;</li>
     *   <li>{@code version} — managed by JPA optimistic locking (PR-22);</li>
     *   <li>audit fields — populated by the JPA {@code AuditingEntityListener}.</li>
     * </ul>
     *
     * <p>The {@code accountId} field on the request is NOT a {@link Transaction}
     * field (the service resolves the card via the cross-reference) and is ignored
     * here.</p>
     *
     * <p>Returns {@code null} if {@code request} is {@code null}.</p>
     *
     * @param request the inbound {@link TransactionRequest} (may be {@code null})
     * @return a transient {@link Transaction} (without {@code tranId}/{@code procTimestamp}/
     *         {@code version}), or {@code null} if input is null
     */
    public Transaction toEntity(TransactionRequest request) {
        if (request == null) {
            return null;
        }
        Transaction transaction = new Transaction();
        // tranId NOT set — server-generated via TransactionIdGenerator (PR-10).
        transaction.setCardNum(request.getCardNumber());                       // cardNumber -> cardNum
        transaction.setTypeCd(request.getTypeCd());
        transaction.setCategoryCd(request.getCategoryCd());
        transaction.setSource(request.getSource());
        transaction.setDescription(request.getDescription());
        transaction.setAmount(BigDecimalUtil.ensureScaleTwo(request.getAmount())); // PR-16: scale 2, HALF_UP
        transaction.setMerchantId(request.getMerchantId());
        transaction.setMerchantName(request.getMerchantName());
        transaction.setMerchantCity(request.getMerchantCity());
        transaction.setMerchantZip(request.getMerchantZip());
        transaction.setOrigTimestamp(parseDb2(request.getOrigTimestamp()));    // PR-11: DB2 String -> LocalDateTime
        // procTimestamp NOT set — server stamps at persistence time.
        // version / audit fields NOT set — managed by JPA.
        return transaction;
    }

    /**
     * Converts a list of {@link Transaction} entities to a list of
     * {@link TransactionDto} objects, preserving order.
     *
     * <p>Returns an immutable empty list (never {@code null}) when {@code transactions}
     * is {@code null} or empty; otherwise each element is mapped via
     * {@link #toDto(Transaction)} and collected into an immutable list.</p>
     *
     * @param transactions the {@link Transaction} entities (may be {@code null})
     * @return a new immutable {@link List} of {@link TransactionDto} (never {@code null})
     */
    public List<TransactionDto> toDtoList(List<Transaction> transactions) {
        if (transactions == null || transactions.isEmpty()) {
            return List.of();
        }
        return transactions.stream()
            .map(this::toDto)
            .toList();
    }

    /**
     * Converts a Spring Data {@link Page} of {@link Transaction} entities to the
     * immutable Java 17 {@code record} {@link TransactionListResponse} for the
     * {@code GET /api/transactions} paginated list endpoint.
     *
     * <p>Replaces the original VSAM browse cursor with stateless pagination metadata
     * built from the {@link Page} (AAP &sect;0.6.1). All seven record components are
     * populated, in canonical-constructor order: {@code content},
     * {@code totalElements}, {@code totalPages}, {@code currentPage}
     * ({@link Page#getNumber()}), {@code pageSize} ({@link Page#getSize()}),
     * {@code hasNext}, and {@code hasPrevious}. Each entity on the page is mapped via
     * {@link #toDto(Transaction)}.</p>
     *
     * @param page the Spring Data {@link Page} of {@link Transaction} entities (must not be {@code null})
     * @return a {@link TransactionListResponse} carrying the page content and metadata
     * @throws NullPointerException if {@code page} is {@code null} (a Spring Data
     *         {@link Page} is always non-null for a valid query)
     */
    public TransactionListResponse toListResponse(Page<Transaction> page) {
        if (page == null) {
            throw new NullPointerException("page must not be null");
        }
        List<TransactionDto> content = page.getContent().stream()
            .map(this::toDto)
            .toList();
        return new TransactionListResponse(
            content,
            page.getTotalElements(),
            page.getTotalPages(),
            page.getNumber(),
            page.getSize(),
            page.hasNext(),
            page.hasPrevious()
        );
    }
}
