/*
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 */
package com.carddemo.dto.customer;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for customer data, used as both the request payload for admin customer creation/update
 * and the response payload for {@code GET /api/customers/{custId}} (served by
 * {@code CustomerController}).
 *
 * <p><strong>Mapping reference:</strong> Mirrors the 500-byte {@code CUSTOMER-RECORD}
 * from {@code app/cpy/CVCUS01Y.cpy} (CardDemo_v1.0-15-g27d6c6f-68) which declares 18 user
 * fields plus a trailing {@code FILLER PIC X(168)}. The filler carries no business meaning
 * and is intentionally <strong>NOT</strong> exposed by this DTO. Field declaration order
 * intentionally matches the copybook so the shape is stable across the
 * {@code CustomerMapper} entity&harr;DTO boundary. Field-length constraints mirror the
 * COBOL {@code PIC} clauses per PR-13.</p>
 *
 * <p><strong>PR-20 &mdash; SSN Masking (CRITICAL):</strong> The {@link #ssn} field stores
 * a 9-digit string. On outbound responses, {@code CustomerMapper} transforms the SSN
 * into {@code ***-**-####} format (asterisks + last 4 digits visible) BEFORE the DTO
 * is serialized to JSON. The masking logic lives in the mapper, NOT in this DTO; this DTO
 * performs no transformation of its own. On inbound (admin creation flow) the DTO accepts a
 * plain 9-digit SSN for downstream storage.</p>
 *
 * <p><strong>PII fields (sensitive &mdash; never log raw values):</strong></p>
 * <ul>
 *   <li>{@link #ssn} &mdash; Social Security Number (9 digits, masked on outbound per PR-20)</li>
 *   <li>{@link #govtIssuedId} &mdash; Government-issued ID (e.g., driver license)</li>
 *   <li>{@link #dateOfBirth} &mdash; Date of birth</li>
 *   <li>{@link #phoneNum1}, {@link #phoneNum2} &mdash; Contact phone numbers</li>
 * </ul>
 *
 * <p><strong>Field name conventions:</strong> DTO field names follow the COBOL
 * field-name conventions (e.g., {@code addrStateCd}, {@code addrCountryCd},
 * {@code addrZip}, {@code dateOfBirth}, {@code priCardHolderInd},
 * {@code ficoCreditScore}). The {@code Customer} entity uses shorter Java
 * conventions ({@code stateCd}, {@code countryCd}, {@code zipCd}, {@code dob},
 * {@code primaryCardHolderInd}, {@code ficoScore}). The {@code CustomerMapper}
 * handles the field-name translation between this DTO and the entity.</p>
 *
 * <p><strong>Compliance notes (Tech Spec &sect;6.4):</strong> Tech Spec &sect;6.4 documents
 * this application as demonstration-grade with PII stored in plaintext. SSN masking
 * on outbound is the minimum required security improvement per PR-20. Full
 * encryption-at-rest and audit logging are out of scope as deliverables.</p>
 *
 * <p>This is a plain POJO leaf class with no dependency on the entity, repository, service,
 * or persistence layers: it carries no {@code com.carddemo.*} imports and no JPA annotations
 * (PR-28 mandates the {@code jakarta.*} validation namespace). Boilerplate (getters, setters,
 * {@code equals}/{@code hashCode}/{@code toString}, all-args + no-args constructors, and the
 * fluent {@code builder()}) is generated by Lombok; the no-args constructor additionally
 * supports Jackson deserialization on inbound requests.</p>
 *
 * @see app/cpy/CVCUS01Y.cpy
 * @see com.carddemo.mapper.CustomerMapper
 * @see com.carddemo.entity.Customer
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(description = "Customer DTO. SSN is masked as ***-**-#### on outbound responses by "
        + "CustomerMapper per PR-20. Inbound admin creation accepts plain 9-digit SSN for "
        + "downstream storage.")
public class CustomerDto {

    /**
     * Customer ID &mdash; the natural primary key. Maps COBOL {@code CUST-ID PIC 9(09)}
     * (app/cpy/CVCUS01Y.cpy line 5). Modeled as a {@link Long} to match the
     * {@code Customer} entity {@code custId} ({@code cust_id BIGINT}). Required for all
     * interactions.
     */
    @NotNull
    @Schema(description = "Customer ID — maps COBOL CUST-ID PIC 9(09)", example = "100000001")
    private Long custId;

    /**
     * Customer first name. Maps COBOL {@code CUST-FIRST-NAME PIC X(25)}
     * (app/cpy/CVCUS01Y.cpy line 6). Entity field: {@code firstName}.
     */
    @NotBlank
    @Size(max = 25)
    @Schema(description = "Customer first name — maps COBOL CUST-FIRST-NAME PIC X(25)", example = "John")
    private String firstName;

    /**
     * Customer middle name (optional &mdash; may be blank). Maps COBOL
     * {@code CUST-MIDDLE-NAME PIC X(25)} (app/cpy/CVCUS01Y.cpy line 7).
     * Entity field: {@code middleName}.
     */
    @Size(max = 25)
    @Schema(description = "Customer middle name — maps COBOL CUST-MIDDLE-NAME PIC X(25)", example = "Q")
    private String middleName;

    /**
     * Customer last name. Maps COBOL {@code CUST-LAST-NAME PIC X(25)}
     * (app/cpy/CVCUS01Y.cpy line 8). Entity field: {@code lastName}.
     */
    @NotBlank
    @Size(max = 25)
    @Schema(description = "Customer last name — maps COBOL CUST-LAST-NAME PIC X(25)", example = "Smith")
    private String lastName;

    /**
     * Address line 1. Maps COBOL {@code CUST-ADDR-LINE-1 PIC X(50)}
     * (app/cpy/CVCUS01Y.cpy line 9). Entity field: {@code addrLine1}.
     */
    @Size(max = 50)
    @Schema(description = "Address line 1 — maps COBOL CUST-ADDR-LINE-1 PIC X(50)", example = "123 Main Street")
    private String addrLine1;

    /**
     * Address line 2. Maps COBOL {@code CUST-ADDR-LINE-2 PIC X(50)}
     * (app/cpy/CVCUS01Y.cpy line 10). Entity field: {@code addrLine2}.
     */
    @Size(max = 50)
    @Schema(description = "Address line 2 — maps COBOL CUST-ADDR-LINE-2 PIC X(50)")
    private String addrLine2;

    /**
     * Address line 3. Maps COBOL {@code CUST-ADDR-LINE-3 PIC X(50)}
     * (app/cpy/CVCUS01Y.cpy line 11). Entity field: {@code addrLine3}.
     */
    @Size(max = 50)
    @Schema(description = "Address line 3 — maps COBOL CUST-ADDR-LINE-3 PIC X(50)")
    private String addrLine3;

    /**
     * 2-letter US state code (uppercase). Maps COBOL {@code CUST-ADDR-STATE-CD PIC X(02)}
     * (app/cpy/CVCUS01Y.cpy line 12). Entity field: {@code stateCd} &mdash; the
     * {@code CustomerMapper} translates between this DTO {@code addrStateCd} and the entity
     * {@code stateCd}. Constrained to exactly two uppercase letters.
     */
    @Size(min = 2, max = 2)
    @Pattern(regexp = "[A-Z]{2}")
    @Schema(description = "2-letter US state code (uppercase) — maps COBOL CUST-ADDR-STATE-CD PIC X(02)", example = "CA")
    private String addrStateCd;

    /**
     * 3-letter ISO country code. Maps COBOL {@code CUST-ADDR-COUNTRY-CD PIC X(03)}
     * (app/cpy/CVCUS01Y.cpy line 13). Entity field: {@code countryCd}.
     */
    @Size(max = 3)
    @Schema(description = "3-letter ISO country code — maps COBOL CUST-ADDR-COUNTRY-CD PIC X(03)", example = "USA")
    private String addrCountryCd;

    /**
     * ZIP/postal code. Maps COBOL {@code CUST-ADDR-ZIP PIC X(10)}
     * (app/cpy/CVCUS01Y.cpy line 14). Entity field: {@code zipCd}.
     */
    @Size(max = 10)
    @Schema(description = "ZIP/postal code — maps COBOL CUST-ADDR-ZIP PIC X(10)", example = "90210")
    private String addrZip;

    /**
     * Primary phone number. Maps COBOL {@code CUST-PHONE-NUM-1 PIC X(15)}
     * (app/cpy/CVCUS01Y.cpy line 15). Entity field: {@code phoneNum1}.
     * <strong>PII</strong> &mdash; treat as sensitive, never log raw values.
     */
    @Size(max = 15)
    @Schema(description = "Primary phone number — maps COBOL CUST-PHONE-NUM-1 PIC X(15)", example = "555-123-4567")
    private String phoneNum1;

    /**
     * Secondary phone number. Maps COBOL {@code CUST-PHONE-NUM-2 PIC X(15)}
     * (app/cpy/CVCUS01Y.cpy line 16). Entity field: {@code phoneNum2}.
     * <strong>PII</strong> &mdash; treat as sensitive, never log raw values.
     */
    @Size(max = 15)
    @Schema(description = "Secondary phone number — maps COBOL CUST-PHONE-NUM-2 PIC X(15)")
    private String phoneNum2;

    /**
     * Social Security Number. Maps COBOL {@code CUST-SSN PIC 9(09)}
     * (app/cpy/CVCUS01Y.cpy line 17) &mdash; stored as a 9-digit {@link String} (never numeric)
     * so leading zeros are preserved. Entity field: {@code ssn}.
     *
     * <p><strong>CRITICAL &mdash; PR-20:</strong> INBOUND a raw 9-digit string is accepted for
     * admin creation; OUTBOUND the value is MASKED as {@code ***-**-####} (last 4 digits visible)
     * by {@code CustomerMapper} BEFORE JSON serialization. The DTO itself performs no masking.</p>
     *
     * <p><strong>PII</strong> &mdash; must never appear in logs.</p>
     */
    @Size(min = 9, max = 11)
    @Pattern(regexp = "\\d{9}|\\*{3}-\\*{2}-\\d{4}")
    @Schema(description = "Social Security Number. Maps COBOL CUST-SSN PIC 9(09). " +
            "INBOUND: 9-digit raw string accepted for admin creation. " +
            "OUTBOUND: MASKED as ***-**-#### by CustomerMapper per PR-20 (last 4 digits visible). " +
            "The accepted pattern admits BOTH the inbound raw 9-digit form AND the outbound " +
            "masked 11-char form, so the same DTO can faithfully represent either direction "
            + "without ever carrying a raw SSN on an outbound response. PII — never logged.",
            example = "***-**-6789")
    private String ssn;

    /**
     * Government-issued identifier (e.g., driver license number). Maps COBOL
     * {@code CUST-GOVT-ISSUED-ID PIC X(20)} (app/cpy/CVCUS01Y.cpy line 18).
     * Entity field: {@code govtIssuedId}.
     * <strong>PII</strong> &mdash; treat as sensitive, never log raw values.
     */
    @Size(max = 20)
    @Schema(description = "Government-issued ID (e.g., driver license number). " +
            "Maps COBOL CUST-GOVT-ISSUED-ID PIC X(20). PII — treat as sensitive, never log.",
            example = "DL12345678")
    private String govtIssuedId;

    /**
     * Date of birth in {@code YYYY-MM-DD} format. Maps COBOL
     * {@code CUST-DOB-YYYY-MM-DD PIC X(10)} (app/cpy/CVCUS01Y.cpy line 19). Entity field:
     * {@code dob} (a {@code LocalDate}) &mdash; the {@code CustomerMapper} translates between
     * this DTO {@code dateOfBirth} string and the entity {@code dob}.
     * <strong>PII</strong> &mdash; DOB combined with name is a strong identifier; treat as sensitive.
     */
    @Size(min = 10, max = 10)
    @Pattern(regexp = "\\d{4}-\\d{2}-\\d{2}")
    @Schema(description = "Date of birth in YYYY-MM-DD format — maps COBOL CUST-DOB-YYYY-MM-DD PIC X(10). PII — treat as sensitive.",
            example = "1985-06-15")
    private String dateOfBirth;

    /**
     * EFT (Electronic Funds Transfer) account ID. Maps COBOL
     * {@code CUST-EFT-ACCOUNT-ID PIC X(10)} (app/cpy/CVCUS01Y.cpy line 20).
     * Entity field: {@code eftAccountId}.
     */
    @Size(max = 10)
    @Schema(description = "EFT (Electronic Funds Transfer) account ID — maps COBOL CUST-EFT-ACCOUNT-ID PIC X(10)")
    private String eftAccountId;

    /**
     * Primary card holder indicator: {@code Y} or {@code N}. Maps COBOL
     * {@code CUST-PRI-CARD-HOLDER-IND PIC X(01)} (app/cpy/CVCUS01Y.cpy line 21).
     * Entity field: {@code primaryCardHolderInd} &mdash; the {@code CustomerMapper} translates
     * between this DTO {@code priCardHolderInd} and the entity {@code primaryCardHolderInd}.
     */
    @Size(min = 1, max = 1)
    @Pattern(regexp = "[YN]")
    @Schema(description = "Primary card holder indicator: Y or N — maps COBOL CUST-PRI-CARD-HOLDER-IND PIC X(01)", example = "Y")
    private String priCardHolderInd;

    /**
     * FICO credit score (valid range 300&ndash;850). Maps COBOL
     * {@code CUST-FICO-CREDIT-SCORE PIC 9(03)} (app/cpy/CVCUS01Y.cpy line 22). Entity field:
     * {@code ficoScore} &mdash; the {@code CustomerMapper} translates between this DTO
     * {@code ficoCreditScore} and the entity {@code ficoScore}. Modeled as a boxed
     * {@link Integer} so the value may be {@code null} on inbound creation flows where a score
     * has not yet been assessed. The {@code @Min}/{@code @Max} bounds enforce the business FICO
     * range, which is more semantic than the storage-only {@code PIC 9(03)} width.
     */
    @Min(300)
    @Max(850)
    @Schema(description = "FICO credit score (range 300-850) — maps COBOL CUST-FICO-CREDIT-SCORE PIC 9(03)", example = "750")
    private Integer ficoCreditScore;
}
