package com.carddemo.card.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

/**
 * One run of {@code domain/CardTokenReconciler} that re-derived at least one stored card token.
 *
 * <p>No field of {@code app/cpy/CVACT02Y.cpy} declares a card token, so this table and the mechanism
 * behind it are additive in full. The source has no keyed identity for a card and therefore no
 * rotation of one.
 *
 * <p>The table is the audit record a security review asked for. A card token is the platform identity
 * of one card: it keys {@code statement_transaction} and {@code notification_log} in the notification
 * service, it is recorded on {@code authorization_decision} in the authorization service, and it is
 * the subject of a {@code SCOPE_CARD} authority an operator grants in configuration. Turning the key
 * or the version over moves that identity, and none of those three places holds a card number, so
 * none of them can derive its own replacement. A run that moves anything therefore records what it
 * moved.
 *
 * <p>A run that rewrote nothing writes no row. The presence of a row means a stored identity moved,
 * which is the fact an operator reads this table for. Nothing deletes a row: the mapping rows the run
 * owns are what another store is re-keyed from, and a rollback reads them in reverse.
 *
 * <p>{@code src/main/resources/db/migration/V10__card_token_version_and_rotation.sql} declares the
 * table and states the same contract in the catalogue. Design decisions:
 * {@code card-platform/docs/decision-log.md}. The operator procedure is
 * {@code card-platform/services/card-service/README.md}.
 */
@Entity
@Table(name = "card_token_rotation")
public class CardTokenRotationEntity {

    /** Characters {@code from_version} and {@code to_version} hold at most. */
    static final int VERSION_WIDTH = 3;

    /** Characters {@code actor} holds at most. */
    static final int ACTOR_WIDTH = 64;

    /**
     * Identifier of this run, generated by the caller rather than by the database.
     *
     * <p>The caller generates it so that every mapping row of the run can name it before the run
     * finishes, without reading a generated key back.
     */
    @Id
    @Column(name = "rotation_id", nullable = false, updatable = false)
    private UUID rotationId;

    /** When the run began reading rows. */
    @Column(name = "started_at", nullable = false, updatable = false)
    private Instant startedAt;

    /**
     * When the run finished rewriting rows.
     *
     * <p>Written twice. A run opens its record before it rewrites anything, with this equal to
     * {@link #startedAt}, so every mapping row it goes on to write has a record to belong to. It
     * closes the record when the last page is done. {@link #complete(Instant, int, int)} is the only
     * writer of the closing values, which is why this column and the two counts are the only mutable
     * ones on the row.
     */
    @Column(name = "finished_at", nullable = false)
    private Instant finishedAt;

    /**
     * The card-token version the rewritten rows carried.
     *
     * <p>Equal to {@link #toVersion} where the rotation turned the key over and left the version
     * alone, which is the common case.
     */
    @Column(name = "from_version", nullable = false, updatable = false, length = VERSION_WIDTH)
    private String fromVersion;

    /** The card-token version the rewritten rows now carry. */
    @Column(name = "to_version", nullable = false, updatable = false, length = VERSION_WIDTH)
    private String toVersion;

    /** Rows the run read, zero until the run closes its record. */
    @Column(name = "rows_read", nullable = false)
    private int rowsRead;

    /** Rows the run rewrote under rotation, never more than {@link #rowsRead}. */
    @Column(name = "rows_rewritten", nullable = false)
    private int rowsRewritten;

    /**
     * The identity the process ran under.
     *
     * <p>A rotation is performed by an operator setting a variable and restarting, so the useful
     * record is which process applied it rather than which human decided it. No credential and no key
     * material reaches this column.
     */
    @Column(name = "actor", nullable = false, updatable = false, length = ACTOR_WIDTH)
    private String actor;

    /**
     * No-argument constructor for the persistence provider.
     *
     * <p>Hibernate calls this to materialise a row and then populates the fields directly.
     * Application code calls
     * {@link #CardTokenRotationEntity(UUID, Instant, Instant, String, String, int, int, String)}.
     */
    protected CardTokenRotationEntity() {
    }

    /**
     * Builds one audit row.
     *
     * @param rotationId    identifier of the run, which every mapping row of the run names
     * @param startedAt     when the run began reading
     * @param finishedAt    when the run finished rewriting, not before {@code startedAt}
     * @param fromVersion   the version the rewritten rows carried
     * @param toVersion     the version the rewritten rows now carry
     * @param rowsRead      rows the run read, zero or more
     * @param rowsRewritten rows the run rewrote, zero or more and no more than {@code rowsRead}
     * @param actor         the identity the process ran under
     * @throws NullPointerException     if any reference argument is {@code null}
     * @throws IllegalArgumentException if a count is negative, if more rows were rewritten than
     *                                  read, or if the run finished before it started
     */
    public CardTokenRotationEntity(UUID rotationId, Instant startedAt, Instant finishedAt,
            String fromVersion, String toVersion, int rowsRead, int rowsRewritten, String actor) {
        this.rotationId = Objects.requireNonNull(rotationId, "rotationId must not be null");
        this.startedAt = Objects.requireNonNull(startedAt, "startedAt must not be null");
        this.finishedAt = Objects.requireNonNull(finishedAt, "finishedAt must not be null");
        this.fromVersion = Objects.requireNonNull(fromVersion, "fromVersion must not be null");
        this.toVersion = Objects.requireNonNull(toVersion, "toVersion must not be null");
        this.actor = Objects.requireNonNull(actor, "actor must not be null");

        if (rowsRead < 0 || rowsRewritten < 0) {
            throw new IllegalArgumentException("a rotation counts no negative rows, and this run"
                    + " reports " + rowsRead + " read and " + rowsRewritten + " rewritten");
        }
        if (rowsRewritten > rowsRead) {
            throw new IllegalArgumentException("a rotation cannot rewrite more rows than it read,"
                    + " and this run reports " + rowsRewritten + " rewritten of " + rowsRead
                    + " read");
        }
        if (finishedAt.isBefore(startedAt)) {
            throw new IllegalArgumentException(
                    "a rotation cannot finish before it started, and this run reports both");
        }
        this.rowsRead = rowsRead;
        this.rowsRewritten = rowsRewritten;
    }

    /**
     * Closes the record with the figures the finished run measured.
     *
     * <p>A run opens its record before its first rewrite so that every mapping row it writes has a
     * record to reference, and the counts are not known until the last page is read. This method is
     * therefore the closing write, and it applies the same three checks the constructor applies so a
     * closing value cannot break what an opening value satisfied.
     *
     * @param at             when the run finished, not before it started
     * @param readRows       rows the run read, zero or more
     * @param rewrittenRows  rows the run rewrote, no more than {@code readRows}
     * @throws NullPointerException     if {@code at} is {@code null}
     * @throws IllegalArgumentException if a count is negative, if more rows were rewritten than read,
     *                                  or if the run finished before it started
     */
    public void complete(Instant at, int readRows, int rewrittenRows) {
        Objects.requireNonNull(at, "at must not be null");
        if (readRows < 0 || rewrittenRows < 0) {
            throw new IllegalArgumentException("a rotation counts no negative rows, and this run"
                    + " reports " + readRows + " read and " + rewrittenRows + " rewritten");
        }
        if (rewrittenRows > readRows) {
            throw new IllegalArgumentException("a rotation cannot rewrite more rows than it read,"
                    + " and this run reports " + rewrittenRows + " rewritten of " + readRows
                    + " read");
        }
        if (at.isBefore(startedAt)) {
            throw new IllegalArgumentException(
                    "a rotation cannot finish before it started, and this run reports both");
        }
        this.finishedAt = at;
        this.rowsRead = readRows;
        this.rowsRewritten = rewrittenRows;
    }

    /**
     * @return the identifier of this run
     */
    public UUID getRotationId() {
        return rotationId;
    }

    /**
     * @return when the run began reading rows
     */
    public Instant getStartedAt() {
        return startedAt;
    }

    /**
     * @return when the run finished rewriting rows
     */
    public Instant getFinishedAt() {
        return finishedAt;
    }

    /**
     * @return the card-token version the rewritten rows carried
     */
    public String getFromVersion() {
        return fromVersion;
    }

    /**
     * @return the card-token version the rewritten rows now carry
     */
    public String getToVersion() {
        return toVersion;
    }

    /**
     * @return rows the run read
     */
    public int getRowsRead() {
        return rowsRead;
    }

    /**
     * @return rows the run rewrote
     */
    public int getRowsRewritten() {
        return rowsRewritten;
    }

    /**
     * @return the identity the process ran under
     */
    public String getActor() {
        return actor;
    }

    /**
     * Compares on {@code rotation_id} alone, the primary key.
     *
     * @param other the object to compare with
     * @return {@code true} when {@code other} is a rotation row carrying the same identifier
     */
    @Override
    public boolean equals(Object other) {
        if (this == other) {
            return true;
        }
        if (other == null || getClass() != other.getClass()) {
            return false;
        }
        return Objects.equals(rotationId, ((CardTokenRotationEntity) other).rotationId);
    }

    /**
     * @return the hash of {@code rotation_id}
     */
    @Override
    public int hashCode() {
        return Objects.hash(rotationId);
    }

    /**
     * Renders the run without a token, a card number or key material.
     *
     * @return the identifier, the window, the two versions and the two counts
     */
    @Override
    public String toString() {
        return "CardTokenRotationEntity[rotationId=" + rotationId
                + ", startedAt=" + startedAt
                + ", finishedAt=" + finishedAt
                + ", fromVersion=" + fromVersion
                + ", toVersion=" + toVersion
                + ", rowsRead=" + rowsRead
                + ", rowsRewritten=" + rowsRewritten + "]";
    }
}
