/**
 * Card Type Definitions
 * 
 * TypeScript interfaces and enums for card data structures.
 * Converted from COBOL CARD-RECORD copybook (CVACT02Y.cpy).
 * 
 * PCI DSS Compliance:
 * - Card numbers are always masked (only last 4 digits visible)
 * - CVV codes are never transmitted or stored in frontend
 * - Full card numbers only available during initial card creation
 * 
 * Conversion Notes:
 * - COBOL PIC X(16) → TypeScript string (masked format ****XXXX)
 * - COBOL PIC 9(11) → TypeScript number
 * - COBOL PIC X(50) → TypeScript string
 * - COBOL PIC X(10) dates → TypeScript string (ISO 8601 format YYYY-MM-DD)
 * - COBOL PIC X(01) → TypeScript string (status code)
 * - COBOL PIC 9(03) CVV → EXCLUDED per PCI DSS requirements
 */

/**
 * Card data structure matching backend CardDto.java
 * Converted from COBOL CARD-RECORD (CVACT02Y.cpy)
 * 
 * This interface represents a credit card with PCI-compliant field masking.
 * The card number is always masked to show only the last 4 digits for security.
 * 
 * Used by:
 * - CardListPage (display masked cards in table)
 * - CardUpdatePage (show card details with masked number)
 * - CardForm (form validation and data binding)
 * - CardTable (table data structure)
 * - cardService (API client type definitions)
 */
export interface Card {
  /**
   * Masked card number showing only last 4 digits
   * Format: ****1234 (12 asterisks + 4 digits)
   * 
   * From COBOL: CARD-NUM PIC X(16)
   * Security: Always masked per PCI DSS requirement
   * Full card number is never transmitted to frontend
   */
  cardNum: string;

  /**
   * Associated account identifier
   * Links this card to an account record
   * 
   * From COBOL: CARD-ACCT-ID PIC 9(11)
   * References: Account.acctId in account table
   */
  cardAcctId: number;

  /**
   * Cardholder name as embossed on physical card
   * Maximum 50 characters, typically FIRSTNAME LASTNAME format
   * 
   * From COBOL: CARD-EMBOSSED-NAME PIC X(50)
   * Example: "JOHN DOE"
   */
  cardEmbossedName: string;

  /**
   * Card expiration date in ISO 8601 format
   * Format: YYYY-MM-DD
   * 
   * From COBOL: CARD-EXPIRAION-DATE PIC X(10)
   * Note: COBOL field name has typo "EXPIRAION" (preserved in comments)
   * Example: "2025-12-31"
   */
  cardExpirationDate: string;

  /**
   * Current card status code
   * Single character indicating card's operational status
   * 
   * From COBOL: CARD-ACTIVE-STATUS PIC X(01)
   * Values: See CardStatus enum
   * - 'Y' = Active (card can be used for transactions)
   * - 'N' = Inactive (card cannot be used)
   * - 'B' = Blocked (card blocked due to suspicious activity)
   * - 'E' = Expired (card has expired)
   */
  cardStatus: string;

  /**
   * Card activation date in ISO 8601 format
   * Null if card has never been activated
   * 
   * Format: YYYY-MM-DD
   * Example: "2023-01-15" or null
   */
  cardActiveDate: string | null;

  /**
   * Record creation timestamp
   * ISO 8601 format with timezone
   * 
   * Generated by backend on initial card creation
   * Example: "2023-01-15T10:30:00Z"
   */
  createdAt: string;

  /**
   * Record last update timestamp
   * ISO 8601 format with timezone
   * 
   * Updated by backend on any card modification
   * Example: "2023-06-20T14:45:30Z"
   */
  updatedAt: string;

  // Note: CARD-CVV-CD PIC 9(03) is intentionally excluded
  // CVV codes must never be stored or transmitted per PCI DSS 3.2 requirement
}

/**
 * Card status enumeration
 * 
 * Maps COBOL single-character status codes to descriptive enum values.
 * These values correspond to CARD-ACTIVE-STATUS field in COBOL CARD-RECORD.
 * 
 * From COBOL: CARD-ACTIVE-STATUS PIC X(01)
 * 
 * Usage:
 * ```typescript
 * const card: Card = {
 *   cardStatus: CardStatus.ACTIVE,
 *   // ... other fields
 * };
 * 
 * if (card.cardStatus === CardStatus.EXPIRED) {
 *   // Handle expired card
 * }
 * ```
 */
export enum CardStatus {
  /**
   * Card is active and can be used for transactions
   * Value: 'Y'
   * 
   * Active cards can:
   * - Process purchases and payments
   * - Be used for balance inquiries
   * - Perform cash advances
   */
  ACTIVE = 'Y',

  /**
   * Card is inactive and cannot be used for transactions
   * Value: 'N'
   * 
   * Inactive cards:
   * - Cannot process any transactions
   * - May be pending activation
   * - May be temporarily disabled by cardholder
   */
  INACTIVE = 'N',

  /**
   * Card is blocked due to suspicious activity or user request
   * Value: 'B'
   * 
   * Blocked cards:
   * - Cannot be used until unblocked
   * - May require fraud verification
   * - Typically blocked by fraud detection system or cardholder
   */
  BLOCKED = 'B',

  /**
   * Card has expired and needs replacement
   * Value: 'E'
   * 
   * Expired cards:
   * - Cannot be used for any transactions
   * - Require new card issuance
   * - Expiration date has passed
   */
  EXPIRED = 'E'
}
