package com.carddemo.exception;

import java.time.LocalDateTime;
import java.util.List;

import lombok.Builder;

/**
 * Standardized error response payload for REST 4xx/5xx responses.
 *
 * <p>This type is <strong>not</strong> an exception. It is the JSON <em>body</em>
 * returned to REST clients when a request fails. It is constructed and returned by
 * the {@code GlobalExceptionHandler} {@code @ControllerAdvice} in
 * {@code com.carddemo.controller.advice}, which catches every application and
 * framework exception and maps it onto this uniform contract so that the entire
 * REST surface (the nine controllers described in AAP &sect;0.4.1.1) reports errors
 * with one consistent shape, regardless of the underlying exception type.</p>
 *
 * <h2>JSON shape</h2>
 * <pre>
 * {
 *   "status": 400,
 *   "code": "100",
 *   "message": "INVALID CARD NUMBER FOUND",
 *   "path": "/api/transactions",
 *   "timestamp": "2024-06-15T14:32:11.123",
 *   "fieldErrors": [
 *     {"field": "amount", "message": "must be positive"}
 *   ]
 * }
 * </pre>
 *
 * <p>{@code fieldErrors} is {@code null} for the vast majority of exceptions and is
 * populated only for Spring {@code MethodArgumentNotValidException} (and the related
 * bind/validation exceptions), where the handler flattens the framework
 * {@code BindingResult} field errors into a {@link FieldError} list. With the
 * application's default Jackson {@code non_null} property inclusion, a {@code null}
 * {@code fieldErrors} is omitted from the serialized JSON entirely; no Jackson
 * annotations are required on this record to achieve that behavior.</p>
 *
 * <h2>The {@code code} field is a {@code String}</h2>
 * <p>{@code code} is intentionally a {@link String}, not an {@code int}, so it can
 * carry <em>both</em> the numeric COBOL validation reason codes preserved from
 * {@code CBTRN02C} paragraph {@code 1500-VALIDATE-TRAN} &mdash; {@code "100"}
 * ({@code "INVALID CARD NUMBER FOUND"}), {@code "101"}
 * ({@code "ACCOUNT RECORD NOT FOUND"}), {@code "102"}
 * ({@code "OVERLIMIT TRANSACTION"}), {@code "103"}
 * ({@code "TRANSACTION RECEIVED AFTER ACCT EXPIRATION"}) &mdash; <em>and</em> symbolic
 * cross-cutting codes such as {@code "VALIDATION_FAILED"}, {@code "UNAUTHORIZED"}, or
 * {@code "CONFLICT"}. For the COBOL-derived exceptions, {@code GlobalExceptionHandler}
 * typically populates {@code code} via {@code String.valueOf(ex.getCode())}, preserving
 * the original batch reason code on the REST error payload (refactoring rule PR-03).</p>
 *
 * <h2>Immutability</h2>
 * <p>Implemented as a Java&nbsp;17 {@code record}, this payload is immutable: every
 * component is {@code final}, there are no setters, and the canonical constructor plus
 * the per-component accessors ({@link #status()}, {@link #code()}, {@link #message()},
 * {@link #path()}, {@link #timestamp()}, {@link #fieldErrors()}) are generated by the
 * compiler. The Lombok {@link Builder @Builder} annotation additionally generates a
 * fluent {@code ErrorResponse.builder()} static factory used by the handler to assemble
 * payloads readably, for example:</p>
 * <pre>
 * ErrorResponse.builder()
 *     .status(400)
 *     .code("100")
 *     .message("INVALID CARD NUMBER FOUND")
 *     .path("/api/transactions")
 *     .timestamp(LocalDateTime.now())
 *     .build();
 * </pre>
 *
 * <p>The {@code timestamp} is a {@link LocalDateTime} (matching the Tech Spec timestamp
 * conventions used across the migration) and is serialized as an ISO-8601 string by the
 * Jackson JSR-310 module that {@code spring-boot-starter-web} auto-registers.</p>
 *
 * @param status      HTTP status code of the failed response (e.g. 400, 404, 422, 500)
 * @param code        application error code; either a numeric COBOL reason code rendered
 *                    as a string ({@code "100"}, {@code "101"}, {@code "102"},
 *                    {@code "103"}) or a symbolic code ({@code "VALIDATION_FAILED"},
 *                    {@code "UNAUTHORIZED"}, &hellip;)
 * @param message     human-readable error message; for the COBOL-derived validation
 *                    failures this is the exact original message string, preserved
 *                    verbatim from the source exception (PR-03)
 * @param path        the request URI that triggered the error (e.g. {@code "/api/transactions"})
 * @param timestamp   the server {@link LocalDateTime} at which the error response was built
 * @param fieldErrors optional list of field-level validation errors; {@code null} (and
 *                    therefore omitted from JSON) for non-validation failures, populated
 *                    only for Spring validation exceptions
 * @see com.carddemo.exception.TransactionValidationException
 */
@Builder
public record ErrorResponse(
        int status,
        String code,
        String message,
        String path,
        LocalDateTime timestamp,
        List<FieldError> fieldErrors
) {

    /**
     * A single field-level validation error, describing why one input field was
     * rejected.
     *
     * <p>Instances of this nested record are produced by {@code GlobalExceptionHandler}
     * when it flattens a Spring {@code BindingResult} (from
     * {@code MethodArgumentNotValidException} or a related bind exception) into the
     * outer {@link ErrorResponse#fieldErrors()} list, giving REST clients precise,
     * per-field feedback for {@code @Valid} request-body and parameter violations.</p>
     *
     * <p>Like its enclosing type, this is an immutable Java&nbsp;17 {@code record}: its
     * two components are {@code final} and exposed through the compiler-generated
     * accessors {@link #field()} and {@link #message()}.</p>
     *
     * <p><strong>Security &mdash; the rejected value is deliberately not exposed.</strong>
     * This record intentionally carries only the offending field <em>name</em> and the
     * validation <em>message</em>; it does <em>not</em> echo the rejected input value back
     * to the client. Reflecting rejected values in a public error payload would leak
     * sensitive submitted data &mdash; for example a rejected {@code LoginRequest.password},
     * {@code UserCreateRequest.password}, or {@code CustomerDto.ssn} &mdash; into REST
     * responses, logs, and proxies. Omitting it entirely is the safe default and removes
     * any per-field redaction burden from {@code GlobalExceptionHandler}.</p>
     *
     * @param field   the offending field name; dot-notation is used for nested
     *                properties (e.g. {@code "address.zipCode"})
     * @param message the validation failure message (e.g. {@code "must be positive"})
     */
    public record FieldError(
            String field,
            String message
    ) {
    }
}
