/*
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 */
package com.carddemo.dto.user;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * User Administration Response DTO.
 *
 * <p>Returned by {@code UserController} endpoints to expose user account information
 * to ADMIN clients (all consuming endpoints are protected by
 * {@code @PreAuthorize("hasRole('ADMIN')")} per PR-18):</p>
 * <ul>
 *   <li>{@code GET  /api/admin/users}            — list users (returns {@code List<UserDto>})</li>
 *   <li>{@code GET  /api/admin/users/{userId}}   — single user retrieval</li>
 *   <li>{@code POST /api/admin/users}            — create (returns the created user)</li>
 *   <li>{@code PUT  /api/admin/users/{userId}}   — update (returns the updated user)</li>
 * </ul>
 *
 * <p><b>SECURITY (PR-17):</b> This DTO intentionally <b>NEVER</b> exposes the password
 * hash ({@code secUsrPwd}). The {@code UserMapper.toDto()} method deliberately omits
 * this field. Do not add a password field to this class. Because no sensitive field
 * exists, Lombok's generated {@code toString()} is safe to emit to logs.</p>
 *
 * <p>Maps the visible portion of {@code app/cpy/CSUSR01Y.cpy} SEC-USER-DATA record
 * (excluding {@code SEC-USR-PWD} for security and {@code SEC-USR-FILLER} 23-byte
 * filler which is not part of the public contract). The 4-field read view is
 * corroborated by the list screen {@code app/cpy-bms/COUSR00.CPY} and the delete
 * confirmation screen {@code app/cpy-bms/COUSR03.CPY}, both of which display only
 * {USRID, FNAME, LNAME, UTYPE} and no password.</p>
 *
 * <p>Field-length constraints mirror the original COBOL {@code PIC} clauses per PR-13:</p>
 * <ul>
 *   <li>{@code userId}    — {@code PIC X(08)}, 8 chars</li>
 *   <li>{@code firstName} — {@code PIC X(20)}, 20 chars</li>
 *   <li>{@code lastName}  — {@code PIC X(20)}, 20 chars</li>
 *   <li>{@code userType}  — {@code PIC X(01)}, 1 char, {@code 'A'} (ADMIN) or {@code 'U'} (USER) per PR-19</li>
 * </ul>
 *
 * <p>{@code @JsonInclude(NON_NULL)} suppresses {@code null} fields from the serialized
 * JSON response so partially-populated payloads stay compact; the validation
 * constraints document the contract for clients and are exercised when this shape is
 * also accepted on inbound flows.</p>
 *
 * <p>This is a plain POJO with no dependency on the entity, repository, or service
 * layers (DTO decoupling): it carries no {@code com.carddemo.*} imports and no JPA /
 * persistence annotations. Boilerplate (getters, setters, {@code equals}/{@code hashCode}/
 * {@code toString}, all-args + no-args constructors, and the fluent {@code builder()})
 * is generated by Lombok; the no-args constructor additionally supports Jackson
 * deserialization.</p>
 *
 * @see com.carddemo.dto.user.UserCreateRequest
 * @see com.carddemo.entity.User
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@JsonInclude(JsonInclude.Include.NON_NULL)
@Schema(description = "User account DTO (password hash never exposed per PR-17)")
public class UserDto {

    /**
     * User ID — primary key for the {@code User} entity / {@code SEC-USR-ID}.
     *
     * <p>Mirrors COBOL {@code SEC-USR-ID PIC X(08)} (app/cpy/CSUSR01Y.cpy line 18).
     * Uppercase convention (e.g., {@code "ADMIN001"}, {@code "USER0001"}) following the
     * COSGN00C {@code FUNCTION UPPER-CASE} normalization; the {@code [A-Z0-9]+} pattern
     * enforces uppercase alphanumeric at the API boundary.</p>
     */
    @NotBlank
    @Size(min = 1, max = 8)
    @Pattern(regexp = "[A-Z0-9]+", message = "userId must be uppercase alphanumeric")
    @Schema(description = "User ID (uppercase alphanumeric, max 8 chars)",
            example = "ADMIN001", maxLength = 8)
    private String userId;

    /**
     * First name. Mirrors COBOL {@code SEC-USR-FNAME PIC X(20)}
     * (app/cpy/CSUSR01Y.cpy line 19).
     */
    @Size(max = 20)
    @Schema(description = "First name (max 20 chars)", example = "John", maxLength = 20)
    private String firstName;

    /**
     * Last name. Mirrors COBOL {@code SEC-USR-LNAME PIC X(20)}
     * (app/cpy/CSUSR01Y.cpy line 20).
     */
    @Size(max = 20)
    @Schema(description = "Last name (max 20 chars)", example = "Doe", maxLength = 20)
    private String lastName;

    /**
     * User type / role discriminator. Mirrors COBOL {@code SEC-USR-TYPE PIC X(01)}
     * (app/cpy/CSUSR01Y.cpy line 22).
     *
     * <p><b>PR-19:</b> only {@code 'A'} (&rarr; {@code ROLE_ADMIN}) or {@code 'U'}
     * (&rarr; {@code ROLE_USER}) are valid; the mapping to a Spring Security
     * {@code GrantedAuthority} is performed by {@code CustomAuthorityMapper} /
     * {@code UserDetailsServiceImpl}.</p>
     */
    @NotBlank
    @Size(min = 1, max = 1)
    @Pattern(regexp = "[AU]", message = "userType must be 'A' (ADMIN) or 'U' (USER)")
    @Schema(description = "User type: 'A' for ADMIN (ROLE_ADMIN), 'U' for USER (ROLE_USER)",
            example = "A", allowableValues = {"A", "U"}, maxLength = 1)
    private String userType;
}
