package com.cardemo.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import java.math.BigDecimal;
import java.util.Objects;

/**
 * JPA entity mapping the VSAM TCATBALF dataset — transaction category balance aggregation.
 *
 * <p>Faithfully translates the COBOL TRAN-CAT-BAL-RECORD layout defined in
 * {@code app/cpy/CVTRA01Y.cpy} (50-byte KSDS record) to a PostgreSQL relational table.
 *
 * <h3>COBOL Source Record Layout (CVTRA01Y.cpy):</h3>
 * <pre>
 * 01  TRAN-CAT-BAL-RECORD.
 *     05  TRAN-CAT-KEY.
 *        10 TRANCAT-ACCT-ID    PIC 9(11).     positions [0:11]  → accountId
 *        10 TRANCAT-TYPE-CD    PIC X(02).     positions [11:13] → typeCode
 *        10 TRANCAT-CD         PIC 9(04).     positions [13:17] → categoryCode
 *     05  TRAN-CAT-BAL         PIC S9(09)V99. positions [17:28] → balance
 *     05  FILLER               PIC X(22).     positions [28:50] (not mapped)
 * </pre>
 *
 * <p>Total record length: 11 + 2 + 4 + 11 + 22 = 50 bytes.
 *
 * <h3>Key Design Decisions:</h3>
 * <ul>
 *   <li>Uses a surrogate {@code Long} primary key ({@code id}) for JPA simplicity, with a
 *       {@link UniqueConstraint} on ({@code account_id}, {@code type_code}, {@code category_code})
 *       to preserve the composite VSAM KSDS primary key semantics (TRAN-CAT-KEY).</li>
 *   <li>The balance field uses {@link BigDecimal} with precision=11, scale=2 to exactly match
 *       the COBOL PIC S9(09)V99 specification — 9 integer digits plus 2 decimal digits.
 *       NEVER use floating-point for this field.</li>
 *   <li>{@code accountId} and {@code categoryCode} are stored as {@code String} to preserve
 *       leading zeros from the original PIC 9(n) COBOL representation.</li>
 *   <li>{@code equals()} and {@code hashCode()} are based on the natural composite key
 *       (accountId + typeCode + categoryCode), following JPA best practices for entity
 *       identity comparison across managed and detached entity states.</li>
 * </ul>
 *
 * @see <a href="app/cpy/CVTRA01Y.cpy">COBOL TRAN-CAT-BAL-RECORD copybook</a>
 * @see <a href="app/data/ASCII/tcatbal.txt">Test fixture data (50 records, 50 chars each)</a>
 */
@Entity
@Table(name = "category_balance", uniqueConstraints = {
    @UniqueConstraint(columnNames = {"account_id", "type_code", "category_code"})
})
public class CategoryBalance {

    /**
     * Surrogate primary key for JPA identity management.
     * Auto-generated by the database via IDENTITY strategy (PostgreSQL BIGSERIAL).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * Account identifier — maps to COBOL TRANCAT-ACCT-ID PIC 9(11).
     * Stored as {@code String} to preserve leading zeros (e.g., "00000000001").
     * Part of the composite natural key that mirrors the VSAM KSDS primary key.
     */
    @Column(name = "account_id", length = 11, nullable = false)
    private String accountId;

    /**
     * Transaction type code — maps to COBOL TRANCAT-TYPE-CD PIC X(02).
     * Two-character alphanumeric code identifying the transaction type (e.g., "01").
     * Part of the composite natural key that mirrors the VSAM KSDS primary key.
     */
    @Column(name = "type_code", length = 2, nullable = false)
    private String typeCode;

    /**
     * Transaction category code — maps to COBOL TRANCAT-CD PIC 9(04).
     * Stored as {@code String} to preserve leading zeros (e.g., "0001").
     * Part of the composite natural key that mirrors the VSAM KSDS primary key.
     */
    @Column(name = "category_code", length = 4, nullable = false)
    private String categoryCode;

    /**
     * Category balance amount — maps to COBOL TRAN-CAT-BAL PIC S9(09)V99.
     *
     * <p>Uses {@link BigDecimal} with precision=11 (9 integer + 2 decimal digits) and scale=2
     * to exactly replicate COBOL packed decimal semantics. The signed nature of the COBOL
     * field (S prefix) is naturally handled by {@link BigDecimal}'s sign support.
     *
     * <p><strong>CRITICAL:</strong> NEVER use {@code float} or {@code double} for this field.
     * All monetary calculations must use {@link BigDecimal} with
     * {@link java.math.RoundingMode#HALF_UP} per the AAP mandate for zero floating-point
     * rounding errors.
     */
    @Column(name = "balance", precision = 11, scale = 2, nullable = false)
    private BigDecimal balance;

    /**
     * Default no-argument constructor required by the JPA specification (JSR 338).
     * Protected access prevents direct instantiation outside of the JPA framework
     * while still allowing proxy creation by Hibernate.
     */
    protected CategoryBalance() {
        // Required by JPA specification — no initialization needed
    }

    /**
     * Constructs a new {@code CategoryBalance} with the specified natural key fields and balance.
     *
     * @param accountId    the 11-character zero-padded account identifier (TRANCAT-ACCT-ID)
     * @param typeCode     the 2-character transaction type code (TRANCAT-TYPE-CD)
     * @param categoryCode the 4-character zero-padded category code (TRANCAT-CD)
     * @param balance      the category balance amount (TRAN-CAT-BAL), must not be null
     */
    public CategoryBalance(String accountId, String typeCode, String categoryCode,
                           BigDecimal balance) {
        this.accountId = accountId;
        this.typeCode = typeCode;
        this.categoryCode = categoryCode;
        this.balance = balance;
    }

    /**
     * Returns the surrogate primary key.
     *
     * @return the auto-generated database identity, or {@code null} if not yet persisted
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the surrogate primary key.
     * Typically managed by JPA — direct use is discouraged outside of testing.
     *
     * @param id the database identity value
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the account identifier (TRANCAT-ACCT-ID).
     *
     * @return the 11-character zero-padded account ID
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * Sets the account identifier (TRANCAT-ACCT-ID).
     *
     * @param accountId the 11-character zero-padded account ID
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * Returns the transaction type code (TRANCAT-TYPE-CD).
     *
     * @return the 2-character type code
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * Sets the transaction type code (TRANCAT-TYPE-CD).
     *
     * @param typeCode the 2-character type code
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    /**
     * Returns the transaction category code (TRANCAT-CD).
     *
     * @return the 4-character zero-padded category code
     */
    public String getCategoryCode() {
        return categoryCode;
    }

    /**
     * Sets the transaction category code (TRANCAT-CD).
     *
     * @param categoryCode the 4-character zero-padded category code
     */
    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }

    /**
     * Returns the category balance amount (TRAN-CAT-BAL).
     *
     * @return the balance as {@link BigDecimal} with precision=11 and scale=2
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * Sets the category balance amount (TRAN-CAT-BAL).
     *
     * @param balance the balance as {@link BigDecimal}, must not be null
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * Determines equality based on the composite natural key
     * (accountId + typeCode + categoryCode), mirroring the VSAM KSDS composite
     * primary key TRAN-CAT-KEY = TRANCAT-ACCT-ID || TRANCAT-TYPE-CD || TRANCAT-CD.
     *
     * <p>This follows JPA best practice: entity equality is based on the business/natural
     * key rather than the surrogate database ID, ensuring consistent behavior across
     * managed and detached entity states.
     *
     * @param o the reference object with which to compare
     * @return {@code true} if this entity has the same natural key as the other entity
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CategoryBalance that = (CategoryBalance) o;
        return Objects.equals(accountId, that.accountId)
                && Objects.equals(typeCode, that.typeCode)
                && Objects.equals(categoryCode, that.categoryCode);
    }

    /**
     * Computes the hash code based on the composite natural key
     * (accountId + typeCode + categoryCode).
     * Consistent with the {@link #equals(Object)} contract.
     *
     * @return hash code derived from the natural key fields
     */
    @Override
    public int hashCode() {
        return Objects.hash(accountId, typeCode, categoryCode);
    }

    /**
     * Returns a string representation including the natural key fields and balance.
     * Useful for logging and debugging. Does not expose sensitive data.
     *
     * @return string representation of this category balance record
     */
    @Override
    public String toString() {
        return "CategoryBalance{"
                + "id=" + id
                + ", accountId='" + accountId + '\''
                + ", typeCode='" + typeCode + '\''
                + ", categoryCode='" + categoryCode + '\''
                + ", balance=" + balance
                + '}';
    }
}
