/*
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 */
package com.carddemo.dto.transaction;

import io.swagger.v3.oas.annotations.media.Schema;

import jakarta.validation.constraints.Digits;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Transaction Data Transfer Object — the FOUNDATIONAL DTO of the transaction package.
 *
 * <p>Mirrors the COBOL {@code CVTRA05Y} 350-byte {@code TRAN-RECORD}
 * (app/cpy/CVTRA05Y.cpy lines 4-18) for transaction read operations. Returned by
 * the {@code TransactionController} endpoints:</p>
 * <ul>
 *   <li>{@code GET /api/transactions/{tranId}} — single transaction view
 *       (COBOL counterpart {@code app/cbl/COTRN01C.cbl})</li>
 *   <li>{@code GET /api/transactions} — paginated list, wrapped as the
 *       {@code content} element type of {@code TransactionListResponse}</li>
 * </ul>
 *
 * <p>This shape is mapped to/from the {@code Transaction} JPA entity (sibling
 * {@code entity/} package) by {@code TransactionMapper}. Several deliberate
 * name/type translations are performed by the mapper and MUST NOT leak into
 * this DTO:</p>
 * <ul>
 *   <li><b>cardNumber</b> (this DTO, idiomatic full English) ⇄
 *       {@code Transaction.cardNum} (entity, closer to COBOL {@code TRAN-CARD-NUM})</li>
 *   <li><b>origTimestamp / procTimestamp</b> — 26-char DB2-format {@code String}
 *       here ⇄ {@code LocalDateTime} on the entity (conversion via
 *       {@code DateConversionUtil} at the I/O boundary per PR-11)</li>
 *   <li><b>categoryCd</b> — {@code Integer} here ⇄ {@code String} on the entity</li>
 * </ul>
 *
 * <p><b>Field provenance — RECORD widths, NOT BMS widths (PR-13):</b> Field lengths
 * mirror the {@code CVTRA05Y} record {@code PIC} clauses exactly, which differ from
 * the narrower BMS display widths in {@code app/cpy-bms/COTRN01.CPY}. Notably:
 * {@code description} = 100 (record) vs 60 (BMS), {@code merchantName} = 50 vs 30,
 * {@code merchantCity} = 50 vs 25. The 20-byte {@code FILLER} at the end of the
 * record is a COBOL alignment artifact with no semantic value and is intentionally
 * NOT exposed.</p>
 *
 * <p><b>CRITICAL — PR-16 (BigDecimal for money):</b> {@code amount} is
 * {@code java.math.BigDecimal}, NEVER {@code float}/{@code double}. Constrained by
 * {@code @Digits(integer = 9, fraction = 2)} to preserve the COBOL packed-decimal
 * {@code S9(09)V99} semantics exactly. The sign convention is positive = credit,
 * negative = debit (per COBOL).</p>
 *
 * <p><b>CRITICAL — PR-11 (DB2 timestamp format preserved):</b> {@code origTimestamp}
 * and {@code procTimestamp} are {@code String}s in DB2 external format
 * {@code yyyy-MM-dd-HH.mm.ss.SSS'0000'} preserved verbatim at the API boundary, NOT
 * {@code LocalDateTime}. The conversion to/from internal {@code LocalDateTime}
 * happens in {@code TransactionMapper}.</p>
 *
 * <p><b>CRITICAL — PR-28 (Jakarta EE namespace):</b> All validation annotations are
 * imported from {@code jakarta.validation.constraints.*}, NEVER
 * {@code javax.validation.*}.</p>
 *
 * <p>This is a plain POJO with no dependency on the entity, repository, or service
 * layers (DTO decoupling): it carries no {@code com.carddemo.*} imports and no JPA /
 * persistence annotations. Boilerplate (getters, setters,
 * {@code equals}/{@code hashCode}/{@code toString}, all-args + no-args constructors,
 * and the fluent {@code builder()}) is generated by Lombok; the no-args constructor
 * additionally supports Jackson (de)serialization.</p>
 *
 * @see com.carddemo.entity.Transaction
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(
    description = "Transaction DTO mirroring COBOL CVTRA05Y 350-byte TRAN-RECORD. "
        + "Used as the response payload for GET /api/transactions/{tranId} and as the "
        + "content element type for paginated GET /api/transactions list responses. "
        + "Timestamps (origTimestamp, procTimestamp) are preserved verbatim as 26-char "
        + "DB2 format strings per PR-11."
)
public class TransactionDto {

    /**
     * Transaction ID (COBOL TRAN-ID PIC X(16)).
     * Format: parmDate(10) + sequential suffix(6) per PR-10.
     * Example: "2024011500000001".
     */
    @NotNull(message = "Transaction ID is required")
    @Size(min = 16, max = 16, message = "Transaction ID must be exactly 16 characters")
    @Schema(
        description = "16-character transaction ID (format: parmDate(10) + suffix(6) per PR-10)",
        example = "2024011500000001",
        minLength = 16,
        maxLength = 16,
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String tranId;

    /**
     * Card number (COBOL TRAN-CARD-NUM PIC X(16)).
     * NOTE: Field name is `cardNumber` here but `cardNum` in Transaction entity — mapper handles translation.
     * 16-digit numeric string.
     */
    @NotNull(message = "Card number is required")
    @Size(min = 16, max = 16, message = "Card number must be exactly 16 digits")
    @Pattern(regexp = "\\d{16}", message = "Card number must contain only digits")
    @Schema(
        description = "16-digit card number (COBOL TRAN-CARD-NUM PIC X(16))",
        example = "4111111111111111",
        minLength = 16,
        maxLength = 16,
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String cardNumber;

    /**
     * Transaction type code (COBOL TRAN-TYPE-CD PIC X(02)).
     * Foreign key to transaction_types table.
     */
    @NotNull(message = "Type code is required")
    @Size(min = 2, max = 2, message = "Type code must be exactly 2 characters")
    @Schema(
        description = "2-character transaction type code (FK to transaction_types)",
        example = "01",
        minLength = 2,
        maxLength = 2,
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String typeCd;

    /**
     * Transaction category code (COBOL TRAN-CAT-CD PIC 9(04)).
     * 4-digit numeric (0-9999).
     */
    @NotNull(message = "Category code is required")
    @Min(value = 0, message = "Category code must be 0 or greater")
    @Max(value = 9999, message = "Category code must not exceed 4 digits")
    @Schema(
        description = "4-digit numeric transaction category code",
        example = "5411",
        minimum = "0",
        maximum = "9999",
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    private Integer categoryCd;

    /**
     * Transaction source (COBOL TRAN-SOURCE PIC X(10)).
     * Free-form source/channel identifier.
     */
    @Size(max = 10, message = "Source must not exceed 10 characters")
    @Schema(
        description = "Transaction source/channel (10-char max)",
        example = "POS",
        maxLength = 10,
        requiredMode = Schema.RequiredMode.NOT_REQUIRED,
        nullable = true
    )
    private String source;

    /**
     * Transaction description (COBOL TRAN-DESC PIC X(100)).
     * RECORD WIDTH: 100 chars (not BMS width 60).
     */
    @Size(max = 100, message = "Description must not exceed 100 characters")
    @Schema(
        description = "Transaction description (full record width 100 chars per CVTRA05Y PIC X(100))",
        example = "Grocery purchase at Whole Foods Market - downtown Austin location",
        maxLength = 100,
        requiredMode = Schema.RequiredMode.NOT_REQUIRED,
        nullable = true
    )
    private String description;

    /**
     * Transaction amount (COBOL TRAN-AMT PIC S9(09)V99).
     * MUST be BigDecimal per PR-16. NEVER use float or double for money.
     * 9 integer digits + 2 decimal places, signed (positive=credit, negative=debit per COBOL convention).
     */
    @NotNull(message = "Amount is required")
    @Digits(integer = 9, fraction = 2, message = "Amount must have at most 9 integer digits and 2 decimal places")
    @Schema(
        description = "Transaction amount (BigDecimal, scale=2). Maps COBOL S9(09)V99 - range ±999999999.99. "
            + "Sign convention: positive=credit, negative=debit (per COBOL semantics).",
        example = "123.45",
        type = "number",
        format = "decimal",
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    private BigDecimal amount;

    /**
     * Merchant ID (COBOL TRAN-MERCHANT-ID PIC 9(09)).
     * 9-digit numeric identifier.
     */
    @Min(value = 0, message = "Merchant ID must be 0 or greater")
    @Max(value = 999_999_999L, message = "Merchant ID must not exceed 9 digits")
    @Schema(
        description = "9-digit merchant identifier",
        example = "123456789",
        minimum = "0",
        maximum = "999999999",
        requiredMode = Schema.RequiredMode.NOT_REQUIRED,
        nullable = true
    )
    private Long merchantId;

    /**
     * Merchant name (COBOL TRAN-MERCHANT-NAME PIC X(50)).
     * RECORD WIDTH: 50 chars (not BMS width 30).
     */
    @Size(max = 50, message = "Merchant name must not exceed 50 characters")
    @Schema(
        description = "Merchant name (full record width 50 chars per CVTRA05Y PIC X(50))",
        example = "Whole Foods Market Inc - Austin Downtown Branch",
        maxLength = 50,
        requiredMode = Schema.RequiredMode.NOT_REQUIRED,
        nullable = true
    )
    private String merchantName;

    /**
     * Merchant city (COBOL TRAN-MERCHANT-CITY PIC X(50)).
     * RECORD WIDTH: 50 chars (not BMS width 25).
     */
    @Size(max = 50, message = "Merchant city must not exceed 50 characters")
    @Schema(
        description = "Merchant city (full record width 50 chars per CVTRA05Y PIC X(50))",
        example = "Austin",
        maxLength = 50,
        requiredMode = Schema.RequiredMode.NOT_REQUIRED,
        nullable = true
    )
    private String merchantCity;

    /**
     * Merchant ZIP code (COBOL TRAN-MERCHANT-ZIP PIC X(10)).
     */
    @Size(max = 10, message = "Merchant ZIP must not exceed 10 characters")
    @Schema(
        description = "Merchant ZIP code (US 5 or 9 digit; international free-form)",
        example = "78701",
        maxLength = 10,
        requiredMode = Schema.RequiredMode.NOT_REQUIRED,
        nullable = true
    )
    private String merchantZip;

    /**
     * Origin timestamp in DB2 format (COBOL TRAN-ORIG-TS PIC X(26)).
     * Format: yyyy-MM-dd-HH.mm.ss.SSS'0000' (exactly 26 chars) per PR-11.
     * Preserved verbatim at API boundary; conversion to LocalDateTime is done in TransactionMapper.
     */
    @NotNull(message = "Origin timestamp is required")
    @Size(min = 26, max = 26, message = "Origin timestamp must be exactly 26 characters in DB2 format")
    @Pattern(
        regexp = "\\d{4}-\\d{2}-\\d{2}-\\d{2}\\.\\d{2}\\.\\d{2}\\.\\d{3}0000",
        message = "Origin timestamp must match DB2 format yyyy-MM-dd-HH.mm.ss.SSS'0000'"
    )
    @Schema(
        description = "Origin timestamp in DB2 format yyyy-MM-dd-HH.mm.ss.SSS'0000' (26 chars per PR-11). "
            + "Indexed via @Index(idx_transaction_orig_ts) on the entity for range queries.",
        example = "2024-01-15-14.30.45.1230000",
        minLength = 26,
        maxLength = 26,
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String origTimestamp;

    /**
     * Processing timestamp in DB2 format (COBOL TRAN-PROC-TS PIC X(26)).
     * Format: yyyy-MM-dd-HH.mm.ss.SSS'0000' (exactly 26 chars) per PR-11.
     * Set by server at processing time (batch posting or online creation).
     */
    @NotNull(message = "Processing timestamp is required")
    @Size(min = 26, max = 26, message = "Processing timestamp must be exactly 26 characters in DB2 format")
    @Pattern(
        regexp = "\\d{4}-\\d{2}-\\d{2}-\\d{2}\\.\\d{2}\\.\\d{2}\\.\\d{3}0000",
        message = "Processing timestamp must match DB2 format yyyy-MM-dd-HH.mm.ss.SSS'0000'"
    )
    @Schema(
        description = "Processing timestamp in DB2 format yyyy-MM-dd-HH.mm.ss.SSS'0000' (26 chars per PR-11). "
            + "Server-stamped at the time of batch posting or online transaction creation.",
        example = "2024-01-15-14.30.46.0010000",
        minLength = 26,
        maxLength = 26,
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String procTimestamp;
}
