/*
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 */

package com.carddemo.dto.billpayment;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Digits;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.math.BigDecimal;

/**
 * Bill payment response DTO — outbound payload returned by
 * {@code POST /api/accounts/{acctId}/payments}.
 *
 * <p>Represents the outcome of a successful bill payment processed by
 * {@code BillPaymentService} (replacing the COBOL program {@code COBIL00C}'s
 * post-confirmation flow at {@code app/cbl/COBIL00C.cbl}). The original COBOL
 * program signaled success/failure via the BMS {@code ERRMSGO} field on the
 * {@code COBIL0AO} screen; the REST migration replaces this with HTTP 200 OK
 * plus a structured JSON body (this record).
 *
 * <p>The bill payment flow is <b>atomic</b> per AAP §0.4.1.1: within a single
 * {@code @Transactional} boundary in {@code BillPaymentService}, a payment
 * {@code Transaction} entity is created (via {@code TransactionService}) and
 * the {@code Account} balance is updated. Either both operations succeed or
 * neither does (rolled back on exception).
 *
 * <p>Field provenance:
 * <pre>
 *   Field             Source / Computation
 *   ─────             ────────────────────
 *   tranId            Generated by TransactionIdGenerator per PR-10
 *                     (parmDate(10) + suffix(6) = 16 chars total).
 *                     Mirrors COBOL WS-TRAN-ID-NUM PIC 9(16) at
 *                     app/cbl/COBIL00C.cbl line 57.
 *   accountId         Echoed from the request path parameter / body.
 *                     Mirrors COBIL00.CPY ACTIDINI PIC X(11) line 60
 *                     and CVACT01Y ACCT-ID PIC 9(11).
 *   paymentAmount     The amount processed (BigDecimal scale 2).
 *                     Mirrors COBIL00C WS-TRAN-AMT PIC +99999999.99 line 55.
 *   previousBalance   Account balance BEFORE the payment.
 *                     Mirrors CVACT01Y ACCT-CURR-BAL PIC S9(10)V99 line 7.
 *   newBalance        Account balance AFTER the payment
 *                     (= previousBalance - paymentAmount per BillPaymentService).
 *   availableCredit   = creditLimit - newBalance per AAP §0.4.1.1
 *                     (uses CVACT01Y ACCT-CREDIT-LIMIT PIC S9(10)V99 line 8).
 *   processedAt       Timestamp of payment processing in DB2 external format
 *                     YYYY-MM-DD-HH.MM.SS.MIL0000 (26 chars) per PR-11.
 *                     Generated via DateConversionUtil at I/O boundary.
 *   successMessage    Human-readable confirmation
 *                     (e.g., "Payment processed successfully").
 * </pre>
 *
 * <p><b>CRITICAL — PR-16 (BigDecimal for all money):</b> All four monetary
 * fields ({@code paymentAmount}, {@code previousBalance}, {@code newBalance},
 * {@code availableCredit}) are {@code java.math.BigDecimal} with scale 2.
 * NEVER {@code float}/{@code double} (floating-point would corrupt cents).
 *
 * <p><b>CRITICAL — PR-11 (DB2 timestamp format preserved):</b> The
 * {@code processedAt} field is a {@code String} of exactly 26 characters in
 * format {@code yyyy-MM-dd-HH.mm.ss.SSS'0000'}, NOT a {@code LocalDateTime}.
 * This preserves byte-for-byte compatibility with the original COBOL timestamp
 * representation used by {@code CBACT04C} and {@code CBTRN02C}. The conversion
 * from internal {@code LocalDateTime} to this string format happens in
 * {@code DateConversionUtil} at the I/O boundary per AAP §0.6.5.
 *
 * <p><b>Failure responses</b> are NOT modeled by this record. Errors flow through
 * {@code GlobalExceptionHandler} with appropriate HTTP status codes:
 * <ul>
 *   <li>{@code AccountNotFoundException} → 404 (account ID not found in URL)</li>
 *   <li>{@code OverlimitException} → 422 (payment exceeds credit limit)</li>
 *   <li>{@code ExpiredAccountException} → 422 (account past expiration date)</li>
 *   <li>{@code OptimisticLockException} → 409 (concurrent modification)</li>
 *   <li>{@code AccessDeniedException} → 403 (auth failure)</li>
 *   <li>{@code MethodArgumentNotValidException} → 400 (invalid request body)</li>
 * </ul>
 *
 * <p>This is an immutable Java 17 record — equality, hashing, and string
 * representation are auto-generated. Records are implicitly final.
 *
 * @see com.carddemo.dto.billpayment.BillPaymentRequest
 */
@Schema(description = "Bill payment response — returned after a successful payment is processed " +
        "(HTTP 200 OK). Carries the generated transaction ID, balance state before/after the payment, " +
        "and a confirmation message. All monetary fields are BigDecimal with scale 2 per PR-16. " +
        "The processedAt timestamp is in DB2 external format (26 chars) per PR-11. " +
        "Failure responses are not modeled here — errors flow through GlobalExceptionHandler.")
@JsonInclude(JsonInclude.Include.NON_NULL)
public record BillPaymentResponse(

    @NotBlank
    @Size(min = 16, max = 16, message = "tranId must be exactly 16 characters")
    @Schema(description = "Generated payment transaction ID (16 chars, 10-digit parmDate prefix + " +
            "6-digit sequence suffix per PR-10). Mirrors COBOL WS-TRAN-ID-NUM PIC 9(16) at " +
            "app/cbl/COBIL00C.cbl line 57.",
            example = "2024010100000001", minLength = 16, maxLength = 16,
            requiredMode = Schema.RequiredMode.REQUIRED)
    String tranId,

    @NotNull
    @Schema(description = "Account ID for which the payment was processed. Echoed from the request. " +
            "Mirrors COBIL00.CPY ACTIDINI PIC X(11) at line 60 and CVACT01Y ACCT-ID PIC 9(11).",
            example = "10000000001",
            requiredMode = Schema.RequiredMode.REQUIRED)
    Long accountId,

    @NotNull
    @Digits(integer = 10, fraction = 2)
    @Schema(description = "Amount that was processed for this payment (scale 2). " +
            "Mirrors COBIL00C WS-TRAN-AMT PIC +99999999.99 at line 55. " +
            "PR-16: BigDecimal — NEVER float/double.",
            example = "150.00",
            requiredMode = Schema.RequiredMode.REQUIRED)
    BigDecimal paymentAmount,

    @NotNull
    @Digits(integer = 10, fraction = 2)
    @Schema(description = "Account balance BEFORE the payment was applied (scale 2). " +
            "Mirrors CVACT01Y ACCT-CURR-BAL PIC S9(10)V99 at line 7 immediately prior to " +
            "the BillPaymentService update. PR-16: BigDecimal.",
            example = "1500.00",
            requiredMode = Schema.RequiredMode.REQUIRED)
    BigDecimal previousBalance,

    @NotNull
    @Digits(integer = 10, fraction = 2)
    @Schema(description = "Account balance AFTER the payment was applied (scale 2) — " +
            "equals previousBalance minus paymentAmount. Mirrors CVACT01Y ACCT-CURR-BAL " +
            "PIC S9(10)V99 at line 7 after the BillPaymentService update. PR-16: BigDecimal.",
            example = "1350.00",
            requiredMode = Schema.RequiredMode.REQUIRED)
    BigDecimal newBalance,

    @NotNull
    @Digits(integer = 10, fraction = 2)
    @Schema(description = "Available credit after the payment (scale 2) — " +
            "equals creditLimit minus newBalance, per AAP §0.4.1.1. " +
            "Uses CVACT01Y ACCT-CREDIT-LIMIT PIC S9(10)V99 at line 8 and the post-update " +
            "ACCT-CURR-BAL. PR-16: BigDecimal.",
            example = "8650.00",
            requiredMode = Schema.RequiredMode.REQUIRED)
    BigDecimal availableCredit,

    @NotBlank
    @Size(min = 26, max = 26, message = "processedAt must be exactly 26 characters (DB2 timestamp format)")
    @Schema(description = "Timestamp of payment processing in DB2 external format " +
            "yyyy-MM-dd-HH.mm.ss.SSS'0000' (26 chars total). Preserves byte-for-byte compatibility " +
            "with COBOL CBACT04C/CBTRN02C timestamp emission per PR-11. " +
            "Generated via DateConversionUtil at the I/O boundary.",
            example = "2024-01-15-09.30.45.1230000", minLength = 26, maxLength = 26,
            requiredMode = Schema.RequiredMode.REQUIRED)
    String processedAt,

    @NotBlank
    @Size(max = 200)
    @Schema(description = "Human-readable confirmation message. " +
            "Modernization addition (no direct COBOL equivalent — original COBOL emitted messages " +
            "via BMS ERRMSGO field). Typical values: 'Payment processed successfully'.",
            example = "Payment processed successfully",
            requiredMode = Schema.RequiredMode.REQUIRED)
    String successMessage

) {
}
