-- Account service reference data, third of three migrations. Every value below is a literal of
-- app/cpy/CSLKPCDY.cpy, in copybook order. V1__schema.sql declares the three tables.

-- us_phone_area_code carries one row per distinct area code. band records which condition name
-- of app/cpy/CSLKPCDY.cpy declares the code. The two bands are disjoint, and their union is the
-- 490 codes of VALID-PHONE-AREA-CODE at app/cpy/CSLKPCDY.cpy:L30-L520.

-- 410 codes of VALID-GENERAL-PURP-CODE at app/cpy/CSLKPCDY.cpy:L521-L930, the only band
-- app/cbl/COACTUPC.cbl:L2298 tests.
INSERT INTO us_phone_area_code (area_code, band) VALUES
    ('201', 'GENERAL_PURPOSE'),
    ('202', 'GENERAL_PURPOSE'),
    ('203', 'GENERAL_PURPOSE'),
    ('204', 'GENERAL_PURPOSE'),
    ('205', 'GENERAL_PURPOSE'),
    ('206', 'GENERAL_PURPOSE'),
    ('207', 'GENERAL_PURPOSE'),
    ('208', 'GENERAL_PURPOSE'),
    ('209', 'GENERAL_PURPOSE'),
    ('210', 'GENERAL_PURPOSE'),
    ('212', 'GENERAL_PURPOSE'),
    ('213', 'GENERAL_PURPOSE'),
    ('214', 'GENERAL_PURPOSE'),
    ('215', 'GENERAL_PURPOSE'),
    ('216', 'GENERAL_PURPOSE'),
    ('217', 'GENERAL_PURPOSE'),
    ('218', 'GENERAL_PURPOSE'),
    ('219', 'GENERAL_PURPOSE'),
    ('220', 'GENERAL_PURPOSE'),
    ('223', 'GENERAL_PURPOSE'),
    ('224', 'GENERAL_PURPOSE'),
    ('225', 'GENERAL_PURPOSE'),
    ('226', 'GENERAL_PURPOSE'),
    ('228', 'GENERAL_PURPOSE'),
    ('229', 'GENERAL_PURPOSE'),
    ('231', 'GENERAL_PURPOSE'),
    ('234', 'GENERAL_PURPOSE'),
    ('236', 'GENERAL_PURPOSE'),
    ('239', 'GENERAL_PURPOSE'),
    ('240', 'GENERAL_PURPOSE'),
    ('242', 'GENERAL_PURPOSE'),
    ('246', 'GENERAL_PURPOSE'),
    ('248', 'GENERAL_PURPOSE'),
    ('249', 'GENERAL_PURPOSE'),
    ('250', 'GENERAL_PURPOSE'),
    ('251', 'GENERAL_PURPOSE'),
    ('252', 'GENERAL_PURPOSE'),
    ('253', 'GENERAL_PURPOSE'),
    ('254', 'GENERAL_PURPOSE'),
    ('256', 'GENERAL_PURPOSE'),
    ('260', 'GENERAL_PURPOSE'),
    ('262', 'GENERAL_PURPOSE'),
    ('264', 'GENERAL_PURPOSE'),
    ('267', 'GENERAL_PURPOSE'),
    ('268', 'GENERAL_PURPOSE'),
    ('269', 'GENERAL_PURPOSE'),
    ('270', 'GENERAL_PURPOSE'),
    ('272', 'GENERAL_PURPOSE'),
    ('276', 'GENERAL_PURPOSE'),
    ('279', 'GENERAL_PURPOSE'),
    ('281', 'GENERAL_PURPOSE'),
    ('284', 'GENERAL_PURPOSE'),
    ('289', 'GENERAL_PURPOSE'),
    ('301', 'GENERAL_PURPOSE'),
    ('302', 'GENERAL_PURPOSE'),
    ('303', 'GENERAL_PURPOSE'),
    ('304', 'GENERAL_PURPOSE'),
    ('305', 'GENERAL_PURPOSE'),
    ('306', 'GENERAL_PURPOSE'),
    ('307', 'GENERAL_PURPOSE'),
    ('308', 'GENERAL_PURPOSE'),
    ('309', 'GENERAL_PURPOSE'),
    ('310', 'GENERAL_PURPOSE'),
    ('312', 'GENERAL_PURPOSE'),
    ('313', 'GENERAL_PURPOSE'),
    ('314', 'GENERAL_PURPOSE'),
    ('315', 'GENERAL_PURPOSE'),
    ('316', 'GENERAL_PURPOSE'),
    ('317', 'GENERAL_PURPOSE'),
    ('318', 'GENERAL_PURPOSE'),
    ('319', 'GENERAL_PURPOSE'),
    ('320', 'GENERAL_PURPOSE'),
    ('321', 'GENERAL_PURPOSE'),
    ('323', 'GENERAL_PURPOSE'),
    ('325', 'GENERAL_PURPOSE'),
    ('326', 'GENERAL_PURPOSE'),
    ('330', 'GENERAL_PURPOSE'),
    ('331', 'GENERAL_PURPOSE'),
    ('332', 'GENERAL_PURPOSE'),
    ('334', 'GENERAL_PURPOSE'),
    ('336', 'GENERAL_PURPOSE'),
    ('337', 'GENERAL_PURPOSE'),
    ('339', 'GENERAL_PURPOSE'),
    ('340', 'GENERAL_PURPOSE'),
    ('341', 'GENERAL_PURPOSE'),
    ('343', 'GENERAL_PURPOSE'),
    ('345', 'GENERAL_PURPOSE'),
    ('346', 'GENERAL_PURPOSE'),
    ('347', 'GENERAL_PURPOSE'),
    ('351', 'GENERAL_PURPOSE'),
    ('352', 'GENERAL_PURPOSE'),
    ('360', 'GENERAL_PURPOSE'),
    ('361', 'GENERAL_PURPOSE'),
    ('364', 'GENERAL_PURPOSE'),
    ('365', 'GENERAL_PURPOSE'),
    ('367', 'GENERAL_PURPOSE'),
    ('368', 'GENERAL_PURPOSE'),
    ('380', 'GENERAL_PURPOSE'),
    ('385', 'GENERAL_PURPOSE'),
    ('386', 'GENERAL_PURPOSE'),
    ('401', 'GENERAL_PURPOSE'),
    ('402', 'GENERAL_PURPOSE'),
    ('403', 'GENERAL_PURPOSE'),
    ('404', 'GENERAL_PURPOSE'),
    ('405', 'GENERAL_PURPOSE'),
    ('406', 'GENERAL_PURPOSE'),
    ('407', 'GENERAL_PURPOSE'),
    ('408', 'GENERAL_PURPOSE'),
    ('409', 'GENERAL_PURPOSE'),
    ('410', 'GENERAL_PURPOSE'),
    ('412', 'GENERAL_PURPOSE'),
    ('413', 'GENERAL_PURPOSE'),
    ('414', 'GENERAL_PURPOSE'),
    ('415', 'GENERAL_PURPOSE'),
    ('416', 'GENERAL_PURPOSE'),
    ('417', 'GENERAL_PURPOSE'),
    ('418', 'GENERAL_PURPOSE'),
    ('419', 'GENERAL_PURPOSE'),
    ('423', 'GENERAL_PURPOSE'),
    ('424', 'GENERAL_PURPOSE'),
    ('425', 'GENERAL_PURPOSE'),
    ('430', 'GENERAL_PURPOSE'),
    ('431', 'GENERAL_PURPOSE'),
    ('432', 'GENERAL_PURPOSE'),
    ('434', 'GENERAL_PURPOSE'),
    ('435', 'GENERAL_PURPOSE'),
    ('437', 'GENERAL_PURPOSE'),
    ('438', 'GENERAL_PURPOSE'),
    ('440', 'GENERAL_PURPOSE'),
    ('441', 'GENERAL_PURPOSE'),
    ('442', 'GENERAL_PURPOSE'),
    ('443', 'GENERAL_PURPOSE'),
    ('445', 'GENERAL_PURPOSE'),
    ('447', 'GENERAL_PURPOSE'),
    ('448', 'GENERAL_PURPOSE'),
    ('450', 'GENERAL_PURPOSE'),
    ('458', 'GENERAL_PURPOSE'),
    ('463', 'GENERAL_PURPOSE'),
    ('464', 'GENERAL_PURPOSE'),
    ('469', 'GENERAL_PURPOSE'),
    ('470', 'GENERAL_PURPOSE'),
    ('473', 'GENERAL_PURPOSE'),
    ('474', 'GENERAL_PURPOSE'),
    ('475', 'GENERAL_PURPOSE'),
    ('478', 'GENERAL_PURPOSE'),
    ('479', 'GENERAL_PURPOSE'),
    ('480', 'GENERAL_PURPOSE'),
    ('484', 'GENERAL_PURPOSE'),
    ('501', 'GENERAL_PURPOSE'),
    ('502', 'GENERAL_PURPOSE'),
    ('503', 'GENERAL_PURPOSE'),
    ('504', 'GENERAL_PURPOSE'),
    ('505', 'GENERAL_PURPOSE'),
    ('506', 'GENERAL_PURPOSE'),
    ('507', 'GENERAL_PURPOSE'),
    ('508', 'GENERAL_PURPOSE'),
    ('509', 'GENERAL_PURPOSE'),
    ('510', 'GENERAL_PURPOSE'),
    ('512', 'GENERAL_PURPOSE'),
    ('513', 'GENERAL_PURPOSE'),
    ('514', 'GENERAL_PURPOSE'),
    ('515', 'GENERAL_PURPOSE'),
    ('516', 'GENERAL_PURPOSE'),
    ('517', 'GENERAL_PURPOSE'),
    ('518', 'GENERAL_PURPOSE'),
    ('519', 'GENERAL_PURPOSE'),
    ('520', 'GENERAL_PURPOSE'),
    ('530', 'GENERAL_PURPOSE'),
    ('531', 'GENERAL_PURPOSE'),
    ('534', 'GENERAL_PURPOSE'),
    ('539', 'GENERAL_PURPOSE'),
    ('540', 'GENERAL_PURPOSE'),
    ('541', 'GENERAL_PURPOSE'),
    ('548', 'GENERAL_PURPOSE'),
    ('551', 'GENERAL_PURPOSE'),
    ('559', 'GENERAL_PURPOSE'),
    ('561', 'GENERAL_PURPOSE'),
    ('562', 'GENERAL_PURPOSE'),
    ('563', 'GENERAL_PURPOSE'),
    ('564', 'GENERAL_PURPOSE'),
    ('567', 'GENERAL_PURPOSE'),
    ('570', 'GENERAL_PURPOSE'),
    ('571', 'GENERAL_PURPOSE'),
    ('572', 'GENERAL_PURPOSE'),
    ('573', 'GENERAL_PURPOSE'),
    ('574', 'GENERAL_PURPOSE'),
    ('575', 'GENERAL_PURPOSE'),
    ('579', 'GENERAL_PURPOSE'),
    ('580', 'GENERAL_PURPOSE'),
    ('581', 'GENERAL_PURPOSE'),
    ('582', 'GENERAL_PURPOSE'),
    ('585', 'GENERAL_PURPOSE'),
    ('586', 'GENERAL_PURPOSE'),
    ('587', 'GENERAL_PURPOSE'),
    ('601', 'GENERAL_PURPOSE'),
    ('602', 'GENERAL_PURPOSE'),
    ('603', 'GENERAL_PURPOSE'),
    ('604', 'GENERAL_PURPOSE'),
    ('605', 'GENERAL_PURPOSE'),
    ('606', 'GENERAL_PURPOSE'),
    ('607', 'GENERAL_PURPOSE'),
    ('608', 'GENERAL_PURPOSE'),
    ('609', 'GENERAL_PURPOSE'),
    ('610', 'GENERAL_PURPOSE'),
    ('612', 'GENERAL_PURPOSE'),
    ('613', 'GENERAL_PURPOSE'),
    ('614', 'GENERAL_PURPOSE'),
    ('615', 'GENERAL_PURPOSE'),
    ('616', 'GENERAL_PURPOSE'),
    ('617', 'GENERAL_PURPOSE'),
    ('618', 'GENERAL_PURPOSE'),
    ('619', 'GENERAL_PURPOSE'),
    ('620', 'GENERAL_PURPOSE'),
    ('623', 'GENERAL_PURPOSE'),
    ('626', 'GENERAL_PURPOSE'),
    ('628', 'GENERAL_PURPOSE'),
    ('629', 'GENERAL_PURPOSE'),
    ('630', 'GENERAL_PURPOSE'),
    ('631', 'GENERAL_PURPOSE'),
    ('636', 'GENERAL_PURPOSE'),
    ('639', 'GENERAL_PURPOSE'),
    ('640', 'GENERAL_PURPOSE'),
    ('641', 'GENERAL_PURPOSE'),
    ('646', 'GENERAL_PURPOSE'),
    ('647', 'GENERAL_PURPOSE'),
    ('649', 'GENERAL_PURPOSE'),
    ('650', 'GENERAL_PURPOSE'),
    ('651', 'GENERAL_PURPOSE'),
    ('656', 'GENERAL_PURPOSE'),
    ('657', 'GENERAL_PURPOSE'),
    ('658', 'GENERAL_PURPOSE'),
    ('659', 'GENERAL_PURPOSE'),
    ('660', 'GENERAL_PURPOSE'),
    ('661', 'GENERAL_PURPOSE'),
    ('662', 'GENERAL_PURPOSE'),
    ('664', 'GENERAL_PURPOSE'),
    ('667', 'GENERAL_PURPOSE'),
    ('669', 'GENERAL_PURPOSE'),
    ('670', 'GENERAL_PURPOSE'),
    ('671', 'GENERAL_PURPOSE'),
    ('672', 'GENERAL_PURPOSE'),
    ('678', 'GENERAL_PURPOSE'),
    ('680', 'GENERAL_PURPOSE'),
    ('681', 'GENERAL_PURPOSE'),
    ('682', 'GENERAL_PURPOSE'),
    ('683', 'GENERAL_PURPOSE'),
    ('684', 'GENERAL_PURPOSE'),
    ('689', 'GENERAL_PURPOSE'),
    ('701', 'GENERAL_PURPOSE'),
    ('702', 'GENERAL_PURPOSE'),
    ('703', 'GENERAL_PURPOSE'),
    ('704', 'GENERAL_PURPOSE'),
    ('705', 'GENERAL_PURPOSE'),
    ('706', 'GENERAL_PURPOSE'),
    ('707', 'GENERAL_PURPOSE'),
    ('708', 'GENERAL_PURPOSE'),
    ('709', 'GENERAL_PURPOSE'),
    ('712', 'GENERAL_PURPOSE'),
    ('713', 'GENERAL_PURPOSE'),
    ('714', 'GENERAL_PURPOSE'),
    ('715', 'GENERAL_PURPOSE'),
    ('716', 'GENERAL_PURPOSE'),
    ('717', 'GENERAL_PURPOSE'),
    ('718', 'GENERAL_PURPOSE'),
    ('719', 'GENERAL_PURPOSE'),
    ('720', 'GENERAL_PURPOSE'),
    ('721', 'GENERAL_PURPOSE'),
    ('724', 'GENERAL_PURPOSE'),
    ('725', 'GENERAL_PURPOSE'),
    ('726', 'GENERAL_PURPOSE'),
    ('727', 'GENERAL_PURPOSE'),
    ('731', 'GENERAL_PURPOSE'),
    ('732', 'GENERAL_PURPOSE'),
    ('734', 'GENERAL_PURPOSE'),
    ('737', 'GENERAL_PURPOSE'),
    ('740', 'GENERAL_PURPOSE'),
    ('742', 'GENERAL_PURPOSE'),
    ('743', 'GENERAL_PURPOSE'),
    ('747', 'GENERAL_PURPOSE'),
    ('753', 'GENERAL_PURPOSE'),
    ('754', 'GENERAL_PURPOSE'),
    ('757', 'GENERAL_PURPOSE'),
    ('758', 'GENERAL_PURPOSE'),
    ('760', 'GENERAL_PURPOSE'),
    ('762', 'GENERAL_PURPOSE'),
    ('763', 'GENERAL_PURPOSE'),
    ('765', 'GENERAL_PURPOSE'),
    ('767', 'GENERAL_PURPOSE'),
    ('769', 'GENERAL_PURPOSE'),
    ('770', 'GENERAL_PURPOSE'),
    ('771', 'GENERAL_PURPOSE'),
    ('772', 'GENERAL_PURPOSE'),
    ('773', 'GENERAL_PURPOSE'),
    ('774', 'GENERAL_PURPOSE'),
    ('775', 'GENERAL_PURPOSE'),
    ('778', 'GENERAL_PURPOSE'),
    ('779', 'GENERAL_PURPOSE'),
    ('780', 'GENERAL_PURPOSE'),
    ('781', 'GENERAL_PURPOSE'),
    ('782', 'GENERAL_PURPOSE'),
    ('784', 'GENERAL_PURPOSE'),
    ('785', 'GENERAL_PURPOSE'),
    ('786', 'GENERAL_PURPOSE'),
    ('787', 'GENERAL_PURPOSE'),
    ('801', 'GENERAL_PURPOSE'),
    ('802', 'GENERAL_PURPOSE'),
    ('803', 'GENERAL_PURPOSE'),
    ('804', 'GENERAL_PURPOSE'),
    ('805', 'GENERAL_PURPOSE'),
    ('806', 'GENERAL_PURPOSE'),
    ('807', 'GENERAL_PURPOSE'),
    ('808', 'GENERAL_PURPOSE'),
    ('809', 'GENERAL_PURPOSE'),
    ('810', 'GENERAL_PURPOSE'),
    ('812', 'GENERAL_PURPOSE'),
    ('813', 'GENERAL_PURPOSE'),
    ('814', 'GENERAL_PURPOSE'),
    ('815', 'GENERAL_PURPOSE'),
    ('816', 'GENERAL_PURPOSE'),
    ('817', 'GENERAL_PURPOSE'),
    ('818', 'GENERAL_PURPOSE'),
    ('819', 'GENERAL_PURPOSE'),
    ('820', 'GENERAL_PURPOSE'),
    ('825', 'GENERAL_PURPOSE'),
    ('826', 'GENERAL_PURPOSE'),
    ('828', 'GENERAL_PURPOSE'),
    ('829', 'GENERAL_PURPOSE'),
    ('830', 'GENERAL_PURPOSE'),
    ('831', 'GENERAL_PURPOSE'),
    ('832', 'GENERAL_PURPOSE'),
    ('838', 'GENERAL_PURPOSE'),
    ('839', 'GENERAL_PURPOSE'),
    ('840', 'GENERAL_PURPOSE'),
    ('843', 'GENERAL_PURPOSE'),
    ('845', 'GENERAL_PURPOSE'),
    ('847', 'GENERAL_PURPOSE'),
    ('848', 'GENERAL_PURPOSE'),
    ('849', 'GENERAL_PURPOSE'),
    ('850', 'GENERAL_PURPOSE'),
    ('854', 'GENERAL_PURPOSE'),
    ('856', 'GENERAL_PURPOSE'),
    ('857', 'GENERAL_PURPOSE'),
    ('858', 'GENERAL_PURPOSE'),
    ('859', 'GENERAL_PURPOSE'),
    ('860', 'GENERAL_PURPOSE'),
    ('862', 'GENERAL_PURPOSE'),
    ('863', 'GENERAL_PURPOSE'),
    ('864', 'GENERAL_PURPOSE'),
    ('865', 'GENERAL_PURPOSE'),
    ('867', 'GENERAL_PURPOSE'),
    ('868', 'GENERAL_PURPOSE'),
    ('869', 'GENERAL_PURPOSE'),
    ('870', 'GENERAL_PURPOSE'),
    ('872', 'GENERAL_PURPOSE'),
    ('873', 'GENERAL_PURPOSE'),
    ('876', 'GENERAL_PURPOSE'),
    ('878', 'GENERAL_PURPOSE'),
    ('901', 'GENERAL_PURPOSE'),
    ('902', 'GENERAL_PURPOSE'),
    ('903', 'GENERAL_PURPOSE'),
    ('904', 'GENERAL_PURPOSE'),
    ('905', 'GENERAL_PURPOSE'),
    ('906', 'GENERAL_PURPOSE'),
    ('907', 'GENERAL_PURPOSE'),
    ('908', 'GENERAL_PURPOSE'),
    ('909', 'GENERAL_PURPOSE'),
    ('910', 'GENERAL_PURPOSE'),
    ('912', 'GENERAL_PURPOSE'),
    ('913', 'GENERAL_PURPOSE'),
    ('914', 'GENERAL_PURPOSE'),
    ('915', 'GENERAL_PURPOSE'),
    ('916', 'GENERAL_PURPOSE'),
    ('917', 'GENERAL_PURPOSE'),
    ('918', 'GENERAL_PURPOSE'),
    ('919', 'GENERAL_PURPOSE'),
    ('920', 'GENERAL_PURPOSE'),
    ('925', 'GENERAL_PURPOSE'),
    ('928', 'GENERAL_PURPOSE'),
    ('929', 'GENERAL_PURPOSE'),
    ('930', 'GENERAL_PURPOSE'),
    ('931', 'GENERAL_PURPOSE'),
    ('934', 'GENERAL_PURPOSE'),
    ('936', 'GENERAL_PURPOSE'),
    ('937', 'GENERAL_PURPOSE'),
    ('938', 'GENERAL_PURPOSE'),
    ('939', 'GENERAL_PURPOSE'),
    ('940', 'GENERAL_PURPOSE'),
    ('941', 'GENERAL_PURPOSE'),
    ('943', 'GENERAL_PURPOSE'),
    ('945', 'GENERAL_PURPOSE'),
    ('947', 'GENERAL_PURPOSE'),
    ('948', 'GENERAL_PURPOSE'),
    ('949', 'GENERAL_PURPOSE'),
    ('951', 'GENERAL_PURPOSE'),
    ('952', 'GENERAL_PURPOSE'),
    ('954', 'GENERAL_PURPOSE'),
    ('956', 'GENERAL_PURPOSE'),
    ('959', 'GENERAL_PURPOSE'),
    ('970', 'GENERAL_PURPOSE'),
    ('971', 'GENERAL_PURPOSE'),
    ('972', 'GENERAL_PURPOSE'),
    ('973', 'GENERAL_PURPOSE'),
    ('978', 'GENERAL_PURPOSE'),
    ('979', 'GENERAL_PURPOSE'),
    ('980', 'GENERAL_PURPOSE'),
    ('983', 'GENERAL_PURPOSE'),
    ('984', 'GENERAL_PURPOSE'),
    ('985', 'GENERAL_PURPOSE'),
    ('986', 'GENERAL_PURPOSE'),
    ('989', 'GENERAL_PURPOSE');

-- 80 codes of VALID-EASY-RECOG-AREA-CODE at app/cpy/CSLKPCDY.cpy:L931-L1010.
INSERT INTO us_phone_area_code (area_code, band) VALUES
    ('200', 'EASILY_RECOGNISABLE'),
    ('211', 'EASILY_RECOGNISABLE'),
    ('222', 'EASILY_RECOGNISABLE'),
    ('233', 'EASILY_RECOGNISABLE'),
    ('244', 'EASILY_RECOGNISABLE'),
    ('255', 'EASILY_RECOGNISABLE'),
    ('266', 'EASILY_RECOGNISABLE'),
    ('277', 'EASILY_RECOGNISABLE'),
    ('288', 'EASILY_RECOGNISABLE'),
    ('299', 'EASILY_RECOGNISABLE'),
    ('300', 'EASILY_RECOGNISABLE'),
    ('311', 'EASILY_RECOGNISABLE'),
    ('322', 'EASILY_RECOGNISABLE'),
    ('333', 'EASILY_RECOGNISABLE'),
    ('344', 'EASILY_RECOGNISABLE'),
    ('355', 'EASILY_RECOGNISABLE'),
    ('366', 'EASILY_RECOGNISABLE'),
    ('377', 'EASILY_RECOGNISABLE'),
    ('388', 'EASILY_RECOGNISABLE'),
    ('399', 'EASILY_RECOGNISABLE'),
    ('400', 'EASILY_RECOGNISABLE'),
    ('411', 'EASILY_RECOGNISABLE'),
    ('422', 'EASILY_RECOGNISABLE'),
    ('433', 'EASILY_RECOGNISABLE'),
    ('444', 'EASILY_RECOGNISABLE'),
    ('455', 'EASILY_RECOGNISABLE'),
    ('466', 'EASILY_RECOGNISABLE'),
    ('477', 'EASILY_RECOGNISABLE'),
    ('488', 'EASILY_RECOGNISABLE'),
    ('499', 'EASILY_RECOGNISABLE'),
    ('500', 'EASILY_RECOGNISABLE'),
    ('511', 'EASILY_RECOGNISABLE'),
    ('522', 'EASILY_RECOGNISABLE'),
    ('533', 'EASILY_RECOGNISABLE'),
    ('544', 'EASILY_RECOGNISABLE'),
    ('555', 'EASILY_RECOGNISABLE'),
    ('566', 'EASILY_RECOGNISABLE'),
    ('577', 'EASILY_RECOGNISABLE'),
    ('588', 'EASILY_RECOGNISABLE'),
    ('599', 'EASILY_RECOGNISABLE'),
    ('600', 'EASILY_RECOGNISABLE'),
    ('611', 'EASILY_RECOGNISABLE'),
    ('622', 'EASILY_RECOGNISABLE'),
    ('633', 'EASILY_RECOGNISABLE'),
    ('644', 'EASILY_RECOGNISABLE'),
    ('655', 'EASILY_RECOGNISABLE'),
    ('666', 'EASILY_RECOGNISABLE'),
    ('677', 'EASILY_RECOGNISABLE'),
    ('688', 'EASILY_RECOGNISABLE'),
    ('699', 'EASILY_RECOGNISABLE'),
    ('700', 'EASILY_RECOGNISABLE'),
    ('711', 'EASILY_RECOGNISABLE'),
    ('722', 'EASILY_RECOGNISABLE'),
    ('733', 'EASILY_RECOGNISABLE'),
    ('744', 'EASILY_RECOGNISABLE'),
    ('755', 'EASILY_RECOGNISABLE'),
    ('766', 'EASILY_RECOGNISABLE'),
    ('777', 'EASILY_RECOGNISABLE'),
    ('788', 'EASILY_RECOGNISABLE'),
    ('799', 'EASILY_RECOGNISABLE'),
    ('800', 'EASILY_RECOGNISABLE'),
    ('811', 'EASILY_RECOGNISABLE'),
    ('822', 'EASILY_RECOGNISABLE'),
    ('833', 'EASILY_RECOGNISABLE'),
    ('844', 'EASILY_RECOGNISABLE'),
    ('855', 'EASILY_RECOGNISABLE'),
    ('866', 'EASILY_RECOGNISABLE'),
    ('877', 'EASILY_RECOGNISABLE'),
    ('888', 'EASILY_RECOGNISABLE'),
    ('899', 'EASILY_RECOGNISABLE'),
    ('900', 'EASILY_RECOGNISABLE'),
    ('911', 'EASILY_RECOGNISABLE'),
    ('922', 'EASILY_RECOGNISABLE'),
    ('933', 'EASILY_RECOGNISABLE'),
    ('944', 'EASILY_RECOGNISABLE'),
    ('955', 'EASILY_RECOGNISABLE'),
    ('966', 'EASILY_RECOGNISABLE'),
    ('977', 'EASILY_RECOGNISABLE'),
    ('988', 'EASILY_RECOGNISABLE'),
    ('999', 'EASILY_RECOGNISABLE');

-- 56 codes of VALID-US-STATE-CODE at app/cpy/CSLKPCDY.cpy:L1014-L1069. The order runs
-- alphabetically by state name, then the six codes outside the fifty states.
INSERT INTO us_state_code (state_code) VALUES
    ('AL'), ('AK'), ('AZ'), ('AR'), ('CA'), ('CO'), ('CT'), ('DE'), ('FL'), ('GA'),
    ('HI'), ('ID'), ('IL'), ('IN'), ('IA'), ('KS'), ('KY'), ('LA'), ('ME'), ('MD'),
    ('MA'), ('MI'), ('MN'), ('MS'), ('MO'), ('MT'), ('NE'), ('NV'), ('NH'), ('NJ'),
    ('NM'), ('NY'), ('NC'), ('ND'), ('OH'), ('OK'), ('OR'), ('PA'), ('RI'), ('SC'),
    ('SD'), ('TN'), ('TX'), ('UT'), ('VT'), ('VA'), ('WA'), ('WV'), ('WI'), ('WY'),
    ('DC'), ('AS'), ('GU'), ('MP'), ('PR'), ('VI');

-- 240 combinations of VALID-US-STATE-ZIP-CD2-COMBO at app/cpy/CSLKPCDY.cpy:L1074-L1313.
-- app/cbl/COACTUPC.cbl:L2537-L2540 assembles each value from a two-character state code and
-- the first two characters of a zip code.
INSERT INTO us_state_zip_prefix (state_zip_prefix) VALUES
    ('AA34'), ('AE90'), ('AE91'), ('AE92'), ('AE93'), ('AE94'), ('AE95'), ('AE96'),
    ('AE97'), ('AE98'), ('AK99'), ('AL35'), ('AL36'), ('AP96'), ('AR71'), ('AR72'),
    ('AS96'), ('AZ85'), ('AZ86'), ('CA90'), ('CA91'), ('CA92'), ('CA93'), ('CA94'),
    ('CA95'), ('CA96'), ('CO80'), ('CO81'), ('CT60'), ('CT61'), ('CT62'), ('CT63'),
    ('CT64'), ('CT65'), ('CT66'), ('CT67'), ('CT68'), ('CT69'), ('DC20'), ('DC56'),
    ('DC88'), ('DE19'), ('FL32'), ('FL33'), ('FL34'), ('FM96'), ('GA30'), ('GA31'),
    ('GA39'), ('GU96'), ('HI96'), ('IA50'), ('IA51'), ('IA52'), ('ID83'), ('IL60'),
    ('IL61'), ('IL62'), ('IN46'), ('IN47'), ('KS66'), ('KS67'), ('KY40'), ('KY41'),
    ('KY42'), ('LA70'), ('LA71'), ('MA10'), ('MA11'), ('MA12'), ('MA13'), ('MA14'),
    ('MA15'), ('MA16'), ('MA17'), ('MA18'), ('MA19'), ('MA20'), ('MA21'), ('MA22'),
    ('MA23'), ('MA24'), ('MA25'), ('MA26'), ('MA27'), ('MA55'), ('MD20'), ('MD21'),
    ('ME39'), ('ME40'), ('ME41'), ('ME42'), ('ME43'), ('ME44'), ('ME45'), ('ME46'),
    ('ME47'), ('ME48'), ('ME49'), ('MH96'), ('MI48'), ('MI49'), ('MN55'), ('MN56'),
    ('MO63'), ('MO64'), ('MO65'), ('MO72'), ('MP96'), ('MS38'), ('MS39'), ('MT59'),
    ('NC27'), ('NC28'), ('ND58'), ('NE68'), ('NE69'), ('NH30'), ('NH31'), ('NH32'),
    ('NH33'), ('NH34'), ('NH35'), ('NH36'), ('NH37'), ('NH38'), ('NJ70'), ('NJ71'),
    ('NJ72'), ('NJ73'), ('NJ74'), ('NJ75'), ('NJ76'), ('NJ77'), ('NJ78'), ('NJ79'),
    ('NJ80'), ('NJ81'), ('NJ82'), ('NJ83'), ('NJ84'), ('NJ85'), ('NJ86'), ('NJ87'),
    ('NJ88'), ('NJ89'), ('NM87'), ('NM88'), ('NV88'), ('NV89'), ('NY50'), ('NY54'),
    ('NY63'), ('NY10'), ('NY11'), ('NY12'), ('NY13'), ('NY14'), ('OH43'), ('OH44'),
    ('OH45'), ('OK73'), ('OK74'), ('OR97'), ('PA15'), ('PA16'), ('PA17'), ('PA18'),
    ('PA19'), ('PR60'), ('PR61'), ('PR62'), ('PR63'), ('PR64'), ('PR65'), ('PR66'),
    ('PR67'), ('PR68'), ('PR69'), ('PR70'), ('PR71'), ('PR72'), ('PR73'), ('PR74'),
    ('PR75'), ('PR76'), ('PR77'), ('PR78'), ('PR79'), ('PR90'), ('PR91'), ('PR92'),
    ('PR93'), ('PR94'), ('PR95'), ('PR96'), ('PR97'), ('PR98'), ('PW96'), ('RI28'),
    ('RI29'), ('SC29'), ('SD57'), ('TN37'), ('TN38'), ('TX73'), ('TX75'), ('TX76'),
    ('TX77'), ('TX78'), ('TX79'), ('TX88'), ('UT84'), ('VA20'), ('VA22'), ('VA23'),
    ('VA24'), ('VI80'), ('VI82'), ('VI83'), ('VI84'), ('VI85'), ('VT50'), ('VT51'),
    ('VT52'), ('VT53'), ('VT54'), ('VT56'), ('VT57'), ('VT58'), ('VT59'), ('WA98'),
    ('WA99'), ('WI53'), ('WI54'), ('WV24'), ('WV25'), ('WV26'), ('WY82'), ('WY83');
