package com.aws.carddemo.config.logging;

import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.encoder.Encoder;
import ch.qos.logback.core.encoder.EncoderBase;

import java.nio.charset.StandardCharsets;

/**
 * A Logback {@link Encoder} that wraps another encoder and redacts sensitive digit sequences (card
 * PANs) from the bytes the wrapped encoder produces, using {@link SensitiveDataMasker}.
 *
 * <p><b>Purpose (QA finding F-1 / Observability rule).</b> The migrated CardDemo emits its logs
 * through two console appenders declared in {@code src/main/resources/logback-spring.xml}: a
 * human-readable pattern encoder on the {@code dev} profile and Spring Boot's ECS
 * {@code StructuredLogEncoder} (JSON) on every other profile. When Spring Batch fails to parse a
 * fixed-width record it raises a {@code FlatFileParseException} whose message embeds the raw record
 * (including the 16-digit card number) and {@code AbstractStep} logs it at {@code ERROR}. That
 * message is generated by the framework, not by application code, so it cannot be sanitized at the
 * call site. Wrapping each appender's real encoder with this masking encoder neutralizes the PAN at
 * the logging sink &mdash; for <em>every</em> log line, in whichever output format &mdash; while
 * leaving the batch job's functional behaviour (the {@code FlatFileParseException} still propagates
 * and the step still fails with RC8) completely unchanged. The decision to mask at the sink rather
 * than change the reader's error handling is recorded in {@code docs/decision-log.md}.</p>
 *
 * <h2>Configuration</h2>
 * <p>The wrapped encoder is supplied as a nested {@code <delegate>} element whose {@code class}
 * attribute names the real encoder, for example:</p>
 * <pre>{@code
 * <encoder class="com.aws.carddemo.config.logging.MaskingLogbackEncoder">
 *   <delegate class="org.springframework.boot.logging.logback.StructuredLogEncoder">
 *     <format>ecs</format>
 *   </delegate>
 * </encoder>
 * }</pre>
 * <p>Logback instantiates the delegate from its {@code class} attribute, applies the delegate's own
 * nested configuration ({@code <format>}, {@code <pattern>}, &hellip;), then injects it via
 * {@link #setDelegate(Encoder)}. This encoder owns the delegate's lifecycle: {@link #start()} sets
 * the delegate's Logback {@code Context} and starts it (so a delegate such as
 * {@code StructuredLogEncoder}, which resolves the Spring {@code Environment} from the logger
 * context during {@code start()}, initializes exactly as it would unwrapped), and {@link #stop()}
 * stops it.</p>
 *
 * <h2>Byte handling</h2>
 * <p>The delegate returns encoded {@code byte[]}. Masking is performed by decoding those bytes with
 * ISO-8859-1, masking the resulting text, and re-encoding with ISO-8859-1. ISO-8859-1 is a total,
 * bijective byte&harr;char mapping (every one of the 256 byte values maps to a distinct code point
 * and back), so this round-trip never corrupts non-digit bytes &mdash; including UTF-8 multi-byte
 * sequences, whose continuation bytes ({@code 0x80}-{@code 0xBF}) and lead bytes ({@code 0xC0}+) can
 * never be confused with the ASCII digits ({@code 0x30}-{@code 0x39}) that {@link SensitiveDataMasker}
 * targets. When nothing is masked, {@link SensitiveDataMasker#mask(String)} returns the same String
 * instance, and the original {@code byte[]} is returned as-is to avoid a needless re-encode.</p>
 */
public class MaskingLogbackEncoder extends EncoderBase<ILoggingEvent> {

    /** Shared empty result used only in the misconfiguration guard (no delegate set). */
    private static final byte[] EMPTY = new byte[0];

    /** The wrapped encoder that actually renders each event; injected via {@link #setDelegate}. */
    private Encoder<ILoggingEvent> delegate;

    /**
     * Injects the wrapped encoder. Called by Logback when it finishes configuring the nested
     * {@code <delegate>} element.
     *
     * @param delegate the encoder to wrap and sanitize the output of
     */
    public void setDelegate(Encoder<ILoggingEvent> delegate) {
        this.delegate = delegate;
    }

    /**
     * Returns the wrapped encoder (primarily for tests and diagnostics).
     *
     * @return the delegate encoder, or {@code null} if none has been configured
     */
    public Encoder<ILoggingEvent> getDelegate() {
        return delegate;
    }

    /**
     * Starts this encoder and its delegate. When Logback builds the nested {@code <delegate>} it
     * already assigns it the same {@link ch.qos.logback.core.Context} as this wrapper, so the
     * delegate's context is only populated here if it has none &mdash; this wrapper never clobbers a
     * context Logback already set (which would trip Logback's "context has been already set" guard).
     * Likewise the delegate is started only if it has not already been started, so a delegate that
     * Logback may have started on its own is not started twice. If no delegate was configured, an
     * error is reported to the Logback status system and the encoder is not marked started.
     */
    @Override
    public void start() {
        if (delegate == null) {
            addError("MaskingLogbackEncoder requires a nested <delegate> encoder; none was configured.");
            return;
        }
        if (delegate.getContext() == null) {
            delegate.setContext(getContext());
        }
        if (!delegate.isStarted()) {
            delegate.start();
        }
        super.start();
    }

    /**
     * Stops this encoder and its delegate (if started).
     */
    @Override
    public void stop() {
        if (delegate != null && delegate.isStarted()) {
            delegate.stop();
        }
        super.stop();
    }

    /**
     * Returns the delegate's header bytes, masked.
     *
     * @return the sanitized header bytes (empty when no delegate is configured)
     */
    @Override
    public byte[] headerBytes() {
        return (delegate == null) ? EMPTY : mask(delegate.headerBytes());
    }

    /**
     * Encodes {@code event} with the delegate and returns the sanitized bytes.
     *
     * @param event the logging event to encode
     * @return the delegate's encoded bytes with any card PAN redacted
     */
    @Override
    public byte[] encode(ILoggingEvent event) {
        return (delegate == null) ? EMPTY : mask(delegate.encode(event));
    }

    /**
     * Returns the delegate's footer bytes, masked.
     *
     * @return the sanitized footer bytes (empty when no delegate is configured)
     */
    @Override
    public byte[] footerBytes() {
        return (delegate == null) ? EMPTY : mask(delegate.footerBytes());
    }

    /**
     * Masks a chunk of encoded output. Decodes with ISO-8859-1, applies {@link SensitiveDataMasker},
     * and re-encodes only when the text actually changed.
     *
     * @param rendered the bytes produced by the delegate encoder; may be {@code null} or empty
     * @return the sanitized bytes, or the original array when nothing needed masking
     */
    private static byte[] mask(byte[] rendered) {
        if (rendered == null || rendered.length == 0) {
            return rendered;
        }
        String text = new String(rendered, StandardCharsets.ISO_8859_1);
        String masked = SensitiveDataMasker.mask(text);
        // SensitiveDataMasker returns the same instance when nothing was masked; skip re-encoding.
        if (masked == text) {
            return rendered;
        }
        return masked.getBytes(StandardCharsets.ISO_8859_1);
    }
}
