#!/usr/bin/env python3
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
"""Byte-extraction helper for CardDemo test fixtures.

Reads byte-exact records from app/data/ASCII/*.txt and emits COBOL
`MOVE X'..' TO field(start:len)` snippet .cpy files for inclusion in
cobol-check MOCK FILE .. ON READ blocks.

Pure byte extraction. NO domain logic.
"""
import argparse
import hashlib
from pathlib import Path

# (snippet, source_file, start_rec, count, rec_len, field, sep_size)
SNIPPETS = [
    ("ACCT-FIXTURE-001",        "acctdata.txt",  1,  1, 300, "ACCOUNT-RECORD",      1),
    ("CARD-FIXTURE-001",        "carddata.txt",  1,  1, 150, "CARD-RECORD",         1),
    ("CUST-FIXTURE-001",        "custdata.txt",  1,  1, 500, "CUSTOMER-RECORD",     1),
    ("XREF-FIXTURE-001",        "cardxref.txt",  1,  1,  36, "CARD-XREF-RECORD",    1),
    ("DALYTRAN-FIXTURE-001",    "dailytran.txt", 1,  1, 350, "DALYTRAN-RECORD",     1),
    ("DISCGRP-FIXTURE-A",       "discgrp.txt",   1, 17,  50, "DIS-GROUP-RECORD",    1),
    ("DISCGRP-FIXTURE-DEFAULT", "discgrp.txt",  18, 17,  50, "DIS-GROUP-RECORD",    1),
    ("TCATBAL-FIXTURE-001",     "tcatbal.txt",   1,  1,  50, "TRAN-CAT-BAL-RECORD", 1),
    ("TRANCATG-FIXTURE",        "trancatg.txt",  1, 18,  60, "TRAN-CAT-RECORD",     1),
    ("TRANTYPE-FIXTURE",        "trantype.txt",  1,  7,  60, "TRAN-TYPE-RECORD",    1),
]
BYTES_PER_MOVE = 24

def extract(input_dir, output_dir, only=None):
    for name, src, start, count, rlen, field, sep in SNIPPETS:
        if only and name != only:
            continue
        raw = (input_dir / src).read_bytes()
        recs = []
        for r in range(count):
            off = (start - 1 + r) * (rlen + sep)
            chunk = raw[off:off + rlen]
            if len(chunk) != rlen:
                raise SystemExit(f"{name}: {src} rec {start + r} short ({len(chunk)}/{rlen})")
            recs.append((start + r, off, chunk))
        write_snippet(output_dir, name, src, field, rlen, recs)

def write_snippet(out_dir, name, src, field, rlen, recs):
    sha = hashlib.sha256(b"".join(c for _, _, c in recs)).hexdigest()[:16]
    L = [
        "      *****************************************************************",
        f"      * Generated fixture: {name}",
        f"      * Source: app/data/ASCII/{src}",
        f"      * Records: {len(recs)} of {rlen} bytes each",
        f"      * SHA-256(payload, 64-bit prefix): {sha}",
        "      * Generated by tests/fixtures/load_fixture.py; do not hand-edit.",
        "      * Copyright Amazon.com, Inc. or its affiliates.",
        "      * SPDX-License-Identifier: Apache-2.0",
        "      *****************************************************************",
    ]
    # Build all MOVE pairs across all records first, then attach a
    # terminating period to the FINAL `TO <field>(start:len)` line so
    # the snippet's last sentence is properly terminated when the
    # snippet is expanded by COPY inside a procedure paragraph.
    #
    # Why the trailing period matters
    # -------------------------------
    # When a host paragraph contains:
    #     MOVE '00' TO WS-FIELD
    #     COPY ACCT-FIXTURE-001
    #     .
    # the standalone period on the line following the COPY directive
    # is consumed by the COBOL preprocessor as the COPY directive's
    # SYNTACTIC terminator, NOT as a sentence terminator inside the
    # paragraph.  After expansion, the merged source effectively
    # becomes:
    #     MOVE '00' TO WS-FIELD
    #     <expanded MOVE pairs from .cpy>     <-- no trailing period
    # leaving the paragraph's last sentence unterminated and the
    # following paragraph header (e.g. UT-1-3-1-MOCK.) merged into
    # it as a phantom identifier reference -- GnuCOBOL emits
    # "'UT-1-3-1-MOCK' is not defined".  Anchoring the period
    # inside the .cpy on the final TO-clause prevents this.
    move_lines = []
    for rec_num, off, chunk in recs:
        move_lines.append((True, f"      * Record #{rec_num} at byte offset {off}"))
        for i in range(0, rlen, BYTES_PER_MOVE):
            seg = chunk[i:i + BYTES_PER_MOVE]
            move_lines.append((False, f"           MOVE X'{seg.hex().upper()}'"))
            move_lines.append((False, f"             TO {field}({i + 1}:{len(seg)})"))
    # Append a period to the last non-comment line.
    for idx in range(len(move_lines) - 1, -1, -1):
        is_comment, text = move_lines[idx]
        if not is_comment:
            move_lines[idx] = (False, text + ".")
            break
    L.extend(text for _, text in move_lines)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / f"{name}.cpy").write_text("\n".join(L) + "\n")

def main():
    p = argparse.ArgumentParser(description="Extract byte-exact COBOL fixtures.")
    p.add_argument("--input-dir",  required=True, type=Path)
    p.add_argument("--output-dir", required=True, type=Path)
    p.add_argument("--fixture",    default=None, help="single snippet name; default all")
    a = p.parse_args()
    extract(a.input_dir, a.output_dir, a.fixture)

if __name__ == "__main__":
    main()
