#!/usr/bin/env python3
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
"""Byte-extraction helper for CardDemo test fixtures.

Reads byte-exact records from app/data/ASCII/*.txt and emits COBOL
`MOVE X'..' TO field(start:len)` snippet .cpy files for inclusion in
cobol-check MOCK FILE .. ON READ blocks.

Pure byte extraction. NO domain logic.
"""
import argparse
import hashlib
from pathlib import Path

# (snippet, source_file, start_rec, count, rec_len, field, sep_size)
SNIPPETS = [
    ("ACCT-FIXTURE-001",        "acctdata.txt",  1,  1, 300, "ACCOUNT-RECORD",      1),
    ("CARD-FIXTURE-001",        "carddata.txt",  1,  1, 150, "CARD-RECORD",         1),
    ("CUST-FIXTURE-001",        "custdata.txt",  1,  1, 500, "CUSTOMER-RECORD",     1),
    ("XREF-FIXTURE-001",        "cardxref.txt",  1,  1,  36, "CARD-XREF-RECORD",    1),
    ("DALYTRAN-FIXTURE-001",    "dailytran.txt", 1,  1, 350, "DALYTRAN-RECORD",     1),
    ("DISCGRP-FIXTURE-A",       "discgrp.txt",   1, 17,  50, "DIS-GROUP-RECORD",    1),
    ("DISCGRP-FIXTURE-DEFAULT", "discgrp.txt",  18, 17,  50, "DIS-GROUP-RECORD",    1),
    ("TCATBAL-FIXTURE-001",     "tcatbal.txt",   1,  1,  50, "TRAN-CAT-BAL-RECORD", 1),
    ("TRANCATG-FIXTURE",        "trancatg.txt",  1, 18,  60, "TRAN-CAT-RECORD",     1),
    ("TRANTYPE-FIXTURE",        "trantype.txt",  1,  7,  60, "TRAN-TYPE-RECORD",    1),
]
BYTES_PER_MOVE = 24

def extract(input_dir, output_dir, only=None):
    for name, src, start, count, rlen, field, sep in SNIPPETS:
        if only and name != only:
            continue
        raw = (input_dir / src).read_bytes()
        recs = []
        for r in range(count):
            off = (start - 1 + r) * (rlen + sep)
            chunk = raw[off:off + rlen]
            if len(chunk) != rlen:
                raise SystemExit(f"{name}: {src} rec {start + r} short ({len(chunk)}/{rlen})")
            recs.append((start + r, off, chunk))
        write_snippet(output_dir, name, src, field, rlen, recs)

def write_snippet(out_dir, name, src, field, rlen, recs):
    sha = hashlib.sha256(b"".join(c for _, _, c in recs)).hexdigest()[:16]
    L = [
        "      *****************************************************************",
        f"      * Generated fixture: {name}",
        f"      * Source: app/data/ASCII/{src}",
        f"      * Records: {len(recs)} of {rlen} bytes each",
        f"      * SHA-256(payload, 64-bit prefix): {sha}",
        "      * Generated by tests/fixtures/load_fixture.py; do not hand-edit.",
        "      * Copyright Amazon.com, Inc. or its affiliates.",
        "      * SPDX-License-Identifier: Apache-2.0",
        "      *****************************************************************",
    ]
    for rec_num, off, chunk in recs:
        L.append(f"      * Record #{rec_num} at byte offset {off}")
        for i in range(0, rlen, BYTES_PER_MOVE):
            seg = chunk[i:i + BYTES_PER_MOVE]
            L.append(f"           MOVE X'{seg.hex().upper()}'")
            L.append(f"             TO {field}({i + 1}:{len(seg)})")
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / f"{name}.cpy").write_text("\n".join(L) + "\n")

def main():
    p = argparse.ArgumentParser(description="Extract byte-exact COBOL fixtures.")
    p.add_argument("--input-dir",  required=True, type=Path)
    p.add_argument("--output-dir", required=True, type=Path)
    p.add_argument("--fixture",    default=None, help="single snippet name; default all")
    a = p.parse_args()
    extract(a.input_dir, a.output_dir, a.fixture)

if __name__ == "__main__":
    main()
