package com.carddemo.repository;

import com.carddemo.entity.Transaction;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * Spring Data JPA repository for the {@link Transaction} entity &mdash; the
 * data-access boundary for the relational {@code transactions} table.
 *
 * <h2>Source of truth &amp; what this replaces</h2>
 * <p>The {@code transactions} table is the relational re-expression of the legacy
 * VSAM {@code TRANSACT} KSDS, whose record layout is defined by the COBOL copybook
 * {@code app/cpy/CVTRA05Y.cpy} ({@code TRAN-RECORD}, record length 350, carrying both
 * {@code TRAN-ORIG-TS} and {@code TRAN-PROC-TS}). This repository abstracts every
 * access path the legacy online programs used against that dataset, replacing the
 * CICS/VSAM file operations with idiomatic Spring Data JPA:</p>
 * <ul>
 *   <li><b>List Transactions ({@code COTRN00C}).</b> The screen browsed the
 *       {@code TRANSACT.AIX} alternate index by account in origination-timestamp
 *       order via {@code STARTBR}/{@code READNEXT} (and {@code READPREV} for paging
 *       back). That browse is replaced by the paginated, ordered derived query
 *       {@link #findByAcctIdOrderByOrigTs(Long, Pageable)}.</li>
 *   <li><b>View Transaction ({@code COTRN01C}).</b> The single-record {@code READ}
 *       by transaction id is served by the inherited
 *       {@link JpaRepository#findById(Object) findById(String tranId)}.</li>
 *   <li><b>Add Transaction ({@code COTRN02C}).</b> Insertion is served by the
 *       inherited {@link JpaRepository#save(Object) save(Transaction)}. The legacy
 *       {@code STARTBR}/{@code READPREV} next-id scheme is <em>not</em> reproduced
 *       here: the 16-character, zero-padded {@code tran_id} is generated by
 *       {@code com.carddemo.util.TranIdGenerator} (PostgreSQL {@code transaction_id_seq}
 *       + {@code LPAD}) in the service layer, so this repository performs no
 *       id-generation, date validation, or other business logic.</li>
 * </ul>
 *
 * <h2>Identifier type</h2>
 * <p>The entity declares {@code @Id private String tranId} (column
 * {@code tran_id VARCHAR(16)}); the repository's id type is therefore
 * {@link String}.</p>
 *
 * <h2>Pagination convention (page size 7)</h2>
 * <p>The legacy 3270 list screen displayed a fixed page of <strong>seven</strong>
 * rows. To preserve that behavior with 100% parity, callers (the
 * {@code TransactionService}) MUST build their {@link Pageable} as
 * {@code PageRequest.of(pageNumber, 7)}. The page size is intentionally
 * <em>not</em> hard-coded in this repository &mdash; the repository accepts only a
 * {@link Pageable} and leaves the size-7 decision to the caller, keeping the
 * data-access layer free of presentation concerns.</p>
 *
 * <p>No {@code @Repository} stereotype is declared: Spring Data automatically
 * detects and provides a proxy implementation for interfaces extending
 * {@link JpaRepository}.</p>
 *
 * @see Transaction
 * @see JpaRepository
 */
public interface TransactionRepository extends JpaRepository<Transaction, String> {

    /**
     * Returns a page of transactions belonging to a single account, ordered by
     * origination timestamp (ascending).
     *
     * <p>This derived query reproduces the {@code COTRN00C} "List Transactions"
     * browse, which walked the VSAM {@code TRANSACT.AIX} alternate index by account
     * in origination-timestamp order using {@code STARTBR}/{@code READNEXT}. The
     * generated SQL filters on the {@code acct_id} column and orders by the
     * {@code orig_ts} column, and is index-supported by the V1 composite index
     * {@code idx_transactions_acct_id_orig_ts (acct_id, orig_ts)} &mdash; the index
     * column order matches the filter-then-order clause, so no extra sort is
     * required.</p>
     *
     * <p>The query resolves against the entity properties {@code acctId}
     * (denormalized scalar account foreign key, {@link Long}) and {@code origTs}
     * ({@link java.time.LocalDateTime} origination timestamp).</p>
     *
     * <p>Returning a {@link Page} supplies the total element count and the
     * has-next/has-previous flags that reproduce {@code COTRN00C}'s forward and
     * backward paging indicators. Callers pass {@code PageRequest.of(pageNumber, 7)}
     * to honor the legacy fixed page size of seven rows.</p>
     *
     * @param acctId   the owning account identifier to filter transactions by;
     *                 matches the {@code acct_id} column
     * @param pageable the pagination request supplied by the caller, conventionally
     *                 {@code PageRequest.of(pageNumber, 7)}; must not be {@code null}
     * @return a {@link Page} of {@link Transaction} rows for the account, ordered by
     *         origination timestamp ascending; never {@code null} (an empty page is
     *         returned when the account has no transactions or the page is beyond the
     *         available rows)
     */
    Page<Transaction> findByAcctIdOrderByOrigTs(Long acctId, Pageable pageable);
}
