/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.aws.carddemo.domain;

import java.math.BigDecimal;
import java.util.Objects;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity mapping the legacy COBOL copybook {@code TRAN-RECORD}
 * (source {@code legacy/cpy/CVTRA05Y.cpy}, fixed record length 350) to the
 * relational table {@code transaction}.
 *
 * <p>This is the posted-transaction master. Its natural primary key is the
 * 16-character {@code tran_id}, which is generated by the application (never a
 * database identity), and the monetary {@code tran_amt} is modeled as a
 * {@link java.math.BigDecimal} at scale 2 to preserve the COBOL
 * {@code PIC S9(09)V99} packed-decimal semantics exactly. Binary
 * floating-point types ({@code double}/{@code float}) are never used for
 * monetary values.</p>
 *
 * <p>The relational schema is owned and created by Flyway
 * ({@code V1__schema.sql}); Hibernate runs with {@code ddl-auto: validate}, so
 * every column name, type, length and decimal precision/scale declared here
 * must match that DDL exactly. The foreign keys ({@code card_num} &rarr;
 * {@code card}, {@code type_cd} &rarr; {@code transaction_type}, and the
 * composite {@code (type_cd, cat_cd)} &rarr; {@code transaction_category}) and
 * the chronological-retrieval index over {@code orig_ts}
 * ({@code idx_transaction_orig_ts}, derived from the legacy VSAM alternate
 * index) are defined by that migration. The corresponding fields are therefore
 * kept as plain scalar columns rather than JPA associations, keeping the entity
 * a faithful one-to-one projection of the copybook record.</p>
 *
 * <p>Field order follows the copybook. The two timestamp fields preserve the
 * legacy text contract ({@code PIC X(26)}, format
 * {@code YYYY-MM-DD-HH.MM.SS.ffffff}) and are mapped as {@code String}, not
 * {@code java.time} types. The trailing {@code FILLER PIC X(20)} is layout
 * padding only and is intentionally not mapped.</p>
 *
 * @see <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License 2.0</a>
 */
@Entity
@Table(name = "transaction")
public class Transaction {

    /** {@code TRAN-ID PIC X(16)} &mdash; natural primary key (application-generated). */
    @Id
    @Column(name = "tran_id", length = 16, nullable = false)
    private String tranId;

    /** {@code TRAN-TYPE-CD PIC X(02)} &mdash; scalar FK to {@code transaction_type}; part of composite FK. */
    @Column(name = "type_cd", length = 2, nullable = false)
    private String typeCd;

    /** {@code TRAN-CAT-CD PIC 9(04)} &mdash; part of the composite FK to {@code transaction_category}. */
    @Column(name = "cat_cd", nullable = false)
    private Integer catCd;

    /** {@code TRAN-SOURCE PIC X(10)} &mdash; origination source of the transaction. */
    @Column(name = "tran_source", length = 10)
    private String tranSource;

    /** {@code TRAN-DESC PIC X(100)} &mdash; free-form transaction description. */
    @Column(name = "tran_desc", length = 100)
    private String tranDesc;

    /** {@code TRAN-AMT PIC S9(09)V99} &mdash; signed monetary amount; {@code DECIMAL(11,2)}. */
    @Column(name = "tran_amt", precision = 11, scale = 2)
    private BigDecimal tranAmt;

    /** {@code TRAN-MERCHANT-ID PIC 9(09)} &mdash; merchant identifier; {@code BIGINT}. */
    @Column(name = "tran_merchant_id")
    private Long tranMerchantId;

    /** {@code TRAN-MERCHANT-NAME PIC X(50)} &mdash; merchant name. */
    @Column(name = "tran_merchant_name", length = 50)
    private String tranMerchantName;

    /** {@code TRAN-MERCHANT-CITY PIC X(50)} &mdash; merchant city. */
    @Column(name = "tran_merchant_city", length = 50)
    private String tranMerchantCity;

    /** {@code TRAN-MERCHANT-ZIP PIC X(10)} &mdash; merchant postal code. */
    @Column(name = "tran_merchant_zip", length = 10)
    private String tranMerchantZip;

    /** {@code TRAN-CARD-NUM PIC X(16)} &mdash; scalar FK to {@code card}. */
    @Column(name = "card_num", length = 16, nullable = false)
    private String cardNum;

    /**
     * {@code TRAN-ORIG-TS PIC X(26)} &mdash; origination timestamp preserved as
     * text ({@code YYYY-MM-DD-HH.MM.SS.ffffff}); backed by
     * {@code idx_transaction_orig_ts} for chronological retrieval.
     */
    @Column(name = "orig_ts", length = 26)
    private String origTs;

    /**
     * {@code TRAN-PROC-TS PIC X(26)} &mdash; processing timestamp preserved as
     * text ({@code YYYY-MM-DD-HH.MM.SS.ffffff}).
     */
    @Column(name = "proc_ts", length = 26)
    private String procTs;

    /**
     * Protected no-argument constructor required by the JPA provider.
     *
     * <p>Not intended for direct use by application code; use the all-arguments
     * constructor or the setters to populate a new instance.</p>
     */
    protected Transaction() {
        // Required by the JPA specification for entity instantiation.
    }

    /**
     * Creates a fully-populated transaction record. Every parameter maps
     * one-to-one, in declaration order, to a field of the {@code TRAN-RECORD}
     * copybook.
     *
     * @param tranId           16-character natural primary key
     * @param typeCd           transaction type code (scalar FK)
     * @param catCd            transaction category code (part of composite FK)
     * @param tranSource       origination source
     * @param tranDesc         transaction description
     * @param tranAmt          signed monetary amount (scale 2)
     * @param tranMerchantId   merchant identifier
     * @param tranMerchantName merchant name
     * @param tranMerchantCity merchant city
     * @param tranMerchantZip  merchant postal code
     * @param cardNum          card number (scalar FK)
     * @param origTs           origination timestamp text
     * @param procTs           processing timestamp text
     */
    public Transaction(String tranId,
                        String typeCd,
                        Integer catCd,
                        String tranSource,
                        String tranDesc,
                        BigDecimal tranAmt,
                        Long tranMerchantId,
                        String tranMerchantName,
                        String tranMerchantCity,
                        String tranMerchantZip,
                        String cardNum,
                        String origTs,
                        String procTs) {
        this.tranId = tranId;
        this.typeCd = typeCd;
        this.catCd = catCd;
        this.tranSource = tranSource;
        this.tranDesc = tranDesc;
        this.tranAmt = tranAmt;
        this.tranMerchantId = tranMerchantId;
        this.tranMerchantName = tranMerchantName;
        this.tranMerchantCity = tranMerchantCity;
        this.tranMerchantZip = tranMerchantZip;
        this.cardNum = cardNum;
        this.origTs = origTs;
        this.procTs = procTs;
    }

    /**
     * Returns the 16-character transaction identifier (primary key).
     *
     * @return the transaction id
     */
    public String getTranId() {
        return tranId;
    }

    /**
     * Sets the 16-character transaction identifier (primary key).
     *
     * @param tranId the transaction id
     */
    public void setTranId(String tranId) {
        this.tranId = tranId;
    }

    /**
     * Returns the transaction type code (scalar FK to {@code transaction_type}).
     *
     * @return the transaction type code
     */
    public String getTypeCd() {
        return typeCd;
    }

    /**
     * Sets the transaction type code (scalar FK to {@code transaction_type}).
     *
     * @param typeCd the transaction type code
     */
    public void setTypeCd(String typeCd) {
        this.typeCd = typeCd;
    }

    /**
     * Returns the transaction category code (part of the composite FK to
     * {@code transaction_category}).
     *
     * @return the transaction category code
     */
    public Integer getCatCd() {
        return catCd;
    }

    /**
     * Sets the transaction category code (part of the composite FK to
     * {@code transaction_category}).
     *
     * @param catCd the transaction category code
     */
    public void setCatCd(Integer catCd) {
        this.catCd = catCd;
    }

    /**
     * Returns the origination source of the transaction.
     *
     * @return the transaction source
     */
    public String getTranSource() {
        return tranSource;
    }

    /**
     * Sets the origination source of the transaction.
     *
     * @param tranSource the transaction source
     */
    public void setTranSource(String tranSource) {
        this.tranSource = tranSource;
    }

    /**
     * Returns the free-form transaction description.
     *
     * @return the transaction description
     */
    public String getTranDesc() {
        return tranDesc;
    }

    /**
     * Sets the free-form transaction description.
     *
     * @param tranDesc the transaction description
     */
    public void setTranDesc(String tranDesc) {
        this.tranDesc = tranDesc;
    }

    /**
     * Returns the signed monetary amount at scale 2.
     *
     * @return the transaction amount
     */
    public BigDecimal getTranAmt() {
        return tranAmt;
    }

    /**
     * Sets the signed monetary amount. Callers are responsible for supplying a
     * value at scale 2 to match the {@code DECIMAL(11,2)} column.
     *
     * @param tranAmt the transaction amount
     */
    public void setTranAmt(BigDecimal tranAmt) {
        this.tranAmt = tranAmt;
    }

    /**
     * Returns the merchant identifier.
     *
     * @return the merchant id
     */
    public Long getTranMerchantId() {
        return tranMerchantId;
    }

    /**
     * Sets the merchant identifier.
     *
     * @param tranMerchantId the merchant id
     */
    public void setTranMerchantId(Long tranMerchantId) {
        this.tranMerchantId = tranMerchantId;
    }

    /**
     * Returns the merchant name.
     *
     * @return the merchant name
     */
    public String getTranMerchantName() {
        return tranMerchantName;
    }

    /**
     * Sets the merchant name.
     *
     * @param tranMerchantName the merchant name
     */
    public void setTranMerchantName(String tranMerchantName) {
        this.tranMerchantName = tranMerchantName;
    }

    /**
     * Returns the merchant city.
     *
     * @return the merchant city
     */
    public String getTranMerchantCity() {
        return tranMerchantCity;
    }

    /**
     * Sets the merchant city.
     *
     * @param tranMerchantCity the merchant city
     */
    public void setTranMerchantCity(String tranMerchantCity) {
        this.tranMerchantCity = tranMerchantCity;
    }

    /**
     * Returns the merchant postal code.
     *
     * @return the merchant zip
     */
    public String getTranMerchantZip() {
        return tranMerchantZip;
    }

    /**
     * Sets the merchant postal code.
     *
     * @param tranMerchantZip the merchant zip
     */
    public void setTranMerchantZip(String tranMerchantZip) {
        this.tranMerchantZip = tranMerchantZip;
    }

    /**
     * Returns the card number (scalar FK to {@code card}).
     *
     * @return the card number
     */
    public String getCardNum() {
        return cardNum;
    }

    /**
     * Sets the card number (scalar FK to {@code card}).
     *
     * @param cardNum the card number
     */
    public void setCardNum(String cardNum) {
        this.cardNum = cardNum;
    }

    /**
     * Returns the origination timestamp text ({@code YYYY-MM-DD-HH.MM.SS.ffffff}).
     *
     * @return the origination timestamp text
     */
    public String getOrigTs() {
        return origTs;
    }

    /**
     * Sets the origination timestamp text ({@code YYYY-MM-DD-HH.MM.SS.ffffff}).
     *
     * @param origTs the origination timestamp text
     */
    public void setOrigTs(String origTs) {
        this.origTs = origTs;
    }

    /**
     * Returns the processing timestamp text ({@code YYYY-MM-DD-HH.MM.SS.ffffff}).
     *
     * @return the processing timestamp text
     */
    public String getProcTs() {
        return procTs;
    }

    /**
     * Sets the processing timestamp text ({@code YYYY-MM-DD-HH.MM.SS.ffffff}).
     *
     * @param procTs the processing timestamp text
     */
    public void setProcTs(String procTs) {
        this.procTs = procTs;
    }

    /**
     * Two transactions are considered equal when they share the same
     * {@code tranId}, which is the natural primary key.
     *
     * @param o the reference object with which to compare
     * @return {@code true} if this object is the same as {@code o}
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Transaction other)) {
            return false;
        }
        return Objects.equals(tranId, other.tranId);
    }

    /**
     * Returns a hash code consistent with {@link #equals(Object)}, derived
     * solely from the {@code tranId} primary key.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {
        return Objects.hashCode(tranId);
    }

    /**
     * Returns a diagnostic representation of this transaction.
     *
     * <p>The full card number is deliberately excluded to avoid exposing a
     * primary account number (PAN) in logs; merchant details, the amount and
     * the timestamps are safe to render.</p>
     *
     * @return a string representation excluding the card number
     */
    @Override
    public String toString() {
        return "Transaction{"
                + "tranId='" + tranId + '\''
                + ", typeCd='" + typeCd + '\''
                + ", catCd=" + catCd
                + ", tranSource='" + tranSource + '\''
                + ", tranDesc='" + tranDesc + '\''
                + ", tranAmt=" + tranAmt
                + ", tranMerchantId=" + tranMerchantId
                + ", tranMerchantName='" + tranMerchantName + '\''
                + ", tranMerchantCity='" + tranMerchantCity + '\''
                + ", tranMerchantZip='" + tranMerchantZip + '\''
                + ", origTs='" + origTs + '\''
                + ", procTs='" + procTs + '\''
                + '}';
    }
}
