/*
 * Copyright Amazon.com, Inc. or its affiliates.
 * All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 */
package com.carddemo.dto.card;

import io.swagger.v3.oas.annotations.media.Schema;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Positive;
import jakarta.validation.constraints.Size;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Card Data Transfer Object — mirrors the COBOL {@code CVACT02Y} 150-byte
 * {@code CARD-RECORD} layout for the card management REST API.
 *
 * <p><strong>Endpoints:</strong></p>
 * <ul>
 *   <li>{@code GET /api/cards/{cardNum}} — single card view (response body)</li>
 *   <li>{@code GET /api/accounts/{acctId}/cards} — paginated card list
 *       (wrapped in {@code CardListResponse.content})</li>
 *   <li>{@code PUT /api/cards/{cardNum}} — card update (request body, same DTO reused)</li>
 * </ul>
 *
 * <p><strong>Mapping reference:</strong> Mirrors the 150-byte {@code CARD-RECORD}
 * from {@code app/cpy/CVACT02Y.cpy} (6 user fields + 59-byte FILLER —
 * FILLER is NOT exposed).</p>
 *
 * <p><strong>Field name reconciliation:</strong> The {@code Card} JPA entity uses
 * field {@code cvvCd} (shortened convention) while this DTO uses {@code cvvCode}
 * (full English word for API clarity). The {@code CardMapper} handles the
 * field-name translation between DTO and entity. Mirrors the pattern used in
 * {@code TransactionDto.cardNumber} ↔ {@code Transaction.cardNum}.</p>
 *
 * <p><strong>PR-13 (Field length fidelity):</strong> Each {@code @Size}
 * annotation maximum matches the COBOL PIC clause length exactly. The 59-byte
 * FILLER from CVACT02Y is intentionally NOT exposed.</p>
 *
 * <p><strong>PR-14 (Typo correction):</strong> The original COBOL field
 * {@code CARD-EXPIRAION-DATE} (misspelled "EXPIRAION") is corrected here to
 * {@code expirationDate} (proper English spelling). The PostgreSQL column
 * remains {@code expiration_date} (snake_case Java convention).</p>
 *
 * <p><strong>CVV handling:</strong> The {@code cvvCode} field is stored as
 * {@code String} (NOT {@code Integer}) to preserve leading zeros such as
 * "007". This mirrors the COBOL {@code PIC 9(03)} fixed-width semantics where
 * leading zeros are significant for the on-wire/on-disk representation.</p>
 *
 * <p><strong>BMS split-entry NOT preserved:</strong> The original BMS update
 * screen ({@code COCRDUP}) split the expiration date into three separate
 * fields: {@code EXPMON X(2)}, {@code EXPDAY X(2)}, {@code EXPYEAR X(4)}.
 * The REST API consolidates these into a single {@code expirationDate} String
 * in {@code yyyy-MM-dd} format. Clients are responsible for assembling
 * year/month/day inputs into the ISO-8601 date string.</p>
 *
 * <p><strong>No PII masking:</strong> Unlike {@code CustomerDto.ssn},
 * the Card entity has no PII fields requiring transformation in the mapper.
 * All fields are exposed verbatim.</p>
 *
 * <p>This is a plain POJO with no dependency on the entity, repository, or
 * service layers (DTO decoupling): it carries no {@code com.carddemo.*} imports
 * and no JPA / persistence annotations. Boilerplate (getters, setters,
 * {@code equals}/{@code hashCode}/{@code toString}, all-args + no-args
 * constructors, and the fluent {@code builder()}) is generated by Lombok; the
 * no-args constructor additionally supports Jackson (de)serialization.</p>
 *
 * @see com.carddemo.entity.Card
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(
    description = "Card DTO mirroring COBOL CVACT02Y 150-byte CARD-RECORD. "
        + "Used as the response payload for GET /api/cards/{cardNum} (single view), "
        + "as the content element type for paginated GET /api/accounts/{acctId}/cards list responses, "
        + "and as the request body for PUT /api/cards/{cardNum} (update). "
        + "The 59-byte FILLER from CVACT02Y is intentionally NOT exposed. "
        + "The CVV is stored as String to preserve leading zeros (e.g., \"007\"). "
        + "COBOL field CARD-EXPIRAION-DATE (misspelled) is corrected to expirationDate per PR-14."
)
public class CardDto {

    /**
     * Card number — maps COBOL {@code CARD-NUM PIC X(16)}.
     * 16-digit numeric string. Primary key in the {@code cards} table.
     * <p>Format: 16 numeric digits (no spaces, no dashes).</p>
     * <p>Example: {@code "4111111111111111"}.</p>
     */
    @NotBlank(message = "Card number is required")
    @Size(min = 16, max = 16, message = "Card number must be exactly 16 characters")
    @Pattern(regexp = "\\d{16}", message = "Card number must contain exactly 16 digits")
    @Schema(
        description = "16-digit card number — primary identifier. Maps COBOL CARD-NUM PIC X(16).",
        example = "4111111111111111",
        minLength = 16,
        maxLength = 16,
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    private String cardNum;

    /**
     * Account ID — maps COBOL {@code CARD-ACCT-ID PIC 9(11)}.
     * 11-digit numeric account identifier. Foreign key to the {@code accounts} table.
     * <p>The {@code Card} entity has {@code @Index(idx_card_account_id)} on this
     * column, replacing the original VSAM {@code CARDDATA.AIX} alternate index
     * per AAP §0.6.13.</p>
     */
    @NotNull(message = "Account ID is required")
    @Positive(message = "Account ID must be positive")
    @Max(value = 99_999_999_999L, message = "Account ID must not exceed 11 digits")
    @Schema(
        description = "11-digit account ID (foreign key to accounts table). Maps COBOL CARD-ACCT-ID PIC 9(11). "
            + "Indexed via @Index(idx_card_account_id) on the Card entity (replaces VSAM CARDDATA.AIX).",
        example = "10000000001",
        requiredMode = Schema.RequiredMode.REQUIRED
    )
    private Long accountId;

    /**
     * Card Verification Value (CVV) — maps COBOL {@code CARD-CVV-CD PIC 9(03)}.
     * 3-digit numeric security code printed on the back of the card.
     * <p><strong>Stored as {@code String} (NOT {@code Integer}) to preserve
     * leading zeros</strong> such as "007". This mirrors the COBOL
     * {@code PIC 9(03)} fixed-width semantics where leading zeros are significant.</p>
     * <p><strong>Entity field name discrepancy:</strong> The {@code Card} entity
     * uses field name {@code cvvCd} (shortened); the {@code CardMapper} translates
     * between this DTO field {@code cvvCode} and the entity field {@code cvvCd}.</p>
     */
    @Size(min = 3, max = 3, message = "CVV must be exactly 3 digits")
    @Pattern(regexp = "\\d{3}", message = "CVV must contain exactly 3 digits")
    @Schema(
        description = "3-digit card verification value (CVV). Maps COBOL CARD-CVV-CD PIC 9(03). "
            + "Stored as String to preserve leading zeros (e.g., \"007\"). "
            + "Entity field is named cvvCd (mapper handles translation).",
        example = "123",
        minLength = 3,
        maxLength = 3,
        requiredMode = Schema.RequiredMode.NOT_REQUIRED,
        nullable = true
    )
    private String cvvCode;

    /**
     * Embossed cardholder name — maps COBOL {@code CARD-EMBOSSED-NAME PIC X(50)}.
     * The name as it appears physically embossed on the card (up to 50 chars).
     */
    @Size(max = 50, message = "Embossed name must not exceed 50 characters")
    @Schema(
        description = "Cardholder name as embossed on the card (max 50 chars). Maps COBOL CARD-EMBOSSED-NAME PIC X(50).",
        example = "JOHN Q SMITH",
        maxLength = 50,
        requiredMode = Schema.RequiredMode.NOT_REQUIRED,
        nullable = true
    )
    private String embossedName;

    /**
     * Card expiration date in ISO {@code yyyy-MM-dd} format — maps COBOL
     * {@code CARD-EXPIRAION-DATE PIC X(10)}.
     * <p><strong>PR-14 typo correction:</strong> The original COBOL field name is
     * misspelled as {@code CARD-EXPIRAION-DATE} (should be EXPIRATION). The Java
     * field uses the proper English spelling {@code expirationDate}.</p>
     * <p><strong>BMS split-entry NOT preserved:</strong> The original BMS update
     * screen split this into {@code EXPMON X(2)}, {@code EXPDAY X(2)},
     * {@code EXPYEAR X(4)}. The REST API takes a single ISO-8601 date string.</p>
     */
    @Size(min = 10, max = 10, message = "Expiration date must be exactly 10 characters (yyyy-MM-dd)")
    @Pattern(
        regexp = "\\d{4}-\\d{2}-\\d{2}",
        message = "Expiration date must match yyyy-MM-dd format"
    )
    @Schema(
        description = "Card expiration date in ISO yyyy-MM-dd format (10 chars). "
            + "Maps COBOL CARD-EXPIRAION-DATE PIC X(10) (PR-14 typo correction). "
            + "BMS COCRDUP split-entry (EXPMON+EXPDAY+EXPYEAR) is NOT preserved — single ISO string.",
        example = "2026-12-31",
        minLength = 10,
        maxLength = 10,
        requiredMode = Schema.RequiredMode.NOT_REQUIRED,
        nullable = true
    )
    private String expirationDate;

    /**
     * Card active status flag — maps COBOL {@code CARD-ACTIVE-STATUS PIC X(01)}.
     * Single character: {@code Y} (active) or {@code N} (inactive).
     */
    @Size(min = 1, max = 1, message = "Active status must be exactly 1 character")
    @Pattern(regexp = "[YN]", message = "Active status must be Y or N")
    @Schema(
        description = "Card active status: Y (active) or N (inactive). Maps COBOL CARD-ACTIVE-STATUS PIC X(01).",
        example = "Y",
        allowableValues = {"Y", "N"},
        minLength = 1,
        maxLength = 1,
        requiredMode = Schema.RequiredMode.NOT_REQUIRED,
        nullable = true
    )
    private String activeStatus;
}
