/*
 * StatementFileWriter.java — Spring Batch ItemWriter for Statement Output
 *
 * Source COBOL Program: CBSTM03B.CBL (I/O subroutine)
 *   Function: Write statement records to STMT-FILE (plain text PIC X(80))
 *             and HTML-FILE (HTML PIC X(100))
 *
 * Migration Strategy:
 *   The COBOL subroutine CBSTM03B handles I/O for statement generation,
 *   including writes to two output files (STMT-FILE and HTML-FILE).
 *   In Spring Batch, the writer receives StatementData objects from
 *   StatementProcessor and writes both plain-text and HTML files to
 *   an output directory specified via job parameters.
 *
 * COBOL Paragraph → Java Method Traceability:
 *   5000-STMTFILE-WRITE  → write() — plain-text file output
 *   6000-HTMLFILE-WRITE  → write() — HTML file output
 *   OPEN OUTPUT STMT-FILE → output directory creation
 *   CLOSE STMT-FILE      → automatic via try-with-resources
 *
 * Ver: CardDemo_v1.0 — Migrated from COBOL to Java 25 + Spring Boot 3.5.x
 */
package com.cardemo.batch.writer;

import com.cardemo.batch.processor.StatementProcessor.StatementData;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.batch.core.StepExecution;
import org.springframework.batch.core.annotation.BeforeStep;
import org.springframework.batch.item.Chunk;
import org.springframework.batch.item.ItemWriter;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Spring Batch {@link ItemWriter} that writes generated statement data to
 * both plain-text and HTML output files. Translates the COBOL CBSTM03B.CBL
 * file I/O operations for STMT-FILE and HTML-FILE.
 *
 * <p>Each {@link StatementData} item contains pre-formatted plain-text and
 * HTML statement content generated by
 * {@link com.cardemo.batch.processor.StatementProcessor}. This writer
 * persists those strings to files in the output directory specified via
 * the {@code outputDir} job parameter.</p>
 *
 * <p><strong>File Naming Convention:</strong></p>
 * <ul>
 *   <li>Plain text: {@code statement_NNNN.txt} (← STMT-FILE)</li>
 *   <li>HTML: {@code statement_NNNN.html} (← HTML-FILE)</li>
 * </ul>
 * where NNNN is a zero-padded sequential counter.
 *
 * <p><strong>Thread Safety:</strong> The {@code AtomicInteger} counter
 * ensures safe concurrent writes if the step is configured for
 * multi-threaded execution.</p>
 *
 * @see StatementData the input item from StatementProcessor
 * @see com.cardemo.batch.processor.StatementProcessor
 */
public class StatementFileWriter implements ItemWriter<StatementData> {

    private static final Logger log = LoggerFactory.getLogger(StatementFileWriter.class);

    /** Atomic counter for unique file naming across chunks. */
    private final AtomicInteger fileCounter = new AtomicInteger(0);

    /** Output directory path, populated from job parameters before step execution. */
    private Path outputDir;

    /**
     * Captures the output directory from job parameters before the step begins.
     * The {@code outputDir} parameter is required and must point to a writable
     * directory (or a path that can be created).
     *
     * <p>Translates COBOL {@code OPEN OUTPUT STMT-FILE} and
     * {@code OPEN OUTPUT HTML-FILE} — the output destination is determined
     * at job launch time rather than compile time.</p>
     *
     * @param stepExecution the step execution context containing job parameters
     */
    @BeforeStep
    public void beforeStep(StepExecution stepExecution) {
        String outputDirParam = stepExecution.getJobParameters().getString("outputDir");
        if (outputDirParam == null || outputDirParam.isBlank()) {
            outputDirParam = System.getProperty("java.io.tmpdir");
            log.warn("No outputDir job parameter specified, defaulting to: {}", outputDirParam);
        }
        this.outputDir = Path.of(outputDirParam);
        log.info("Statement output directory: {}", this.outputDir);
    }

    /**
     * Writes a chunk of statement data to plain-text and HTML files.
     *
     * <p>For each {@link StatementData} item in the chunk:</p>
     * <ol>
     *   <li>Ensures the output directory exists (creates if necessary)</li>
     *   <li>Writes the plain-text statement to {@code statement_NNNN.txt}
     *       (← COBOL 5000-STMTFILE-WRITE)</li>
     *   <li>Writes the HTML statement to {@code statement_NNNN.html}
     *       (← COBOL 6000-HTMLFILE-WRITE)</li>
     *   <li>Logs completion at info level (replacing COBOL DISPLAY)</li>
     * </ol>
     *
     * @param chunk the chunk of StatementData items to write
     * @throws IOException if file creation or writing fails
     */
    @Override
    public void write(Chunk<? extends StatementData> chunk) throws Exception {
        if (outputDir == null) {
            throw new IllegalStateException("Output directory not initialized — "
                    + "ensure @BeforeStep was invoked with outputDir job parameter");
        }

        // Ensure output directory exists (← OPEN OUTPUT equivalent)
        Files.createDirectories(outputDir);

        for (StatementData data : chunk) {
            int seq = fileCounter.incrementAndGet();
            String seqStr = String.format("%04d", seq);

            // Write plain-text statement (← STMT-FILE, PIC X(80) lines)
            Path txtPath = outputDir.resolve("statement_" + seqStr + ".txt");
            String plainText = data.getPlainTextStatement();
            if (plainText != null && !plainText.isEmpty()) {
                Files.writeString(txtPath, plainText, StandardCharsets.UTF_8,
                        StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
                log.info("STMT-FILE written: {} ({} bytes)", txtPath.getFileName(),
                        plainText.length());
            }

            // Write HTML statement (← HTML-FILE, PIC X(100) lines)
            Path htmlPath = outputDir.resolve("statement_" + seqStr + ".html");
            String htmlContent = data.getHtmlStatement();
            if (htmlContent != null && !htmlContent.isEmpty()) {
                Files.writeString(htmlPath, htmlContent, StandardCharsets.UTF_8,
                        StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
                log.info("HTML-FILE written: {} ({} bytes)", htmlPath.getFileName(),
                        htmlContent.length());
            }

            log.info("Statement #{}: account={}, card={}, txns={}, total={}",
                    seq, data.getAccountId(), maskCard(data.getCardNumber()),
                    data.getTransactionLines() != null ? data.getTransactionLines().size() : 0,
                    data.getTotalAmount());
        }
    }

    /**
     * Masks card number for secure logging — shows only last 4 digits.
     *
     * @param cardNumber full card number
     * @return masked representation
     */
    private String maskCard(String cardNumber) {
        if (cardNumber == null || cardNumber.length() < 4) {
            return "****";
        }
        return "****" + cardNumber.substring(cardNumber.length() - 4);
    }
}
