import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  Index,
} from 'typeorm';

/**
 * Audit operation status enum.
 * 
 * Values:
 * - SUCCESS: Operation completed successfully
 * - FAILURE: Operation failed completely
 * - PARTIAL: Operation completed with partial success or warnings
 */
export enum AuditStatus {
  SUCCESS = 'success',
  FAILURE = 'failure',
  PARTIAL = 'partial',
}

/**
 * AuditLog entity for comprehensive audit trail recording.
 * 
 * Purpose:
 * - Track all significant operations in the OCR Processing Application
 * - Support SOC 2 Type II compliance with comprehensive audit logging
 * - Enable GDPR Article 30 record of processing activities
 * - Facilitate security monitoring and forensic analysis
 * - Provide data modification history for compliance
 * 
 * Features:
 * - Multi-tenant isolation via account_id
 * - Immutable records (insert-only, no updates or deletes)
 * - Comprehensive metadata capture (IP, user agent, old/new values)
 * - Status tracking (success, failure, partial)
 * - JSONB storage for flexible old_values, new_values, and metadata
 * - Indexed columns for efficient querying
 * - 7-year default retention policy
 * 
 * Audit Log Types:
 * - Authentication: user.login, user.logout, user.mfa, user.password_reset
 * - User Management: user.create, user.update, user.delete, user.role_assign
 * - Documents: document.upload, document.process, document.approve, document.reject, document.export, document.delete
 * - Templates: template.create, template.update, template.delete, template.publish
 * - Integrations: integration.connect, integration.disconnect, integration.sync
 * - API Keys: api_key.create, api_key.revoke, api_key.rotate
 * - Security: auth.failed, access.unauthorized, rate_limit.exceeded
 * 
 * Database Schema:
 * - Table: audit_logs
 * - Migration: 007-create-audit-logs-table.ts
 * - Indexes: account_id, user_id, action, (resource_type, resource_id), status, created_at, (account_id, created_at)
 * 
 * Usage:
 * - Created via AuditService.log()
 * - Queried via AuditService.findLogs()
 * - Automatic creation via @AuditLog() decorator
 * 
 * Security:
 * - Multi-tenant isolation enforced at query level
 * - No cross-account access permitted
 * - Immutable records prevent tampering
 * - Sensitive data sanitized (passwords never logged)
 * 
 * Compliance:
 * - SOC 2 Type II: Comprehensive audit trail
 * - GDPR Article 30: Record of processing activities
 * - GDPR Article 32: Security of processing
 * - CCPA: Consumer data tracking
 * - Retention: 7 years default (configurable per account)
 * 
 * Example Records:
 * 
 * 1. User Login:
 * {
 *   account_id: '123e4567-e89b-12d3-a456-426614174000',
 *   user_id: '123e4567-e89b-12d3-a456-426614174001',
 *   action: 'user.login',
 *   resource_type: 'user',
 *   resource_id: '123e4567-e89b-12d3-a456-426614174001',
 *   ip_address: '192.168.1.100',
 *   user_agent: 'Mozilla/5.0...',
 *   status: 'success',
 *   metadata: { login_method: 'email' }
 * }
 * 
 * 2. Document Update:
 * {
 *   account_id: '123e4567-e89b-12d3-a456-426614174000',
 *   user_id: '123e4567-e89b-12d3-a456-426614174001',
 *   action: 'document.update',
 *   resource_type: 'document',
 *   resource_id: '123e4567-e89b-12d3-a456-426614174002',
 *   old_values: { status: 'pending', confidence: 0.85 },
 *   new_values: { status: 'approved', confidence: 0.95 },
 *   ip_address: '192.168.1.100',
 *   status: 'success',
 *   metadata: { processing_time_ms: 1250 }
 * }
 * 
 * Schema defined in migration 007-create-audit-logs-table.ts per Section 0.2.5
 */
@Entity('audit_logs')
@Index(['account_id'])
@Index(['user_id'])
@Index(['action'])
@Index(['resource_type', 'resource_id'])
@Index(['status'])
@Index(['created_at'])
@Index(['account_id', 'created_at']) // Compound index for time-based queries per account
export class AuditLog {
  /**
   * Primary key - UUID for globally unique audit log entries.
   * Auto-generated by database on insert.
   */
  @PrimaryGeneratedColumn('uuid')
  id: string;

  /**
   * Account identifier for multi-tenant isolation.
   * Required field - every audit log must belong to an account.
   * Indexed for efficient filtering and security enforcement.
   * All queries MUST filter by account_id to prevent cross-tenant data access.
   */
  @Column({ type: 'uuid', name: 'account_id', nullable: false })
  @Index()
  accountId: string;

  /**
   * User identifier who performed the action.
   * Nullable for system-initiated actions (e.g., automated processing, scheduled jobs).
   * Indexed for user activity tracking and auditing.
   */
  @Column({ type: 'uuid', name: 'user_id', nullable: true })
  @Index()
  userId: string | null;

  /**
   * Action type performed (e.g., 'user.login', 'document.upload', 'document.approve').
   * Uses dot notation for hierarchical categorization.
   * Required field - must always specify what action occurred.
   * Indexed for action-based filtering and reporting.
   * 
   * Common action patterns:
   * - Authentication: user.login, user.logout, user.mfa, user.password_reset
   * - User Management: user.create, user.update, user.delete, user.role_assign
   * - Documents: document.upload, document.process, document.approve, document.reject
   * - Templates: template.create, template.update, template.delete
   * - Integrations: integration.connect, integration.disconnect
   * - API Keys: api_key.create, api_key.revoke
   * - Security: auth.failed, access.unauthorized, rate_limit.exceeded
   */
  @Column({ type: 'varchar', length: 255, nullable: false })
  @Index()
  action: string;

  /**
   * Type of resource being acted upon (e.g., 'user', 'document', 'template', 'api_key').
   * Required field - identifies the category of resource.
   * Indexed for resource-based filtering.
   * Used in combination with resource_id for precise resource tracking.
   */
  @Column({ type: 'varchar', length: 100, name: 'resource_type', nullable: false })
  @Index()
  resourceType: string;

  /**
   * UUID of the specific resource being acted upon.
   * Nullable for actions that don't target a specific resource (e.g., list operations).
   * Indexed for resource-specific audit trail retrieval.
   * Combined with resource_type for efficient lookups.
   */
  @Column({ type: 'uuid', name: 'resource_id', nullable: true })
  @Index()
  resourceId: string | null;

  /**
   * Previous values before the operation (for updates and deletes).
   * Stored as JSONB for flexible schema.
   * Nullable for create operations or when previous state is not applicable.
   * Sensitive fields (passwords, tokens) must be sanitized before logging.
   * 
   * Example for document update:
   * { status: 'pending', confidence: 0.85, approved_by: null }
   */
  @Column({ type: 'jsonb', name: 'old_values', nullable: true })
  oldValues: Record<string, any> | null;

  /**
   * New values after the operation (for creates and updates).
   * Stored as JSONB for flexible schema.
   * Nullable for delete operations or when new state is not applicable.
   * Sensitive fields (passwords, tokens) must be sanitized before logging.
   * 
   * Example for document update:
   * { status: 'approved', confidence: 0.95, approved_by: 'user-uuid' }
   */
  @Column({ type: 'jsonb', name: 'new_values', nullable: true })
  newValues: Record<string, any> | null;

  /**
   * Client IP address from which the action was performed.
   * Stored as PostgreSQL INET type for efficient IP-based queries.
   * Nullable for system-initiated actions without client context.
   * Used for security monitoring, geographic analysis, and forensics.
   * Supports both IPv4 and IPv6 addresses.
   */
  @Column({ type: 'inet', name: 'ip_address', nullable: true })
  ipAddress: string | null;

  /**
   * Client user agent string (browser/application identifier).
   * Nullable for system-initiated actions or API calls without user agent.
   * Used for client application tracking and security analysis.
   * Stored as text to accommodate long user agent strings.
   * 
   * Example: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36...'
   */
  @Column({ type: 'text', name: 'user_agent', nullable: true })
  userAgent: string | null;

  /**
   * Operation result status.
   * Required field - every operation must have a status.
   * Indexed for filtering failed operations and monitoring.
   * 
   * Values:
   * - SUCCESS: Operation completed successfully without errors
   * - FAILURE: Operation failed completely
   * - PARTIAL: Operation completed with partial success or warnings
   */
  @Column({
    type: 'enum',
    enum: AuditStatus,
    default: AuditStatus.SUCCESS,
  })
  @Index()
  status: AuditStatus;

  /**
   * Error message or details if operation failed.
   * Nullable for successful operations.
   * Stores exception messages, validation errors, or failure reasons.
   * Used for debugging, error analysis, and alerting.
   * Sensitive information (stack traces with paths) should be sanitized.
   */
  @Column({ type: 'text', name: 'error_message', nullable: true })
  errorMessage: string | null;

  /**
   * Additional contextual metadata about the operation.
   * Stored as JSONB for flexible schema.
   * Nullable when no additional context is needed.
   * 
   * Common metadata fields:
   * - processing_time_ms: Operation duration in milliseconds
   * - file_size_bytes: Document file size
   * - confidence_score: OCR confidence score
   * - integration_name: Name of external integration
   * - api_key_id: API key used for authentication
   * - request_id: Correlation ID for distributed tracing
   * - batch_id: Batch job identifier
   * - template_id: Template used for processing
   * 
   * Example:
   * { processing_time_ms: 1250, file_size_bytes: 2048576, confidence: 0.95 }
   */
  @Column({ type: 'jsonb', nullable: true })
  metadata: Record<string, any> | null;

  /**
   * Timestamp when the audit log was created.
   * Automatically set by database to current UTC time on insert.
   * Indexed for time-based queries and reporting.
   * Immutable - audit logs are never updated or deleted.
   * Used for compliance retention policies (default 7 years).
   */
  @CreateDateColumn({
    type: 'timestamp',
    default: () => 'CURRENT_TIMESTAMP',
    name: 'created_at',
  })
  @Index()
  createdAt: Date;

  // NOTE: No updated_at field - audit logs are immutable (insert-only)
  // NOTE: No lifecycle hooks needed - service layer handles validation
  // NOTE: No soft deletes - audit logs must never be deleted for compliance
}
